### ISSUE TITLE
BUG: Querying private Ecoverse, always returns "anonymousReadAccess":""true

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1374]
**Describe the bug**
Querying private Ecoverse, always returns `"anonymousReadAccess":"true"`,

**To Reproduce**
1. Go to https://dev.alkem.io/graphql
2. Perform the following query:
```
query {
  ecoverse(ID: "test") {
    id
    nameID
    agent{authorization{anonymousReadAccess}}
    community {      
      members {
        id
      }
    }
  }
}
```
3. Result:
```
 "data": {
    "ecoverse": {
      "id": "0743422c-2155-475a-8925-94391b97fba3",
      "nameID": "test",
      "agent": {
        "authorization": {
          "anonymousReadAccess": **true**
        }
      },
```
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6064fc9b-9806-4a4a-91ad-e2271c49be00)

**Expected behavior**
Querying private Ecoverse must return correct `anonymousReadAccess` value.

**Additional context**
Seems, that on the client, the correct value is returned.

**Comment by techsmyth** [comment]
The query above is returning the authorization on the **agent**, not on the actual ecoverse.

Try 

query {
  ecoverse(ID: "test") {
    id
    nameID
    authorization{anonymousReadAccess}
    community {      
      members {
        id
      }
    }
  }
}

**Comment by Comoque1** [comment]
I see.
![image](https://user-images.githubusercontent.com/23620658/133429388-31dbf7cb-b129-4e1f-a72f-2cc6ca9ad062.png)

Still, the access of registered user to the members must be forbiden.

**Comment by techsmyth** [comment]
Yes agreed, need to look at what is happening.

**Comment by Comoque1** [comment]
Tested on Dev env.
Looks OK now.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f78daa57-a586-4351-8634-296597b4cea2)
