### ISSUE TITLE
Extend authorization model with Opportunity Admin

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1380]
## Description
As a challenge owner I would like to be able to delegate admin rights on Opportunities

## Acceptance criteria

- [ ]  New authorization credential: Opportunity-Admin
- [ ] New mutations for adding / removing opportunity admins
- [ ] Update user membership to use new credential type

**Comment by Comoque1** [comment]
User can be granted with opportunityAdmin credentials, without being member of the parent Ecoverse.
When the ecoverse is private, the opportunityAdmin user cannot access the opportunity.
