### ISSUE TITLE
BUG: check for existing applications should ignore ones in final state

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1389]
**Describe the bug**
when checking if a user already has an existing application then the state should be checked that it is not final

**To Reproduce**
Create an application
Reject it
The user cannot create a new application as there is already one

**Expected behavior**
The business logic should check the state of the previous application. If it is not in a "final" state it should be rejected. Otherwise a new applicaiton can be created. 

NOTE: client for now has hard coded states.

**Comment by techsmyth** [comment]
This is resolved with #1149

**Comment by Comoque1** [comment]
Looks OK now.
