### ISSUE TITLE
Bug: Matrix server is unable to deal with the rate of incoming requests

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1397]
**Describe the bug**
Performance issue adding user to opportunity community, when "communications" are enabled.

**To Reproduce**
1. `Communications` are enabled on the SUT (i.e. https://dev.alkem.io/)
2. Using client or api, assign multiple users to an opportunity (I've done it using the poppulator)
3. See error 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/51665362-ba2a-4c0e-a622-83a73822782c)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c196d6e8-151f-4fb8-a627-6d9835a8237a)

**Expected behavior**
Users can be assign to opportunities communities, without having the requests failing, when `communications` feature is enabled.

**Comment by Enderedne** [comment]
I believe this is due to the request limitations that are set in Synapse. We send several requests to the server but I don't think they're excessive.

**Comment by techsmyth** [comment]
Requires updating the rate control defaults in homeserver.yaml:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/e8146003-45d4-41a3-9cc4-f31a7c03fd6a)

Directly in homserver file in server repo, demo repo, k8s

**Comment by Comoque1** [comment]
Using populator - all works.
There is comment in [issue](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/1440), explaining the current behavior. 

Closing this one.
