### ISSUE TITLE
Migration to repair the parentCommunity field on Challenges

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1409]
## Description
As a challenge owner I want that the validation for users being part of the parent ecoverse community is working

## Acceptance criteria

- [ ] Create a migration to set the parentCommunity field properly on all Challenges

## Additional Context
Please see the fix in https://github.com/alkem-io/server/pull/1408

Data that is updated is essentially the following (mockup code to illustrate logic):
foreach (const challenge in challenges) {
    const ecoverseID = challenge.ecoverseID;
    const ecoverse = await this.ecoverseService.getEcoverseOrFail(ecoverseID)
    const communityID = ecoverse.community.id
    await this.setParentCommunity(challenge, communityID);
}

Of course can also be done at the database migration script level. Key is that it iterates over challenges and then gets teh appropriate commintyID via the ecoverseID.

**Comment by Comoque1** [comment]
Data verification is applied on all environments after migration.

The following verification script was user:
```
SELECT co.parentCommunityId, c.communityId as challengeCommunityId, e.communityId as ecoverseCommunityId
from community as co 
INNER JOIN challenge as c ON c.communityId = co.id
INNER JOIN ecoverse as e ON e.id = c.ecoverseId
```
