### ISSUE TITLE
User preferences management api

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1410]
## Description
As a user I want to be able to manage the notifications that I receive. 

## Acceptance criteria
- [ ] User entity and GraphQL api extended with the ability to retrieve + update preferences, with multiple potential sections
- [x] Loading of preferences from json file

## Additional Context
https://miro.com/app/board/o9J_ll9M9ZE=/

Needed to allow more usage of notifications.

**Comment by Comoque1** [comment]
Global Admin cannot update its or the preferences of another user preferences
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5f9a49fa-1614-424c-b80f-3fde8aa6c606)

**Comment by Comoque1** [comment]
After resetting the user policies, still cannot update preferences.

**Comment by Comoque1** [comment]
Tested OK on DEV after policy reset.
