### ISSUE TITLE
BUG: RESET event on verified organisation, doesn't set correct state and nextEvents

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1413]
**Describe the bug**
Resetting verified organisation, doesn't set correct state and nextEvents.

**To Reproduce**
1. Go to https://dev.alkem.io/graphql
2. Set organisation to have state `manuallyVerified`
3. Perform the following mutation:
```
mutation eventOnOrganizationVerification($organizationVerificationEventData: OrganizationVerificationEventInput!) {
  eventOnOrganizationVerification(organizationVerificationEventData: $organizationVerificationEventData) {
    id
    status
    lifecycle {
      state
      nextEvents
    }
  }
}
```
```
{
  "organizationVerificationEventData":
  {
    "organizationVerificationID": "03af4746-f810-4b4e-8487-ba3de338690d",
  	"eventName": "RESET"
  }
} 
```
4. The same `state` and `nextEvent` is returned
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/92148eb0-6009-429b-8c7c-259e4761bcc9)

**Expected behavior**
TBD

**Comment by techsmyth** [comment]
Underlying reason is the following:
Warning: Event "RESET" was sent to stopped service "organization-verification". This service has already reached its final state, and will not transition.

Near term will remove the final state from the lifecycle definition on org verification.

**Comment by Comoque1** [comment]
Looks OK on Dev.
Now, resetting organization verification, sets the state to `notVerified`.
