### ISSUE TITLE
BUG: Creation time for Hub/Challenge and user assignments is too long with communications enabled

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1440]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/admin/
2. Perform the actions below

Hub and Challenge creation ~ 6 seconds
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3da751e8-3b6f-4611-9485-5ab929d13d98)

User assignment to hub community members  ~3,5 seconds
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/57f46181-0af7-4ed2-8d71-9287b87d28bd)

On ACC env. loading the 11 pending applications query takes ~ 6 seconds
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/184b21bc-9295-4265-a7aa-e6ecd2af340d)

**Expected behavior**
~mutations creating entities should not take more than ~0.50 (approximately) sec and should not be dependent on the call out to synapse server.

**Additional context**
calls out to matrix should be not awaited
Timebox to half a day. If it can't be fixed easily - hackmd with findings for follow-up.

**Comment by valentinyanakiev** [comment]
Needs to be verified with the latest set of fixes.

**Comment by techsmyth** [comment]
I do not think this is resolved: will still be slow, though maybe not as slow...

**Comment by Comoque1** [comment]
Tested on Test env with latest #1482.

Creation of Hub/Challenge takes ~ 2 seconds

Regarding user assignment to community the following behavior is experienced:
Assigning 16 users to the same community is fast in the beginning and as more the assigned users become, the slower the assignment mutation gets: 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8a1c2b92-e930-4d68-9761-00b2dff944b4)

If you look at the screenshot, you will notice, that almost every second request is slower than the first. Every third request is faster than the second, but in general the request execution duration grow exponentially.

Also, sometimes, request response is failing with error (`message: "Agent (ecoverse.member@alkem.io) already has assigned credential: ecoverse-member"`), but the user gets assigned

**Comment by Comoque1** [comment]
After commenting with @techsmyth agreed to move it back to backlog

**Comment by atstoyanov** [comment]
The result from profiling the `assignUserToCommunity` mutation
Most of the execution time is taken by `addUserToCommunityMessaging` -  98%
Adding user to room/group in matrix is taking ~1-7seconds.

![image.png](https://images.zenhubusercontent.com/5f3ccd6f7c7033ff3483f1b8/49297b80-ec8b-4648-8c18-4e080be25e4f)

**Comment by techsmyth** [comment]
Yes that much is clear. This particular card was to switch to using a callback instead of awaiting the promise.

**Comment by Comoque1** [comment]
Assignment to community duration is reduced by 5 times, which is significant improvement.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1a402d2f-4475-435d-9d87-361b79e2103c)

Entity creation takes around 1 second.
