### ISSUE TITLE
nameID validation mismatch with the client

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Server#1476]
## Description
Currently, the client has validation on nameIDs to be between **3** and **25** characters, **NO spaces** and lower case.
The server does not have such limitations, or at least not all of them.

## Acceptance criteria
- [x] Specific validator for nameID fields on the client, and apply to the different places where the user can enter a nameID: org, hub, challenge, opportunity, project

**Comment by Comoque1** [comment]
NameIds comparison
- [x] user - nameID is auto-generated on registration when using the client
- [x] organization - **OK**
- [x] hub - **OK**
- [x] challenge - **OK**
- [x] opportunity - **OK**
- [ ] aspect - nameId for aspect is generated from the displayName - currently it is possibly to set displayName with "spaces" and aspect is successfully created using the client and the api
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/48968e2b-a142-420e-a775-daaa94d29e8d)
- [ ] project - creating project with "spaces" for nameID iusing the client is setting "underscore", using the api, cannot be created project with spaces
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f9d9c822-18c4-4c07-92e4-18b382bdd757)

## NOTE:
The results above are observed before before having merged the [DTO validations PR ](https://github.com/alkem-io/server/pull/1957)
