### ISSUE TITLE
Spike: Evaluate usage DTO decorators to disallow empty strings + splitting the work

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1480]
## Description
As a developer I want to be able to specify input value checking cleanly on the DTOs

## Acceptance criteria

- [ ] Pick Challenge DTOs, apply the changes there and evaluate the impact (client, populator, client-lib etc.)
- [ ] An Epic as an outcome + stories breakdown on the work that comes out of it

Timebox to half a day

## Additional Context
The code below was added as a work around:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/4ed958e2-5bec-42eb-9109-76321ff1d2ca)

- [ ] For the mutations related to sending a message to another user / community room, the input validation should check that the message field length is greater than zero. 
- [ ] This validation should be added to all mutations that send messages: to a user, to a community room
- [ ] Work around validation should be removed
- [ ] Apply to discussion title + description, ....

**Comment by techsmyth** [comment]
there is now a minLength() decorator which can do this easily

**Comment by valentinyanakiev** [comment]
To be split into multiple stories and added as an epic
