### ISSUE TITLE
BUG: Creating entity and querying updateRooms as part of the creation, throws an error

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1484]
**Describe the bug**
Creating entity and querying `updateRooms` as part of the creation, throws an error.

**To Reproduce**
1. Go to https://dev.alkem.io/graphql
2. Perform the following mutation
```
mutation createEcoverse($ecoverseData: CreateEcoverseInput!) {
  createEcoverse(ecoverseData: $ecoverseData) {
    id
    nameID
    community {
      updatesRoom {
        id
        messages {
          id
          message
        }
      }
    }
  }
}
```
```
{
  "ecoverseData": {
    "displayName": "testZ",
    "nameID": "tun",
    "hostID": "energy"
  }
}
```

3. The entity is created, but an error is thrown:    ` "message": "Cannot read property 'getId' of undefined",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/51db60ac-6695-40f6-a1f4-a1ce12f27e6b)

**Expected behavior**
The entity is created, communityRoom is returned.

## Additional information
Querying the community `updateRoom` in a later request, returns correct data.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3de73e14-ef08-44f2-850b-eec14536b598)

**Comment by techsmyth** [comment]
Please retest this with the latest api...for me this was working now.

**Comment by Comoque1** [comment]
With latest changes on DEV env., the issue is not reproducible.
Closing it.
