### ISSUE TITLE
api: DiscussionRoom ==> community.discussions

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1485]
## Description
As a user I want a clean api that allows me to have discussions within a particular community

## Acceptance criteria
- [X] domain model extended to have a new entity: Communication
- [X] Communication entity to have the following fields: discussions, updates
- [X] Community entity extended to have a new child: Communication
- [X] domain model extended to have a new entity: 'Discussion'
- [X] Discussion entity has the following fields: title, category, messages

- [X] migration to move room id for updatesRoom to be under the Community entity
- [X] code restructured to have a communication folder
- [ ] client updated to work with the adjusted updates api: draft PR in place, mapping of IDs still needed.

**Comment by Comoque1** [comment]
Messeges created as part of discussion creation are not returned
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/82a8188d-0332-4bbd-8f23-64afceb7da53)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8d8470c5-86ef-4f5b-8979-b7787094ec77)

**Comment by techsmyth** [comment]
Yes this is an open point. I need to discuss this with Nikola. I will raise it as a separate issue.

**Comment by Comoque1** [comment]
1. User member of community can create discussion, but have no rights to send message to that discussion
2. Error is thrown when user not member of community, send message to a discussion
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d35414f9-56a2-4e26-ac72-b03efb9ae56b)
