### ISSUE TITLE
Add API logic for create Service Profile

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#1499]
## Description
As a DevOps engineer
I want to be able to manage my entities over the API.

## Acceptance criteria

- [ ] Service Profile can be created over the GraphQL API. There is a field in the User model already that supports it.

**Comment by techsmyth** [comment]
Note that for now we would just create the user as normal, but then do a mutation via the graphql api to set the flag indicating this is a service account. That is there and working.
