### ISSUE TITLE
Fix UUID fields length in the database

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#1502]
## Description
As a developer
I want to have consistent data approach
So that I have less risk of data errors.

## Acceptance criteria

- [ ] Write a migration to fix the length to UUID fields to 36. There are plenty of fields in the schema at the moment with 255.
- [ ] All decorators for UUID fields in entities should be the same

## Additional Context
- The migration needs to be ALTER and not DROP + CREATE
- Check the data consistency after the update

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/7b957ab1-eed6-4323-b669-bb2aa747412b)
e.g. hubID in the above

**Comment by Comoque1** [comment]
DEV env server doesn't load.
Migrations are failing:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/83568097-ba5f-47a8-882a-0a17dcd6b344)

**Comment by techsmyth** [comment]
Yes the migration currently has communicationRoomID / communicationGroupID on Updates coming through as 36, but these need to be 255. They are not UUIDs (they are identifiers that come from Matrix).

Also not sure about us making nameIDs look like UUIDs + having the same length - they are actually different so maybe they should just stay as they were?
