### ISSUE TITLE
BUG (PROD): Updates can only be removed by the user that created them

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1509]
**Describe the bug**
Updates can only be removed by the user that created them.

## Repro steps:
1. Navigate to ecoverse admin page 
2. Add 2 admins to it: admin1 and admin2
3. Create an update with admin 1
4. login with admin 2 + try to remove the update. The removal fails:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/06b9346f-6eb8-4b93-9fcb-df815c762fea)

**Expected behavior**
If the user is authorized by the Alkemio server to remove the message then the event (message) should be removed.

Note: this bug is affecting production in that there are now two updates on the digicampus ecoverse.

**Comment by Comoque1** [comment]
Tested OK on dev env.
