### ISSUE TITLE
Able to send message to a room immediately after creation

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1518]
## Description
As the initiator of a discusison I want to be able to send a message with creation

## Acceptance criteria

- [ ] Send a message as part of the discussion creation process

## Additional Context
Currently the sending of the message is failing. My hypothesis is that the user is not yet a member of the room as the invitation to accept event has not yet been accepted (separate event / acceptance loop).

Note: this may be related to server-1484

**Comment by Comoque1** [comment]
Tested OK with this branch on Test env.
