### ISSUE TITLE
BUG: Only user creating discussion,can send a message to it

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1526]
**Describe the bug**
Only user creating discussion,can send a message to it.

**To Reproduce**
1. Go to https://dev.alkem.io/graphql
2. Create discussion to a Hub with hub member
3. Create message to the discussion win Global Admin - request fails
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/59c21db2-94ba-4244-a6f9-d10cbdb900f5)

**Expected behavior**
Users members of a community or corresponding admins, can send messages.

**Comment by techsmyth** [comment]
This may need a deeper discussion re who is allowed to send into a discussion. I am not convinced a global admin should have this right if it is for a community...

**Comment by Comoque1** [comment]
Looks OK on DEV env.
Closing.
