### ISSUE TITLE
Default values for discussion category.

### ISSUE THREAD

**Issue by atstoyanov** [cherrytwist/Server#1538]
`createDiscussion` mutation does not require value for `category`. As result if discussion without category is queried the query fails if the category is selected, because empty string can't be represented in the enum.

Possible solutions:
1. Category field should be mandatory on creation. Migration is required.
2. Category field stays optional. The backend sets default value. Migration is required.

## Acceptance criteria

- [ ] Category field is mandatory

**Comment by techsmyth** [comment]
I think the category then should be required.

**Comment by Comoque1** [comment]
Looks OK on DEV
