### ISSUE TITLE
BUG: User leaving a community is failing to remove the user from the matrix room

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1539]
**Describe the bug**
The leaving of the matrix room is not actually removing the user as a member of the matrix room

**To Reproduce**
Add the user to a community
Remove the user from a community
Use the communication admin query to see memberships on that community: the user will be still listed as a member of the matrix room which should not be the case

**Expected behavior**
User is removed from the Matrix room when removed from the community.

**Comment by Comoque1** [comment]
Tested OK on ACC env using the following query:
```
query adminCommunicationMembership(
  $communicationData: CommunicationAdminMembershipInput!
) {
  adminCommunicationMembership(communicationData: $communicationData) {
    displayName
    id
    rooms {
      displayName
      extraMembers
      members
      missingMembers
      roomID
    }
  }
}

```

```
{
  "communicationData": {
    "communityID": "ccba6076-6675-46be-84a9-6fff3860041a"
  }
}
```
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/586db265-c6de-4010-935e-17e9e721baff)
