### ISSUE TITLE
BUG (PROD): Removing a discussion / updates is not removing the underlying matrix room

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1540]
**Describe the bug**
The removal of the wrapping entity within the alkemio server is not removing the supporting Matrix room

**To Reproduce**
1. Create a discussion
2. Remove the discussion
The room is still present in Matrix.

**Expected behavior**
The Matrix room should be removed when the Discussion / Updates entity is removed.

**Comment by Comoque1** [comment]
The issue is still reproducible for discussions
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/895acc3b-532a-4399-abea-32b7a22e7a62)

Also after removing the community to which the rooms relates, they are not removed.

Bring back to backlog.

**Comment by techsmyth** [comment]
As discussed, the rooms will still be there in synapse - but without any members.
