### ISSUE TITLE
Performance enhancement: Room invitations should not be auto-accepted

### ISSUE THREAD

**Issue by Enderedne** [cherrytwist/Server#1542]
## Description

Room invitations are currently sent when a user is added to a discussion created in their community. The more users are added to a community the more invitations will be sent and at some point the matrix server will begin failing the requests.

## Ideas

The room-auto-accept should be done on user log-in so that they are able to query and see all the discussions and updates for the community they are a part of.
Synchronously accepting the room invite should be applied only for the discussion creator.

## Acceptance criteria

TBD

**Comment by techsmyth** [comment]
This is addressed as part of the 1596 related branch: room memberships are no longer automatically accepted.
