### ISSUE TITLE
BUG ( High Severity): When running population with 100 users, server crash

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1550]
**Describe the bug**
When running population with 100 users, server crash.

**To Reproduce**
1. Using the populator, populate the following [data](https://stichtingcherrytwist.sharepoint.com/:x:/s/Contributors/EaTQAgVv6sxOjC52bFTCUA4BVUuuksuhlYBESEOKzbhypw?e=7tmBEk)
2. During the creation of user 81, the server crash due to JavaScript heat out of memory
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/70b2d200-5d07-425d-9ed7-e537701618b0)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c0bbeb6a-4093-403c-be31-84ea571270fd)

**Expected behavior**
Population with 100 user can be performed successfully.

## Additional information
After the server restart, the system is usable again.

**Comment by Comoque1** [comment]
The issue is still reproducible:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7f6435b0-d233-47b6-9389-1094a73c0881)

Tested a couple of times and happens around user 50+
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/14f8b229-b816-42f3-bdc0-693bb1ed0604)

**Comment by techsmyth** [comment]
Can you please set COMMUNICATIONS_AGENTPOOL_SIZE=20 in your .env file and see how it performs?

**Comment by Comoque1** [comment]
With before changing each COMMUNICATIONS_AGENTPOOL_SIZE, each time the "alkemio" db was recreated.

With COMMUNICATIONS_AGENTPOOL_SIZE=20, the population fails on 50th user and server restarts.
With COMMUNICATIONS_AGENTPOOL_SIZE=50, the population fails on 49th user and server restarts.
With COMMUNICATIONS_AGENTPOOL_SIZE=70, the population fails on 47th user and server restarts.
With COMMUNICATIONS_AGENTPOOL_SIZE=10, the population fails on 46th user and server restarts.

Obviously, after each population, the amount of successfully created users is less with at least 1. 
Bringing back to backlog.

**Comment by Comoque1** [comment]
Issue is not reproducible on Test env.
