### ISSUE TITLE
BUG: creating a user with  tagsets / references does not use that data

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1575]
**Describe the bug**
Use the populator to create new users. The tagsets / references are not created. 

**To Reproduce**
Run the populator. 
The requests are sent with the tagsets / references created - but they are not used in the creation process.
OR
create a new user using the updated graphql sample file for createUser

**Expected behavior**
Creating a user should also use the tagsets / references data on the created user.

**Comment by Comoque1** [comment]
Tested with graphql mutation, and all data was created successfully on dev env.
