### ISSUE TITLE
BUG: Cannot send update or create discussion on newly created opportunity

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1587]
**Describe the bug**
Cannot send update or create discussion on newly created opportunity

**To Reproduce**

1. Go to https://dev.alkem.io/admin/hubs/uwv/challenges/agile-werken/opportunities/new
2. Create new opportunity
3. Send update to the newly created opportunity - error is thrown: `message: "ER_NONUNIQ_TABLE: Not unique table/alias: 'community'"`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c0ca0faf-5587-4208-9675-869253b06f0b)

**Expected behavior**
Admin can create updates successfully, to newly created opportunities.

**Comment by valentinyanakiev** [comment]
The issue is in createDiscussion:

    const payload =
      await this.notificationsPayloadBuilder.buildCommunicationDiscussionCreatedNotificationPayload(
        discussion
      );

    this.notificationsClient.emit<number>(
      EventType.COMMUNICATION_DISCUSSION_CREATED,
      payload
    );
