### ISSUE TITLE
Add preferences for all events and templates

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#1588]
## Description
As an Alkemio admin / user
I want to have full control over the notifications I receive
So that my email is not spammed with information of no interest to me

## Acceptance criteria

- [ ] Add the following preferences to the server
   - [ ] Discussion Created - for admin
   - [ ] Communication Update Sent - for admin
- [ ] Add the preferences to the client web UI
- [ ] Pick the settings up in the notifications service and filter the events based on them

**Comment by techsmyth** [comment]
Pretty hard to add a preference for users that have not signed up :)
