### ISSUE TITLE
Allow retrieving specific canvases

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1589]
## Description
As a user I want to only load the canvases that I want to view

## Acceptance criteria

- [ ] Add an optional argument into the canvases field on context entity to allow specifying a list of canvas IDs to be returned.

**Comment by Comoque1** [comment]
Creating a Canvas and retrieving its name and values as a separate query, doesn't return the set data.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/31d0590b-f0d4-4753-9094-61c959a937ba)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ec15fe40-d022-46ea-b457-a804d6a6d91a)

**Comment by techsmyth** [comment]
The example above is querying the wrong context. It should be context.canvases, not the one on ecosystem model.
