### ISSUE TITLE
Add activity to organization to show the number of members

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1592]
## Description
As a user I want to get information as to the activity of an organization

## Acceptance criteria

- [ ] New activity field that provides the count of members without authorization

**Comment by Comoque1** [comment]
Look OK on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ed11ee72-89ab-4f5b-922f-68774fb2fe09)
