### ISSUE TITLE
Search availability and usage

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1598]
** Background
The server is rejecting search requests from users that are not logged in:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/e9b82142-cf93-460f-82be-8f76e96d0f77)

Related is the user experience when you just land on the site:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/544e4510-096a-4ef8-8f6a-b5f73590a100)

You go to the hub, and you think lets just try search - and you get the above page. Highly, highly unfriendely...

**To Reproduce**
Do not login
Trigger a search on the challenges explorer or search page. 

**Expected behavior**
Server: allow search for users that are not logged in, but do not search on Users unless logged in
Client: remove logic to block access to search if not logged in
Client: display a message stating that search does not cover Users if not logged in
Client: Challenge Explorer to show error messages that come back

**Comment by Comoque1** [comment]
Now unauthenticated user can use the search 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/49e5cde0-c9c9-453e-8e8e-38eddbc2dfed)

The last point: server error is not displayed on the client:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cb7d4216-d4e5-4ecd-b450-5ea1b7d3f063)

I'll raise another bug
