### ISSUE TITLE
BUG: User with rights, cannot create discussion on specific hub

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1603]
**Describe the bug**
User with rights, cannot create discussion on **specific** hub

**To Reproduce**
1. Go to https://acc.alkem.io/codefornl/community/discussions and authenticate with global admin
2. Error is thrown in the browser dev tool console
3. See error
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d935f729-d4b4-4849-ada5-9721d6dabd02)

**Expected behavior**
User with rights can create discussion.

**Comment by techsmyth** [comment]
This looks like a data issue: a field that should be set is not set. Please check with other data, and if not reproducible then close this issue.

**Comment by Comoque1** [comment]
Yes seems to be data related issue., with other communities works fine.
Closing.
