### ISSUE TITLE
BUG: Discussions messages are not received dynamically from community members

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1607]
**Describe the bug**

**To Reproduce**
0. Precondition: you are authenticated with 2 users from the same community and have opened the same discussion
1. Go to https://test.alkem.io/un-sdgs/community/discussions/2d72aa5e-d998-4b2b-9682-7e032b5855bf
2. One of the user sends a message - message is sent successfully. Notification and message are displayed on sender page. The user, that didn't send the message, receive notification for new message, but doesn't receive the message.

**Expected behavior**
When user 1 sends a message to a discussion, all community members that have the discussion open receive notification and the latest messages.

**Comment by Comoque1** [comment]
After testing the message retrieval from second user with Valentin, it appears that the messages are received from the second user, and at some point they stop. This behavior was observed on api level. There could be potentially issues with the actual message sending, rather than users filtering.

**Comment by techsmyth** [comment]
Please retest this based on the updated subscriptions implementation

**Comment by Comoque1** [comment]
The issue is still reproducible with server [branch-1563](https://github.com/alkem-io/server/pull/1625)

Sender made 20 comments on 1 discussion
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4254fcd5-05e7-4c48-a952-49c84b6a5eeb)

Subscriber received 5 out of 20 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ef224505-b5fb-4a88-8b87-198fac525517)

The messages received are as follows: 2, 7, 11, 16, 20.

Moving back to backlog

**Comment by Comoque1** [comment]
Looks better now on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/92636482-b0cc-4655-8508-7074d45a2d1c)
