### ISSUE TITLE
Refine authorization model around canvases

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1618]
## Description
As a member of a community I want to be able to create and edit canvases

## Acceptance criteria

- [ ] Allow members of a community to create / edit canvases
- [ ] Allow admins of a community to save a canvas as a template (restrict this?)

**Comment by Comoque1** [comment]
Community member doesn't have rights to save canvas changes 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/311a69eb-9f93-44e8-93da-108851a4a979)

**Comment by Comoque1** [comment]
The issue is still reproducible on DEV env., after the changes.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c8475797-6114-4f8f-b34d-153de2dc4845)
