### ISSUE TITLE
Spike: Latest version of TypeORM + see what is status of migrations

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1622]
## Description
As a developer I want that migrations are easy to generate

## Acceptance criteria

- [ ] Upgrade TypeOrm to v0.2.41
- [ ] Look at status of migrations under this version

## Additional Context

Timebox to 2 hours

**Comment by hero101** [comment]
## Results with `0.2.41`.
- Generating migration still produce the same results
- ![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/dda24b34-3e54-4638-87ff-e9a717a139a4)
- [relevant issue with 0.2.41](https://github.com/typeorm/typeorm/issues/8547)

## Results with `0.2.43` (latest at this time)
- Generating migration produce the same 1:1 results
- Also introduces some breaking changes to some of the migrations - `uuid4()` method is removed from `RandomGenerator` util
