### ISSUE TITLE
Communication subscriptions to be triggered from the domain model

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1633]
## Description
As a user I want to have events that allow the client to be updated in near real time

## Acceptance criteria
- [ ] Subscriptions related to communications are sent directly from the domain model. Two new subscriptions: communicationUpdateMessageReceived, communicationDiscussionMessageReceived
- [ ] The triggering of domain events based on events on the Matrix room timeline is disabled.

**Comment by Comoque1** [comment]
Tested on DEV env as follows:

### Users
 - Global Admin
 - Hub Admin
 - Hub Member the same user is Challenge Admin
 - Non Ecoverse user


- [ ] `communicationUpdateMessageReceived`
  - [ ] Public Hub
    - [ ] Hub update - all users receive 1st, 3rd, etc updates
    - [ ] Challenge update - all users receive 1st, 3rd, etc updates
  - [ ] Private Hub
    - [ ] Hub update - all users except **non-ecoverse** receive 1st, 3rd, etc updates
    - [ ] Challenge update -  all users except **non-ecoverse** receive 1st, 3rd, etc updates
 
- [ ] `communicationDiscussionMessageReceived`
  - [ ] Public Hub
    - [ ] Hub discussion message - all users receive **2nd, 4th,** etc updates
    - [ ] Challenge discussion message - all users receive **2nd, 4th,** etc updates
  - [ ] Private Hub
    - [ ] Hub discussion message  - all users except **non-ecoverse** receive **2nd, 4th,** etc updates
    - [ ] Challenge discussion message  -  all users except **non-ecoverse** receive **2nd, 4th,** etc updates

- [ ]  `applicationReceived` - error is thrown, when the subscription is started
```
subscription {
  applicationReceived(communityID: "17a31e74-9284-44ea-aaa5-4c56030c2b08") {
    applicationID
    communityID
    userID
  }
}
```
![image](https://user-images.githubusercontent.com/23620658/148416594-96df9928-e686-4351-bfb2-d7d8d6658c26.png)

@techsmyth, if you approve the results, we can close the issue.

**Comment by Comoque1** [comment]
Closing the issue.
In separate item will be addressed the [applicationReceived](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/1643) issue.
