### ISSUE TITLE
Public + private api end point

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1642]
## Description
As an admin I want to be better able to control which traffic should be authenticated and which does not need authentication

## Acceptance criteria
- [x] Routing to have a non-authenticated end point that forwards to the server without validating cookie-session
- [x] Public api exposed on a different path to the primary graphql end point: /api/public/graphql
- [x] Add a new path to be /api/private/graphql 
- [x] K8s Environments updated
- [x] Repositories updated: server, client

## Additional Context
Should we not also then restrict the graphql queries that are allowed on the public end point?

- /api/private/graphql - protected api
- /api/private/non-interactive/graphql - non-interactive logins for protected api
- /api/public/graphql - public api
- /graphql - playground has backend calls to /api/private/graphql
   - add me, hubs, configuration, metadata queries as default

remove /admin/graphql

**Comment by valentinyanakiev** [comment]
What do we do with /graphql and /admin/graphql?
