### ISSUE TITLE
Remove applicatioReceived subscription

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#1643]
## Description
As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

**Comment by Comoque1** [comment]
It is removed on Dev env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e44d665a-95e1-4c75-9450-7d2c0f3a07d6)
