### ISSUE TITLE
BUG: Mutation "adminCommunicationUpdateRoomsJoinRule" is failing on DEMO env.

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1674]
**Describe the bug**
Mutation "adminCommunicationUpdateRoomsJoinRule" is failing on DEMO env.

**To Reproduce**
1. Go to https://demo.alkem.io/graphql
2. Authenticate with GA
3. Perform the following mutation:
```
mutation adminCommunicationUpdateRoomsJoinRule(
  $changeRoomAccessData: CommunicationAdminUpdateRoomsJoinRuleInput!
) {
  adminCommunicationUpdateRoomsJoinRule(
    changeRoomAccessData: $changeRoomAccessData
  )
}

```
```
{
  "changeRoomAccessData": {
    "isPublic": true
  }
}
```
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f56a5d7c-ba16-426a-a378-a0aa00bd9474)

**Expected behavior**
GA must have rights to perform the mutation.

**Comment by valentinyanakiev** [comment]
2022-01-24 14:34:15,023 - synapse.access.http.8008 - 389 - INFO - PUT-13 - ::ffff:10.0.1.125 - 8008 - {@matrixadmin=alkem.io:matrix-demo.alkem.io} Processed request: 0.004sec/-0.000sec (0.000sec, 0.000sec) (0.000sec/0.002sec/1) 48B 403 "PUT /_matrix/client/r0/rooms/!XkOqEAfdjuwjlfdAli%3Amatrix-demo.alkem.io/state/m.room.join_rules/?access_token=<redacted> HTTP/1.1" "-" [0 dbevts]
2022-01-24 14:34:21,076 - synapse.http.server - 88 - INFO - PUT-14 - <XForwardedForRequest at 0x7feff79c6a60 method='PUT' uri='/_matrix/client/r0/rooms/!XkOqEAfdjuwjlfdAli%3Amatrix-demo.alkem.io/state/m.room.join_rules/?access_token=<redacted>' clientproto='HTTP/1.1' site='8008'> SynapseError: 403 - Unknown room

**Comment by valentinyanakiev** [comment]
Synapse returns **403 - Uknown room** - for each put request to the matrix API, generated with the mutation. We don't handle the erroneous state and don't propagate it properly to the client.

**Comment by valentinyanakiev** [comment]
The database data looks corrupt, e.g. in updates table:

```sql
SELECT * FROM alkemio.updates where communicationRoomID like '%alkemio.matrix.host%';
SELECT * FROM alkemio.updates where communicationRoomID like '%matrix-demo.alkem.io%';
```

Shows we have two different domains for updates / room IDs that will not work. Also, we have many `updates` entities without a communicationGroupID and communicationRoomID.

**Comment by valentinyanakiev** [comment]
Wipe communicationGroupID and communicationRoomID in Updates and Discussions and Communications tables

**Comment by valentinyanakiev** [comment]
```sql
SET SQL_SAFE_UPDATES = 0;
UPDATE `alkemio`.`communication` SET `communicationGroupID` = '' where `communicationGroupID` like '%alkemio.matrix.host%';
UPDATE `alkemio`.`updates` SET `communicationGroupID` = '', `communicationRoomID` = '' where `communicationGroupID` like '%alkemio.matrix.host%';
SET SQL_SAFE_UPDATES = 1;
```

**Comment by valentinyanakiev** [comment]
Tested the approach locally, it doesn't work.
