### ISSUE TITLE
BUG: Some users have invalid membership

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Server#1682]
**Describe the bug**
A user is not able to access their profile if they have an invalid membership, likely caused by invalid data integrity.

**To Reproduce**
1. Go to https://dev.alkem.io
2. Have an organization beforehand
3. Assign the user to the organization
4. Delete the organization
5. Access user profile page
6. User page is not found (data error)

**Expected behavior**
The user is able to access their profile page

**Screenshots**

![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/8e8a9e6f-4c84-45bc-b6bd-ae65748fa7c3)
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/ed75f45b-2ffe-4d73-944f-1852a7ac0964)

**Comment by techsmyth** [comment]
This is very likely tied to the org credential still being assigned to a user.

I just tried this issue with both my own profile and that of a test user locally, and the removal all worked fine.

**Comment by Comoque1** [comment]
Cannot reproduce on test environment as well.
Closing the issue.
