### ISSUE TITLE
Aspect entity refresh

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1683]
## Description
As a user I want to be able to create aspects with different types

## Acceptance criteria
- [x] Aspect entity refreshed to have the following fields:
- nameID to be used in the breadcrumbs and the URL
- displayName
- description
- authorization
- references[]
- tagset: Tagset
- discussion
- banner: Visual
- bannerNarrow: Visual
- createdBy
- [x] Mutations update to allow creation + deletion of aspects including the above fields, and ability to add / remove references on aspects.
- [x] Set of aspects to be offered updated to have the following entries: Knowledge, Stakeholder, Related Initiative
- [x] Migration in place for new data structure / relationships
- [x] Sample mutation to load aspects onto a Context via playground
- [x] Able to retrieve messages / send comments etc on the discussion
- [ ] Migration in place for existing data: title ==> displayName, framing + explanation ==> combined into description

Authorization: 
- [x] assign the CREATE_ASPECT privilege to (a) users that are members of the community (b) users that have the CREATE privilege
- [ ] assign the UPDATE privilege to (a) user that created the Aspect (b) users that have the UPDATE privilege on Context
- [x] Allow users that are part of the Community to provide comments onto an Aspect discussion

**Comment by Comoque1** [comment]
Looks OK, except the following issues, which are raised as separate bugs:
1. [BUG: Community members, doesn't have rights to create aspects](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/1696)

2. [BUG: Multiple aspects, can be created with same name id](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/1697)

3. [BUG: Creating aspect on Challenge/Opportunity, throws matrix error](https://app.zenhub.com/workspaces/alkemio-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/1698)
