### ISSUE TITLE
BUG: Missing validation on displayName for aspect creation

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1713]
**Describe the bug**

**To Reproduce**
1. Go to https://test.alkem.io/testecoeid55b116/context
2. Create new Aspect
3. Add long text for `displayName`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/51a1540f-a13b-48a9-960c-12918f53adcf)

**Expected behavior**
There is `displayName` length validation on client and server.
- min length - 3
- max length - 128
- check whether the displayName is not used already

**Comment by techsmyth** [comment]
Also given we generate the nameID from the displayName entered we also should put in a minumum text entry length of 3 if easy to do?
