### ISSUE TITLE
Templates for Hubs

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1714]
## Description
As a Hub admin I want to be able to have templates for my Hub 

## Acceptance criteria

- [ ] New field on a Hub: templates
- [ ] Templates to provide the following information: set of aspect type definitions, with for each the name of the type and the default value for the description field

**Comment by Comoque1** [comment]
The mutation and migration executes without errors.
@techsmyth, wonder if the following query, shouldn't return, the created template:
```
query configuration {
  configuration {
    template{ecoverses{name}}
    template{opportunities{aspects}}
  }
}
```
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1231a0b4-4faf-4e53-95d7-0f21d9c9db6c)
Currently, user can set whatever value want, for aspect `type`, using the api.

**Comment by techsmyth** [comment]
the template should be "owned" by the hub, hence it lives under the hub entity. The above would make it hosted on the platform which I do not think is right

**Comment by Comoque1** [comment]
Thanks, @techsmyth. Api test is added. Closing the issue.
