### ISSUE TITLE
BUG: Lifecycle - Incorrect state transition after "completed" state

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1739]
**Describe the bug**

**To Reproduce**
1. Go to https://acc.alkem.io/admin/hubs/un-sdgs/challenges/food/opportunities/222/lifecycle
2. Authenticate with GA
3. Create an opportunity 
4. Navigate to its lifecycle
5. Go through all states: new > beingRefined > inProgress > complete
6. Set the next state to be "abandoned" - the transition is to `archived` instead of `abandoned`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/041a328b-5162-4732-9269-47ee247e86f9)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/883c869f-e260-483c-b8b9-fe9e0527ca35)

**Expected behavior**
Correct transition is performed.

**Comment by techsmyth** [comment]
@Comoque1 closing as this is an error in the actual innovation flow machine definition, so a data issue
