### ISSUE TITLE
BUG: Canvas Lifecycle problems on MariaDB

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Server#1749]
**Describe the bug**
While working with a canvas and checking in, checking out, saving the states get mixed up and the next state is pointing to an invalid next state.
**This could potentially be affecting all lifecycles.**

**To Reproduce**
1. Create a canvas
2. Check it out (Edit)
3. Edit it
4. Check it in
5. The canvas is saved but it's not checked in

**Expected behavior**
For canvases: After checking out a canvas, it must be possible to be checked in again and visa versa.
Lifecycles must follow their correct state transitions.

**Comment by Comoque1** [comment]
Could be related to this one: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/1779

**Comment by hero101** [comment]
@Comoque1 This is observed on MariaDB only

**Comment by techsmyth** [comment]
Just tried the creating a canvas on mariadb, checking out, saving, checking in etc - all worked smoothly for me...
