### ISSUE TITLE
Canvases: Storage space allocation and performance

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1756]
## Description
As an Engineer I want to have canvases storage allocation and performance issues mitigated. 

As currently there is no limitation on the canvas size and there is possibility to upload images, the size of an canvas could easily  extend enormously. As a result the DB storage will increase. 
Using the client, a user could request a single canvas and the request for 1.46mb take around 800ms.
Using the playground there is no canvases request limitation and the server could get loaded hard from malicious usage, by requesting all canvases from all entities.

## Acceptance criteria

- [ ] MD file with analysis of sizing implications for canvases with images, with suggested approaches for how to manage this from both a design and operational perspective (limits on upload size?, separate storage?)

**Comment by techsmyth** [comment]
Closing as covered by #1609
