### ISSUE TITLE
Spike: Upgrade of Apollo 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1758]
## Description
Major upgrade of Apollo to v3 and the underlying libraries + transitive dependencies

## Acceptance criteria
 - [x] Upgrade to Alkemio Server implementation to the latest apollo-server-express (3.6.3)
 - [x] Upgrade graphql uploads following the Apollo v2 -> v3 migration guide
  - [x] Upgrade ws following the Apollo v2 -> v3 migration guide
  - [x] Upgrade graphql to v 15.5.1
 -  [x] Upgrade all transitive dependencies of the graphql / apollo-server-express libraries

- [x] Client implications, particularly re upload
- [x] NestJS implications

Timebox: 0.5 day

# Additional context
@nestjs/graphql needs to be updated to 10.0.6
[Apollo v2 -> v3 migration guide](https://www.apollographql.com/docs/apollo-server/migration/)

**Comment by hero101** [comment]
| package | old version | new version |
| ----------- | ----------- |  ----------- | 
| @nestjs/graphql  | 8.0.2 | 9.1.2 (v10 has breaking changes )
| graphql | 15.5.1 | 15.5.1 (@nestjs/graphql@9.1.2 has hard dependency to graphql@15.5.1) |
apollo-server-express|2.22.2| 3.6.3|
graphql-amqp-subscriptions|LATEST|
graphql-subscriptions|1.2.1|2.0.0|
graphql-type-json|LATEST
graphql-upload|12.0.0|13.0.0
@types/graphql-upload|8.0.6|8.0.11

> The installSubscriptionHandlers configuration option has been removed from the latest version of Apollo server
> and will be soon deprecated in this package as well. By default, installSubscriptionHandlers will fallback to use the
> subscriptions-transport-ws (read more) but we strongly recommend using the graphql-ws(read more) library instead.

**Comment by techsmyth** [comment]
Nice set of updates. What would be the key changes we would see from this set of updates? What are the breaking changes that come with @nestjs/graphql v10?

**Comment by techsmyth** [comment]
and a related question: this is in our blocked column: https://github.com/alkem-io/client-web/issues/858 - is this now something we can pick up?
