### ISSUE TITLE
Spike: Require email verification to create an account

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1759]
## Description
As a platform I want to ensure users have verified their email address before granting them rights on the platform

## Acceptance criteria
- [ ] Kratos to not create a session as part of the registration step
- [ ] Server to not accept mutations to create a user profile if the email is not verified
- [ ] Understand the impact on the tests + how to mitigate
- [ ] Page flows on client updated as per design

Timebox to half a day

## Additional Context
TBD - add a new exception type on the server to indicate that the session does not have a valid email?

- [Verification flow](https://images.zenhubusercontent.com/612cb1848a783db262f19451/317cf032-14e9-4386-a3d3-d9fad73f27f1)
- [Sign up callback page](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/b3887ae4-5bbf-4443-b04b-1d199d45a90a)
- [Email not validated page](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/24bbe05e-6add-42d1-9bdc-631f876e1fb6)

https://xd.adobe.com/view/01e2a818-7c77-41a7-9b80-4319bdd4fbf2-54b1/

**Comment by Comoque1** [comment]
In order to identify all users that are not verified, the following query should be performed against kratos db `SELECT * FROM kratos.identity_verifiable_addresses where verified = 0`
