### ISSUE TITLE
Apple Sillicon Dev Support

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#1761]
## Description
As a developer
I want to be able to develop on Apple Silicon
so that I have my hardware of preference used for development.

## Acceptance criteria

- [x] There is a hardware setup for Apple Sillicon for the Alkemio Server and dependent services that works on M1, M1Max etc Apple Sillicon
- [x] There is a setup guide how to configure and run the setup
- [x] Use mariadb 10.7.1

**Comment by valentinyanakiev** [comment]
The lifecycle issue with canvases is not reproducible with the latest client version (containing the latest Excalidraw package).
The following issues were experienced:
1. Integration tests related to `organization verification` are failing:
  - [ ] when set event: "MANUALLY_VERIFY" 
  - **expected:**  state: "manuallyVerified", nextEvents: "["RESET"]", 
  - **actual**: "state": "verificationPending",
        "nextEvents": [
          "MANUALLY_VERIFY",
          "REJECT"
        ]
  - [ ] when set event: "RESET" 
  - **expected:**  state: "notVerified", nextEvents: "["VERIFICATION_REQUEST"]", 
  - **actual**:` "message": "Unable to update state: provided event (RESET) not in valid set of next events: MANUALLY_VERIFY,REJECT",` 
![image](https://user-images.githubusercontent.com/23620658/155617986-40d043c5-79b4-449a-a13e-695eb699d6bc.png)

2. Communications: all communications fail with the following error: `"message": "Cannot read property 'publish' of undefined",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8bdd5a77-8614-4385-82cc-e383ae510fc1)

3. I wasn't able to make the notifications working.
The error below was thrown on notifications service, when notification must be triggered.
![image](https://user-images.githubusercontent.com/23620658/155616999-835a93db-735a-424c-a49c-01306d8e32aa.png)
![image](https://user-images.githubusercontent.com/23620658/155617168-53567cf1-5974-4be4-a281-f66fd8bd996a.png)

**Comment by Comoque1** [comment]
Closing the issue and opening the following bugs:
1. Organization [verification flow](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/1791)
2. [Notifications service](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/notifications/97)
