### ISSUE TITLE
BUG: Registered user can set its preference to receive notifications similar to GA and GCA

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1768]
**Describe the bug**

**To Reproduce**
1. Go to https://acc.alkem.io/graphql
2. Authenticate with newly registered user
3. Perform the following mutation:
```
mutation updateUserPreference($userPreferenceData: UpdateUserPreferenceInput!) {
  updateUserPreference(userPreferenceData: $userPreferenceData) {
    id
    definition {
      type
    }
    value
    authorization {
      anonymousReadAccess
      myPrivileges
      credentialRules {
        grantedPrivileges
        resourceID
        type
      }
    }
  }
}

```
```
{
  "userPreferenceData": {
    "userID": "8cc51d1f-c645-454b-b837-a1ed1ac08409",
    "type": "NOTIFICATION_USER_SIGN_UP",
    "value": "true"
  }
}
```
4. The user can successfully update, but using the client there is a limitation.  
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7478a187-740a-4bcf-99a8-ca182a18c77f)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/f738bfc7-a0bb-4863-86eb-b88b909f5c0e)

**Expected behavior**
The preferences updates authorization through the api must be same as through the client.

**Additional context**

**Comment by techsmyth** [comment]
This is actually fine. It is ok that the user does update those preferences as in the future they may step into such a role. It is just that we do not show them on the client as that could be confusing.
