### ISSUE TITLE
Symbols in aspect's name makes it unable to be opened

### ISSUE THREAD

**Issue by oldhoyte** [cherrytwist/Server#1778]
**Describe the bug**
After writing special characters like slashes, i.e "Report 23/02", the aspect was unable to be opened.

**To Reproduce**
1. Go to 'https://demo.alkem.io/stopthetraffik/context'
2. Click on 'create aspect'
3. Scroll down to 'make aspect with forward slash in the name'
4. See error: you cannot open the aspect anymore 

**Expected behavior**
Opening the aspect should be possible.

Server should add an additional rule to the creation of nameID given the aspect title to remove characters such as /.

**Comment by hero101** [comment]
The nameID is not supposed to be changed. Not even from API.

**Comment by oldhoyte** [comment]
Ah, I thought that's what Neil asked me to put on the card (@techsmyth). 

But if you want to name the aspect: "Report 23/02", you cannot open it. Is it possible to fix that?

**Comment by hero101** [comment]
Description and title renamed to reflect the problem.

**Comment by Comoque1** [comment]
Tested on Dev env. and looks OK. The symbols from dysplayName are escaped in the nameID.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/03a98339-b3f6-405f-8cb2-c799f2824ac5)
