### ISSUE TITLE
Spike: usage of Apollo data loader

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1808]
## Description
As a user I want a performance platform
As an admin I want to optimize resources

## Acceptance criteria

- [ ] Evaluate the usage of Apollo data loader and how it could benefit our setup. Also relationship to pagination spike. 

Timebox to half a day.

## Additional Context
https://github.com/graphql/dataloader

**Comment by techsmyth** [comment]
It seems you are already busy with this one...

**Comment by valentinyanakiev** [comment]
Pagination and dataloader don't contradict each other. Dataloader is used to optimize batching requests to field resolvers, whereas paginated queries limit the data loaded (which can still use field resolvers in it).

**Comment by valentinyanakiev** [comment]
In the screenshot below, we have a real ```HubCommunityContributors``` query (1:1, without any modifications) - first 10 queries are with dataloader, 11-20 are without dataloader:

![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/362ee9ec-667b-460f-9ac6-74b3e6d91f66)

**Comment by valentinyanakiev** [comment]
On a field resolver to field resolver comparison, without guards, the optimization is 4x+.
