### ISSUE TITLE
Preferences on organizations + challenges

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1818]
## Description
As an organization / challenge admin I want to be able to set preferences

## Acceptance criteria

- [x] Organizations to have preferences
- [x] Challenges to have preferences
- [x] Migration in place to add preferences to challenges + organizations
- [x] Initial organization preferences: (a) "Automatically add new users with emails matching domain to Organization" -> false
- [x] Initial challenge preferences: (a) "Allow Hub members to Join", defaults to false (b) Allow Hub members to apply", defaults to true
- [x] Initial challenge preferences: (a) "Allow Hub members to provide feedback on Context", default false
- [x] api extended to expose preferences on both challenges + organizations
- [x] mutation for updating preferences on Organization
- [x] mutation for updating preferences Challenges

**Comment by techsmyth** [comment]
@hero101 I realized when working through the demo that we also need another preference on Challenge: enable feedback. Can you please add one for this?   "Allow Hub members to provide feedback on Context", defaults to false.

**Comment by hero101** [comment]
Will do.

**Comment by Comoque1** [comment]
The migration is failing and server service is failing to start on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d56bb3eb-c152-41db-b026-1235ab7ab2d4)
