### ISSUE TITLE
Expand the data size limit on Aspect descriptions

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1892]
## Description
As a STT user I want to be able to upload reports

## Acceptance criteria

- [ ] Expand the aspect description field length from 2k to 8k.

**Comment by Comoque1** [comment]
Tested with 55659 chars on DEV env and works fine.

**Comment by Comoque1** [comment]
The bug was tested with 55659 chars on DEV and they were set, when editing the aspect.
When create the aspect with that amount of chars, DTO error is thrown.

**Comment by techsmyth** [comment]
that is very surprising. So you cannot create with long text but can then edit to add the long text?
