### ISSUE TITLE
Location entity + migration

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1899]
## Description
As a user I want to be able to work with locations properly across Alkemio

## Acceptance criteria
- [ ] Location entity added to the domain model
- [ ] Profile entity to have a Location child that is managed over full lifecycle (create, update, delete)
- [ ] Context entity to have a location that is managed over full lifecycle (create, update, delete)
- [ ] User.city + User.country migration to the Location entity under Profile

**Comment by Comoque1** [comment]
Error is thrown, when searching data:
Env. (test)
Mutation:
```
query create($searchData: SearchInput!) {
      search(searchData: $searchData) {
        terms
        score
        result {
          __typename
          ... on User {
            id
            displayName
          }
          ... on Organization {
            id
            displayName
          }
        }
      }
    }
```
```
{
  "searchData": {
    "tagsetNames": ["Keyword"],
    "terms":["qa"],
    "typesFilter": ["user", "organization"]
  }
}
```
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/43ab2c80-2766-4987-b2af-7cce451e733d)
