### ISSUE TITLE
BUG:  Organization profile is not saving updated data

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1930]
**Describe the bug**
Update the profile of an organization and save it. The data does not get updated. 

**To Reproduce**
1. Go to the profile of an organization
2. change the description  or other field on the Profile entity and hit save
3. the updateOrganization mutation is being invoked with the correct data, but this is not being saved in the Organization Profile on the server

**Expected behavior**
The organization profile information should be saved.

**Comment by techsmyth** [comment]
With the latest development branches it looks to be working fine on the server, just that the web client is not using the returned data to populate the fields on the UI.

**Comment by Comoque1** [comment]
The issue is not reproducible on DEV env. anymore.
