### ISSUE TITLE
BUG: When two different users are assigned as leads to same community, error is thrown

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1946]
**Describe the bug**

**To Reproduce**
1. Go to http://localhost:3000/graphql
2. Assign user 1 as member and as leadUser to a hub community
3. Assign user 2 as member and as leadUser to the same hub community
4. See error: `"Max limit of users reached, cannot assign new user."`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/87a97dbf-492c-46b6-b551-dec184d93256)

**Expected behavior**
No error is thrown, when assign second user as community lead.

**Additional context**
- Mutation to assign user as lead to community:
```
mutation assignUserAsCommunityLead($leadershipData: AssignCommunityLeadUserInput!) {
  assignUserAsCommunityLead(leadershipData: $leadershipData) {
    id,
  }
}

Variables:
{
  "leadershipData": {
    "userID": "uuid",
    "communityID": "uuid"
  }
} 
```

**Comment by techsmyth** [comment]
@Comoque1 The limits are dependent on the policy for the community. There can for example be more than one lead organization for a Challenge - and this is required. 

For a User, there is a max of 2 in the lead role.

**Comment by valentinyanakiev** [comment]
export const hubCommunityPolicy: CommunityPolicy = {
  member: {
    credential: {
      type: AuthorizationCredential.HUB_MEMBER,
      resourceID: '',
    },
    minOrg: 0,
    maxOrg: -1,
    minUser: 0,
    maxUser: -1,
  },
  lead: {
    credential: {
      type: AuthorizationCredential.HUB_HOST,
      resourceID: '',
    },
    minOrg: 0,
    maxOrg: 1,
    minUser: 0,
    maxUser: 2,
  },
};

**Comment by valentinyanakiev** [comment]
this is the policy in the server, I think we should be able to easily check these policies from the API and verify against them (with a field resolver)

**Comment by techsmyth** [comment]
@Comoque1 just tried this with adding two users as leads on both hub + challenge level, without any error being thrown.
