### ISSUE TITLE
BUG: Policy authorization reset failed for 5 prod users

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#1950]
**Describe the bug**

**To Reproduce**
1. Perform Authorization policy reset against hub `npm run-script authorization-reset-all-users`
2. The reset failed for the following user:
user.id === '46e124b3-8904-4ede-b6ec-097bffddf4f2' ||
user.id === '9316c475-4cc6-45d4-9231-6d3d884f5a24' ||
user.id === '97b36b7a-f765-4ef5-9ea0-4daa062c44cb' ||
user.id === 'ad013e98-2438-4555-84b4-aeddd824b643' ||
user.id === 'd82ac101-8d6a-4963-94aa-e6180173a67e'

**Expected behavior**
The policies for the users above are reset and the root cause is identified

**Comment by valentinyanakiev** [comment]
```sql
select `user`.`id`, `user`.`displayName`, `user`.`email`, `user`.`authorizationId`, 
`authorization_policy`.`credentialRules`, `authorization_policy`.`verifiedCredentialRules` from `user` 
left join `authorization_policy` on `user`.`authorizationId` = `authorization_policy`.`id`
where `authorization_policy`.`credentialRules` = '';
```

That explains it...

![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/cfce8c9e-409c-467e-a0c9-8d6e8a364c76)

**Comment by valentinyanakiev** [comment]
The users can't be reset because they don't have an associated authorization policy to them.

**Comment by valentinyanakiev** [comment]
```sql
SET SQL_SAFE_UPDATES = 0;
UPDATE `authorization_policy` RIGHT JOIN `user` on `user`.`authorizationId` = `authorization_policy`.`id`
SET `credentialRules` = '[{"type":"global-admin","resourceID":"","grantedPrivileges":["create","grant","read","update","delete"],"inheritable":true}]'
WHERE `authorization_policy`.`credentialRules` = '';
SET SQL_SAFE_UPDATES = 1;
```

That resets the policy to allow global admins full access to the resource.

**Comment by valentinyanakiev** [comment]
The issue is fixed, now next auth policy reset by a global admin will reset the policies successfully.
