### ISSUE TITLE
Community Policy exposed via GQL API

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#1955]
## Description
As an Alkemio user
I want to be able to check what are the community policies for my communities

## Acceptance criteria

- [ ] Hub / Challenge / Opportunity community policies exposed via GQL, e.g.:

```gql
query hubs {
  hubs {
    displayName
    community {
      displayName
      policy
    }
    challenges {
      displayName
      community {
      displayName
      policy
      }
      opportunities {
        displayName
        community {
          displayName
          policy
        }
      }
    }
  }
}

```

**Comment by Comoque1** [comment]
Works fine on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/602f4f39-0dcd-493b-9af2-7ccb2aba3656)
