### ISSUE TITLE
Spike: Update typeorm on alkemio server

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#1968]
## Description
As a developer, I want to be working with the latest versions of the frameworks in the project
so that I have the best feature set and least security vulnerabilities

## Acceptance criteria

- [ ] Update to typeorm 0.3.12

Timebox to a day.

## Additional Context

 - we are on typeorm@0.2.43

**Comment by Comoque1** [comment]
Tested on ACC env. and locally

When non admin user try to access other user profile, error is thrown and user is redirected to 404 page.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/198dc8a9-64da-4825-accf-1087ee47a5f8)
