### ISSUE TITLE
Add Collaboration entity to domain model

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2030]
)## Description
As a developer I want to have part of the move to call outs already in place

## Acceptance criteria

- [x] Collaboration entity added to domain model
- [x] Call out entity added to the comain model
- [x] Move Context.canvases to a new CallOut instance under the Collaboration entity
- [x] Move Context.aspects to a new CallOut instance under the Collaboration entity
- [x] Move Opportunity.relations to be a field on Collaboration
- [x] Canvas entity updated with bannerCard field of type Visual
- [x] Server layout updated to be as follows:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/5c66facf-5e97-4a3a-97fc-0431fa6ad27b) 
- [x] api updated to show collaboration + callouts
- [x] Client updated to retrieve canvases, aspects and relations from the call-outs on the collaboration entity
- [x] Mutations for creating Canvas updated to be: createCanvasOnCallout(), with associated DTO update
- [x] Mutations for creating Aspect updated to be: createAspectOnCallout(), with associated DTO update
- [x] Mutations for creating Relation updated to be: createRelation(), with associated DTO update
- [x] Migration
- [ ] test suites migrated
- [x] populator + client-lib updated

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/add4a2a4-9813-4605-a6c4-f614d0cedda0)

**Comment by alstojanovic** [comment]
@techsmyth do I change the bannerNarrow name to bannerCard for Aspect? Just checking.

**Comment by techsmyth** [comment]
Lets just leave it as it is, if we do it then we do so across all entities using banners on cards

**Comment by alstojanovic** [comment]
👍

**Comment by Comoque1** [comment]
No data loss or incorrect assignments of aspects, canvas or relations against different levels of entities identified after the migration.
