### ISSUE TITLE
BUG: Canvases are not initialized after migration

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2048]
**Describe the bug**
After  restoring the PROD db and applyed the migrations against latest develop branch of server/client-web and navigate to hub/challenge canvas tab, canvases request fails
**To Reproduce**

1. Get locally develop branch for client-web and server
2. Remove existing Alkemio db and restore prod db
3. Run migrations
4. Start server
5. Navigate to http://localhost:3000/open-innovation/challenges/canvas-templates/canvases
6. See error - ` "message": "Canvas not initialized: 000b7fbd-300d-4cc0-9cb5-1c84b109552d",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/eee690fb-8eba-475d-87a1-7ddf322a623a)

**Expected behavior**
None error is thrown, against prod data after running the migrations.

**Comment by techsmyth** [comment]
It looks like no Visual entity, with its own authorization etc, was created as part of the migration
