### ISSUE TITLE
BUG: GA doesn't have rights to delete/update default hub lifecycle template

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2060]
**Describe the bug**

**To Reproduce**
1. Go to http://localhost:3000/graphql
2. User GA
3. Perform the following mutation:
#### Delete
```
mutation deleteLifecycleTemplate($deleteData: DeleteLifecycleTemplateInput!) {
  deleteLifecycleTemplate(deleteData: $deleteData) {
    info {
      title
    }
  }
}

Variables:
{
  "deleteData": {
      "ID": "uuid"
  }
} 
```
#### Update

```
mutation updateLifecycleTemplate($lifecycleTemplateInput: UpdateLifecycleTemplateInput!) {
  updateLifecycleTemplate(lifecycleTemplateInput: $lifecycleTemplateInput) {
    info {
      title
    }
  }
}

Variables:
{
  "lifecycleTemplateInput": {
      "ID": "uuid",
      "info": {
        "title": "wow",
        "description": "wow this is great",
        "tags": ["Tag 1", "Tag 2"]
      },
      "type": "challenge",
      "definition": "wow"
  }
} 
```

4. See error: 
- Delete error: `"message": "Authorization: unable to grant 'delete' privilege: lifecycle template delete: 1d45635e-9b8b-4cf9-b18d-25fee12bc220",`

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/fee938f9-4ffa-422c-a667-9ad6fefc1dd3)A

- Update error: `"message": "Authorization: unable to grant 'update' privilege: update lifecycle template: 1d45635e-9b8b-4cf9-b18d-25fee12bc220",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5f8ee5ca-efc9-439e-8a61-bc845bd4b0c0)

**Expected behavior**
GA and HA admin can delete and update Hub default lifecycle templates.

**Comment by techsmyth** [comment]
Have you tried reseting the authorization on the Hub?

**Comment by Comoque1** [comment]
> Have you tried reseting the authorization on the Hub?

Yes, after reseting the policies, the result is same.
