### ISSUE TITLE
BUG: No notification is triggered on interestInCollaboration event

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2077]
**Describe the bug**

**To Reproduce**
1. Trigger test suites against develop branch of `server` and `notifications` repos
2. Command: `npm run-script test:communications ./test/functional-api/zcommunications/notifications/notifications-opportunity-collaboration.it-spec.ts` - the only passing test is the one that doesn't expect emails. Notifications service is  not triggered at all.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e1baaf21-fead-410b-94ce-6066bb5e9bbe)

**Expected behavior**
All tests are passing.

**Comment by techsmyth** [comment]
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/51637f57-31e9-4bab-8e25-9ee4251ce76d)
