### ISSUE TITLE
BUG: Members don't have rights to delete Canvas created by him

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2120]
**Describe the bug**

**To Reproduce**
1. Go to Explore / Canvas callout
2. Authenticate with Member (NOT ADMIN, HA, CA, OA)
3. Create Canvas
4. Delete the canvas - authorization error is thrown: `"message": "Authorization: unable to grant 'delete' privilege: delete Canvas: New Canvasfdsd",`

**Expected behavior**
Members of communities, must be able to delete canvases they created.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b8182711-1f88-498c-b4f3-17b223308de3)

**Comment by techsmyth** [comment]
The Canvas entity does not know who it was created by, so it cannot know who should be allowed to delete it.
