### ISSUE TITLE
Attach alternative text to visual

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#2140]
## Description
As a developer I want to have a text associated to every visual
As an accessibility champion I want all relevant images to have an `alt` text

## Acceptance criteria

- [ ] Visual entity to have an additional field: description
- [ ] Existing visuals to get relevant default description:
==> "Entity type" - "displayName"
- [ ] When Visuals are created the  default description should be as above
- [ ] Visual update mutation to allow optionally updating the description
- [ ] Minimum description length of 3 characters on the client + enforced on api

**Comment by techsmyth** [comment]
Split out into separate epic
