### ISSUE TITLE
BUG: Querying activity logs on challenge / opportunity collaboration, throws an error

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2158]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/graphql
2. Perform the following query
```
query activityLogOnCollaboration($queryData: ActivityLogInput!){
  activityLogOnCollaboration(queryData: $queryData) {
    collaborationID
    triggeredBy
    resourceID
    description
    type
  }
}
{
  "queryData":
  {
    "collaborationID": "6bca199d-eb38-424e-85db-9e579cc8ff68"
  }
}
```
3. Error is thrown: `"message": "No Callout found with the given id: 6bca199d-eb38-424e-85db-9e579cc8ff68",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/18b7ce0f-38b8-4804-9102-a5cce05b61f8)

**Expected behavior**
Correct activity logs are returned.

**Comment by techsmyth** [comment]
@Comoque1 just tried this locally and it is working fine for me on both challenge + opportunity. The error message should be that there is no **Collaboration** with given uuid - will fix that with the other issue re member joined not showing up. Can you please re-verify this one?

**Comment by Comoque1** [comment]
Wasn't able to reproduce it on DEV as well.
