### ISSUE TITLE
NotificationAdapter module

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2171]
## Description
As a developer I want all code related to notification sending encapsulated into a module for better maintainability / robustness

## Acceptance criteria

- [ ] NotificationAdapter module that encapsulates the sending of messages to the notification service

**Comment by Comoque1** [comment]
(On DEV env) Notifications for registered user are not received from GA and the registered user 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/4a816a74-4e2f-410f-b3eb-2311f0dfa323)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/78c72da5-564e-406d-9cce-639674fa19ab)

**Comment by Comoque1** [comment]
When user is created using `mutation CreateUser($userData: CreateUserInput!) {createUser(userData: $userData)` with the token from GA, previously 2 separate emails for success where sent -  one to the user that were registered and one to the GA. Nowall mails are sent to the GA, as it has registered again.

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c9339df2-eaf0-4f09-bc2e-b1b3cf8245bc)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/558bcf91-697c-4163-9194-2a4dd0d227b9)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/0243e8df-8a82-432d-826d-169cb8c65a44)

**Comment by Comoque1** [comment]
Raised separate bug with regards to the above comments (BUG: Notifications for registered user are not triggered #149).
