### ISSUE TITLE
Activities to provide additional information to build links for activity entries

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2181]
## Description
As a user I want to be able to directly link to cards / canvases

## Acceptance criteria

- [ ] Each activity entry to have an parentID field that is optional

**Comment by Comoque1** [comment]
@techsmyth, is it expected, entities created before this PR to have null for parentID?
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/efee43f1-3b25-4e42-ad70-a298c5d6cda4)

**Comment by techsmyth** [comment]
@Comoque1 for this card yes that is the case. I will make another migration to populate these fields for existing activity logs where makes sense (card created / canvas created)
