### ISSUE TITLE
Populate parentID for activityLog existing entries

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2193]
## Description
As a  user I want all links clickable

## Acceptance criteria

- [ ] parentID entries are set for cards and canvas creation entries, comment on card entries

**Comment by Comoque1** [comment]
After migration execution,  the parent ID is set to "undefined" to some entities. Moving back to backlog.

**Comment by techsmyth** [comment]
@Comoque1 for which types of activity log entries is parentID still undefined? For some of them the parentID is not needed e.g. calloutPublished does not need it, nor does the community Join activity.

**Comment by hero101** [comment]
We revised the migration logic with Valentin yesterday, but I guess it was not sufficient. NULL must be saved instead of `undefined` as a string. The bug was identified but we failed to fix it properly.

**Comment by Comoque1** [comment]
@techsmyth after deploying on ACC env, beside `callout-published` and `member-joined` for `discussion-comment`.
