### ISSUE TITLE
Review mandatory spaceID

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#2196]
## Description
As a developer 
I want to have properties set based on business logic validation rules and not the IDE
So that there is lesser risk in writing broken logic.

## Acceptance criteria

- [ ] hubID mandatory

## Additional Context

Search for //toDo make mandatory https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/2196

**Comment by techsmyth** [comment]
Fixed as part of storage buckets change PR
