### ISSUE TITLE
Spaces sorted by activity

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2204]
## Description
Display the hubs with the most activity first

## Acceptance criteria and must have scope
- [ ] Hubs() query to sort results as follows (a) public hubs before private hubs (b) activity metrics
- [ ] Schema for how to give the weight to different types of activity

## Stakeholders
tbd

## Timeline
tbd

**Comment by SimoneZaza** [comment]
Will be part of #1166
