### ISSUE TITLE
Allow Hub members to have membership rights on Challenge / Opportunity

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2220]
## Description
As a Hub admin I want (in some cases) that anyone who is a member of the Hub has full membership rights within all challenges / opportunities contained so that barriers to their contribution are minimized

## Acceptance criteria
Authorization page of Challenge to include 3 authorization preferences:
- [ ] Allow Hub members to participate.
- [ ] Allow non-members to read to content of this Challenge.
- [ ] Allow members of the Challenge to create Opportunities.

## Additional Context
TBD "Allow non-members to read to content of this Challenge and the underlying Opportunities" ???

OLD ACCEPTANCE CRITERIA
- [ ] Hub admins to have the option to grant Hub members ability to contribute to Challenges / Opportunities without being a member at those level
- [ ] Challenge admins to have the option to grant Challenge members ability to contribute to Opportunities without being a member at those level

**Comment by Comoque1** [comment]
On clean DB, Hub member, doesn't have rights to create aspect on hub callout
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/8265da15-c80d-4d83-a878-f42302eff0ed)

**Comment by techsmyth** [comment]
> On clean DB, Hub member, doesn't have rights to create aspect on hub callout ![image.png](https://camo.githubusercontent.com/30326f7ad18d0a67187af99a186c9b68b7104b8d08394dbe42c8ca7c4b19645a/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566356666396664353061316139346131663235663332632f38323635646131352d633830642d346438332d613837382d663432333032656666306564)

this should also now be addressed on the server-2220 branch
