### ISSUE TITLE
BUG: Innovation flow template for challenge / opportunity is not updated

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2225]
**Describe the bug**

**To Reproduce**
0. Precondition: there are 3 challenge innovation flow templates with same definitions
1. Go to https://acc.alkem.io/admin/hubs/release-13-07-22-hub/challenges/release-13-07-22-ch/innovation-flow
2. Admin changes the template to the second available - the request succeeds, but the title of the first applied innovation flow template is visible 

**Expected behavior**
The correct innovation flow template is displayed as definition as a title, when applied.

**Comment by Comoque1** [comment]
The issue is still reproducible on ACC with the specific challenge.

**Comment by larssondenise** [comment]
@Comoque1 this is still not working I am afraid. But needs higher priority as I tried changing the template with VNG in their Space
