### ISSUE TITLE
BUG: When callout is removed, the associated activity logs remain

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2232]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/activitylog-hub/explore
2. Create a callout and publish it - activity log is preserved for the event
3. Remove the callout - the activity log still returns data for the previous event

**Expected behavior**
When  callout is removed, activity log is cleaned from the event that has be removed.

**Comment by techsmyth** [comment]
@Comoque1 as discussed, this is not an issue...
