### ISSUE TITLE
BUG: When Admin assign user to community, activity log returns triggeredBy, the ID of the added user instead of the Admin

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2233]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/activitylog-hub/dashboard
2. Using GA assigns another user to the hub community
3. Check the data returned from activity logs - triggeredBy: returns the ID of the assigned user, instead of the GA id

**Expected behavior**
When user is assigned by an admin to a community, the parameter triggeredBy, returns the ID of the Admin, that assigns the user.

**Comment by techsmyth** [comment]
This raises an interesting point. The activtyLog entry **should** record the event as being done by the admin, but the user being added should then be in the resourceID and the parent used for the communityID.

To show the user that was added requires custom logic for this activity log entry on the client, as well as the updates as per this PR for the server.
