### ISSUE TITLE
Migration to single card Callouts

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#2239]
## Description
As an Admin
I want to be able to select a template for every new Card/Canvas on a Callout.
So that I have more structured Card and Canvas callouts. Example: I want users to share ideas on how to solve a problem, I want the community to share their knowledge on a topic, etc.

As an admin I want an easy way of creating a callout with a clear vision on what the different types are 

As a user I want a simple way to create a new card

## Acceptance criteria
Callout create:
- [x] buttons to chose between comments, cards or Canvases
- [x] Clicking on cards will open the option to chose a Card template from the card templates at Hub level
- [x] Update Permission section text

Card Create:
- [x] CardTemplate to be picked up directly from the Callout entity when adding a new contribution
- [x] Visuals for the card are picked up from the CardTemplate

Note: Card labels are always shown

Server:
- [x] Callout entity extended to allow selecting a cardTemplate
- [x] Update existing dto's
- [x] Migration to add the additional columns to the Callout entity

Migration of data:
- [x] Every callout of type Card gets a cardTemplate instance created and linked
   - [x] for callouts whose nameID starts with "card-default":: Type = "contribution", defaultDescription = "Please share your contribution. The more details the better!", visual=same as current "other" visual (if other was renamed then default to empty visual)
   - [x] for callouts with no cards, create cardTemplate with: Type = 'other', defaultText = '', visual=same as current "other" visual
   - [x] for callouts with a single card type used across all cards: Type = the card type, defaultText = '', visual=same as current "other" visual
   - [x] for callouts with multiple card types used: Type = 'other', defaultText = '', visual=same as current "other" visual

## Additional Context

https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Callouts?node-id=438%3A1487

**Comment by hero101** [comment]
- How do the additional types fit in the picture with the templates?
- How are the two new types and two templates related to each other?
- Does the template require the callout the have a single contribution, or are they used on all contributions?

**Comment by alstojanovic** [comment]
I can only answer the third question for now:
The template is used on all contributions. (i.e. you are able to create only idea cards on a Single Card Callout with the idea CardTemplate)

**Comment by hero101** [comment]
- Why is 'cardTemplate' field optional?

**Comment by larssondenise** [comment]
@hero101 In the design you mean? Not optional indeed, changed it!

**Comment by hero101** [comment]
No, in the AC it's explicitly optional

**Comment by alstojanovic** [comment]
It's not optional, changing the AC.
