### ISSUE TITLE
Move card to another callout

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2242]
## Description
As an admin I want to be able to move cards to another callout (of type card)

## Acceptance criteria
Client:
- [ ] Add a tab with "Move" icon to the card dialog that is shown to users with the "MOVE_CARD" privilege
- [ ] Client to open a tab in the dialog with a drop down of the list of available Callouts. Available callouts determined by: also in the same Collaboration, and of type CARD
- [ ] After doing the move, show a success message and reopen the same card in its new location

Server:
- [ ] New privilege: MOVE_CARD that is granted to admins (Hub Admin / Challenge Admin / global admins)
- [ ] New mutation on the server to specify the cardID to be moved and the target calloutID to move to: moveAspectToCollaboration
- [ ] Logic to check that the calloutID specified is of type CARD, and that the target Callout is in the same Collaboration

## Additional Context
https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Callouts?node-id=768%3A1954

**Comment by hero101** [comment]
- What does the question icon do?
- What happens after the 'move' button is pressed?

**Comment by techsmyth** [comment]
@me-andre on reflection, this one may need a bit of a discussion still as (a) the option to move should be dependent on the user having the MOVE_CARD privilege (b) the action of moving is a separate mutation, and not part of the updateCard mutation. @SimoneZaza we may need a short touch base on this tomorrow.

**Comment by alstojanovic** [comment]
@me-andre the design of this has changed. The first two points in the AC are not correct. The action is done not in a separate tab but in the settings tab.

**Comment by SimoneZaza** [comment]
@techsmyth I see the problem & have another look at it.

**Comment by techsmyth** [comment]
Great, please bring it to top of hit list as this issue is needed for next release…

**Comment by SimoneZaza** [comment]
@techsmyth Would this work? 
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/1cb43a98-2f15-45e6-87ae-489a45106778)
https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Callouts?node-id=768%3A1954

**Comment by SimoneZaza** [comment]
@techsmyth had a chat with @me-andre and we decided to go back to the other design without the extra dialog. Clicking Save will then first validate the input and then update & move the card.

**Comment by Comoque1** [comment]
Hub admin cannot move cards.
