### ISSUE TITLE
BUG: When entity that is used from activity logs is removed, the activity logs stop returning data

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2249]
**Describe the bug**

**To Reproduce**
1. Go to http://localhost:3000/activity-hub-tests/dashboard
2. Create a callout and publish it
3. Remove the callout
4. Navigate to dashboard and refresh the page - activity logs are not loading
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5287f524-233a-40d4-8ed4-2a27a7c948a9)

**Expected behavior**
Activity logs are returning the data.

**Comment by alstojanovic** [comment]
@techsmyth I looked at how the new activity service is working and there is no way to get the activities that are related to deleted entities. The parentID and resourceID will be invalid. Do we fix this by not displaying activities we cannot get the parrent and resource entity?

**Comment by techsmyth** [comment]
@alstojanovic yes that would be best for now - so catch the exception + log a warning.
