### ISSUE TITLE
Search api refactor to follow activityLog

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2259]
## Description
As a developer I want a server code base without circular code references, and that returns results in a format that are directly usage by the client

## Acceptance criteria

- [ ] Remove the Searchable interface in the server code base
- [ ] Allow multiple return entities per search result type e.g. opportunity results to also provide the containing challenge + hub

**Comment by Comoque1** [comment]
Closing the issue, but the [identified bug](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/2869), must be addressed.
