### ISSUE TITLE
BUG: User is unable to delete its own references

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2262]
**Describe the bug**

**To Reproduce**
1. Go to https://acc.alkem.io/user/evgeni-alkemio-1176/settings/profile
2. Authenticate with any user (not GA) that has references created from before (cannot define when)
3. Remove old existing reference - authorization error is thrown: 
`"message": "Authorization: unable to grant 'delete' privilege: delete reference: da2b01e6-e35b-477e-a511-d624736d3459",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/08c49fae-bf51-4489-9993-429f62236ac4)

**Expected behavior**
User can delete its own references.

**Comment by Comoque1** [comment]
For new references the issue is not reproducible. For references created before, the bug is still reproducible.

**Comment by techsmyth** [comment]
and what happens after a authorization policy reset?

**Comment by Comoque1** [comment]
After authorization reset, the behavior is the same.

**Comment by techsmyth** [comment]
@Comoque1 can you please run the following graphql query for a reference that is giving this issue:

query {
  me {
    profile {
      
      references {
        authorization {
        myPrivileges
        credentialRules {
          grantedPrivileges
          resourceID
          type
        }
      }
      }
    }
  }
}

Basically I want to see the privileges for that credential, and also what the credential rules are

**Comment by Comoque1** [comment]
Cannot reproduce the issue anymore on any env.
Closing it.
