### ISSUE TITLE
Fix server circular dependencies

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#2274]
## Description
As a developer
I don't want circular dependencies in my code
so that my code works.

## Acceptance criteria

- [ ] `CanvasTemplateResolverMutations` and `LifecycleTemplateResolverMutations` dummy code is removed from the original code and the tests pass

## Additional Context

https://hackmd.io/CccYSXsKQhuEF7HM-7P_1Q?edit

**Comment by techsmyth** [comment]
using dpdm get now the following output using the cardProfile branch:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/3ae60109-4aaf-45fd-aa43-d7558dc20038)

Only one of concern is the one around profiles - but that can be sorted later with a refactoring of profiles in general which we need to revisit.
