### ISSUE TITLE
cardProfile entity 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2278]
## Description
As a developer I want a codebase with less dependencies

## Acceptance criteria

- [ ] New entity: CardProfile that holds references, tagset + description from Aspect entity

**Comment by Comoque1** [comment]
It seems, that the migration failed on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b913a948-25fb-4f24-bd96-ead375b3ebe5)
