### ISSUE TITLE
AuthPolicy: multiple credential criteria per rule

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2283]
## Description
As a developer I want to have understandable authorization policy rules

## Acceptance criteria

- [ ] Credential rules updated to be able to take in an array of credential criteria to be matched on for granting the associated privileges
- [ ] Review of existing rules to use the new capability to reduce the set of rules

## Additional Context

This type of code gets simpler:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/9f8b16d9-ff76-4b36-9f98-c2c899df1c28)

resulting in credential rules like the following:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/7116611a-ca17-4f55-8338-3bad95e5c0a0)

**Comment by Comoque1** [comment]
All auth tests are failing, with difference "MOVE_CARD", which is expected, as they aren't updated yet.
Considering that the rest must remain the same, it looks OK.
