### ISSUE TITLE
BUG: authorizationPolicies in db not fully formed

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2287]
**Describe the bug**
Creating a new alkemio instance is resulting in a database with authorization policy entries with no credential rules

**To Reproduce**
Wipe db
create new db
run migration:run
start the server
look in the authorization_policy table ==> there are entries with no credential rules, which means the policy was not properly created

**Expected behavior**
All authorization policies in a new instance are properly created

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/8fb42068-cc32-43ee-a814-9a9ffbd3e3ed)

**Comment by valentinyanakiev** [comment]
backed out the changes where child authorization was validated and reverted

```ts
    let child = childAuthorization;
    if (!child) {
      child = new AuthorizationPolicy();
    }
    const parent = this.validateAuthorization(parentAuthorization);
```

**Comment by techsmyth** [comment]
Opened a new issue to ensure the code above is removed: https://github.com/alkem-io/server/issues/2300

Closing this.
