### ISSUE TITLE
 Database schema review, looking at FKs used, data field types, indexes, null / not null etc

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2328]
## Description
As an admin I want to have confidence that the design of the db is robust

## Acceptance criteria
- [ ] Review of all types in the db, identifying where there are inconsistencies
- [ ] Review of all 1-1 + 1-many relationships in the db, checking that FKs are properly set
- [ ] Migration script to address identified issues

**Comment by ccanos** [comment]
https://hackmd.io/na068Oq0R_WPlLE7Y0f0ag
