### ISSUE TITLE
BUG: The query InnovationPackCanvasTemplateWithValue returns multiple times the same canvas template

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2350]
**Describe the bug**

**To Reproduce**
1. Go to https://acc.alkem.io/graphql
2. Perform the following query:
```
query InnovationPackCanvasTemplateWithValue($canvasTemplateId: UUID!) {
  library {
    id
    innovationPacks {
      id
      displayName
      templates {
        canvasTemplate(ID: $canvasTemplateId) {
          id
          info{title id description}
        }
      }
    }
  }
}

{
  "canvasTemplateId": "ae3cc5e4-3229-4d0e-a6c1-82e50c81fe97"
}
```
3. In the results the same canvas template is returned 7 times with the canvas value
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/075f4076-40e9-477e-8a77-80a35fecafe4)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/071c6fd6-3fdd-45cc-80cd-a0bae3f4c1df)

**Expected behavior**
The filtered canvas template is returned only ones.

**Comment by techsmyth** [comment]
@alstojanovic can you put an estimate on this one?
