### ISSUE TITLE
BUG: Hub / Challenge / Opportunity deletion is failing

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2358]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/admin/hubs/move-card/challenges with GA
2. Delete a challenge - error is thrown: `"message": "ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`alkemio`.`community`, CONSTRAINT `FK_35533901817dd09d5906537e088` FOREIGN KEY (`policyId`) REFERENCES `community_policy` (`id`) ON UPDATE NO ACTION)",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5324d2a1-c139-48dc-8fa6-735c0cead176)

**Expected behavior**
Hub / Challenge / Opportunity can be removed successfully.

**Comment by techsmyth** [comment]
@Comoque1 which environment is this on? This looks like the migration issue we had a while back re NOT NULL has come back.

**Comment by Comoque1** [comment]
@techsmyth,  DEV env. I also flagged the bug as high priority, as the data doesn't load at on the client, which impacts testing.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cc142e11-d354-4f39-948f-2392471fffc9)

**Comment by techsmyth** [comment]
this is that the migration was run with the old migration. Remember the discussion with Svetlo where we did not put in a new migration but instead updated the old one, that had already been run on Dev?

If you revert / redo to before the migration it should be ok, or just drop the current db on dev.

**Comment by Comoque1** [comment]
After recreating the Alkemio db on DEV env, the issue was not hit anymore. Tried it on TEST env as well, and not reproducible.
