### ISSUE TITLE
Communication entity at Platform level

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Server#2383]
## Description
As a member of Alkemio
I want to have a forum where I can share my thoughts and experience
So that <some business value>

## Acceptance criteria
- [ ] Platform entity added
- [ ] Communication entity as field on Platform entity: platform=>communication
- [ ] Library moved to also be a field under Platform
- [ ] Read access is granted to Communication entity for all Alkemio users
- [ ] All Alkemio users can initiate a discussion and write comments

**Comment by techsmyth** [comment]
delete discussion: global admins, if you created it
delete messages : global admins, user that created the message
update discussion: global admins

**Comment by Comoque1** [comment]
Creation of discussion on platform level on DEV env. fails with error: `"message": "Unable to find Community for Discussion: 4e8d1e70-f279-4c6b-b6f6-63205855f7f7",`, but the discussion is actually created.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/055cc34b-dff7-45c9-9821-5d26d56caa26)

```
mutation createDiscussion($createData: CommunicationCreateDiscussionInput!) {
  createDiscussion(createData: $createData) {
    id
    category
    commentsCount
    createdBy
    description
    id
    messages {
      id
      message
      sender {
        id
        email
        displayName
      }
      timestamp
    }
  }
}
```
```
{
  "createData": {
    "category": "GENERAL",
    "communicationID": "63c051e9-b174-4741-9e36-8ed50f9d45c5",
    "description": "test",
    "title": "test"
  }
}
```

**Comment by techsmyth** [comment]
@Comoque1  actually the discussion does get created, it is the notification related to it that fails...will have a look.

**Comment by Comoque1** [comment]
The issue mentioned above is resolved.
Raised another [bug](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/2447): Registered user (not GA), cannot send comments to platform discussions created by them or by GAs
