### ISSUE TITLE
BUG: User member and lead of Hub / Challenge / Opportunity, leave the communities, cannot access its profile

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2408]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/
2. Assign user as member to Hub / Challenge / Opportunity and as lead to the Challenge and Opportunity
3. User leaves the communities
4. User refresh its profile page - error is thrown
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/05eee605-dee0-4bd1-9a02-1ef75154c41a)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/344927cf-5a2e-410a-ad36-056a1abb5684)

**Expected behavior**
TBD

**Comment by techsmyth** [comment]
@me-andre this looks actually to be a client issue, the server is returning the data ok. For after the release.

**Comment by me-andre** [comment]
This seems to be caused by a user not being able to "read" the community while still remaining a lead (after being removed as a member).
I wasn't able to reproduce it in the latest develop though.

**Comment by Comoque1** [comment]
@me-andre, You are right, the error is not thrown on DEv environment anymore and regarding  the role (lead, host, etc..)
In terms of behavior the issue still remains, as when a user trigger "removeUserAsCommunityMember"  (Leave button), hub must not see the card on its membership anymore.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/29e9557e-be58-4150-944e-073cca491658)

@techsmyth, please share your thoughts on expected behavior.

**Comment by Comoque1** [comment]
After a discussion with @techsmyth, we agreed that behavior around user membership must be addressed as part of a separate epic (Membership models #935). Closing this issue.
