### ISSUE TITLE
Top level direct queries for Context, Community, Collaboration

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2425]
## Description

As a <client developer I want a streamlined code base

## Acceptance criteria

- [ ] New top level queries to support directly accessing context, community, collaboration

**Comment by Comoque1** [comment]
Tested All roles / Configurations and GA/GHA don't have `grant` privileges to Private Challenge and its Opportunity.

[Callout](https://acc.alkem.io/diagrams-hub/contribute/callouts/diagrams-toplevel-9940) with Public hub results
[Callout](https://acc.alkem.io/diagrams-hub/contribute/callouts/diagrams-3886) with Private hub results (could be out of date, as I saw different behavior related to 'contribute')

**Comment by Comoque1** [comment]
Closing the issue.
Based on the discussion during SEE we agreed, that these changes are going to be reverted and will be added more concrete top level queries: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/2452
