### ISSUE TITLE
Community Forum types + authorization

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2427]
## Description

As a user I want to be able to participate safely in Community discussions with valid categories

## Acceptance criteria
- [ ] Categories are platform functionalities, community building, working challenge centric, need help, and other
- [ ] Delete access to a discussion, for deleting messages, granted to GA, Author of message
- [ ] Delete access, to delete a discussion, granted to GA, Author of Discussion

## Additional Context
Split out from #server-2383

**Comment by Comoque1** [comment]
Global admin, doesn't have rights to create a comment to discussion
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6c98e164-2b0c-4ca0-b430-555398b2dd2a)

**Comment by Comoque1** [comment]
Closing the issue, but scenarios related to Community members messages  (Send / Delete) are blocked to be performed due to this bug: BUG: Community members don't have rights to send comments to community discussions #2483
