### ISSUE TITLE
BUG: User can send comment with more than 49000 chars, when validation on client says:500

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2433]
**Describe the bug**

**To Reproduce**

1. Go to https://dev.alkem.io/hub-ch-private/challenges/hubmemberchallenge-4649/contribute
2. Make a comment bigger than 500 chars - it is successfull
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/54579f34-4310-4b10-9aae-6a865fd93763)

**Expected behavior**
TBD

**Comment by techsmyth** [comment]
DTO validation to be added
