### ISSUE TITLE
Elastic data ingestion & data fields picking

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Server#2435]
## Description

As a developer
I want to use the already available infrastructure and code
OR
I want the available instructions and code samples
So that I am able to feed data to Elasticsearch

## Acceptance criteria

- [ ] Data objects are fed to Elasticsearch
- [ ] The needed data fields are decided in order for the required charts from the [epic](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/alkemio/921) to be built.
 - [ ] Data is fed at the time of the activity event since no heavy load is expected

**Comment by valentinyanakiev** [comment]
In professional wording, you want end-to-end `Data ingestion pipeline` feeding your `data lake`. That is pretty much your AC, in my opinion.

**Comment by valentinyanakiev** [comment]
In professional wording, you want end-to-end `Data ingestion pipeline` feeding your `data lake`. That is pretty much your AC, in my opinion.
