### ISSUE TITLE
BUG: Hub member has access to private challenge

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2443]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/graphql
2. Perform the following query with user that is member of the hub:
```
query {
  hub(ID: "private-hub3") {
    authorization {
      myPrivileges
      anonymousReadAccess
    }
    community {
      memberUsers {
        email
      }
    }
    challenges {
      nameID
      displayName
      community {
      memberUsers {
        email
      }
    }
      authorization {
        myPrivileges
        anonymousReadAccess
        credentialRules {
          grantedPrivileges
          criterias{resourceID type}
          inheritable
        }
      }
    }
  }
}
```
3. In the results, it shows up, that hub member has `READ` privileges to a private challenge, when it it is member of a parent hub
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c0ec4b2b-8e14-4bf2-a33c-f64447e39f43)

**Expected behavior**
Hub member, cannot read challenge data if it is private.

**Additional context**
Authorization policy reset is performed.

**Comment by techsmyth** [comment]
@Comoque1 I am not seeing this behavior. For me when I have the flag for "allow anonymouse read access" set to false then I get the following:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/944ff570-c360-4fd0-b833-3ea1019bbb6e)

and when I set it to true I see the following: ![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/609e236b-e461-4f82-93d0-58d19099c54a)

Can you please re-test?

The anonymous read access flag you can actually ignore and just look at the privileges. Note that some fields on a Challenge are not super restricted, we may separately want to revisit that.

Also we may want to rename these preferences are they are confusing - maybe something like "Require membership to read the contents?" @larssondenise thoughts?

**Comment by Comoque1** [comment]
After some additional investigation, it appears, that the issue above is experienced fro **private** Hubs only: 
1. Create Private Hub and Private challenge, 
2. Assign user to the Private Hub
3. Perform the query: 
```
query {
  hub(ID: "pirvate-hub1") {
    authorization {
      myPrivileges
      anonymousReadAccess
    }
    challenges {
      nameID
      displayName

      authorization {
        myPrivileges
        anonymousReadAccess
      }
    }
  }
}
```
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3e525444-2902-4899-b3cd-bf1213752cf1)

When the hub is set to **public**, all works as expected:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/726851ac-1dd0-444a-a77d-0ef471e16c3d)
