### ISSUE TITLE
Migration to single Canvas type Callout

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#2451]
## Description
Old Canvas Callouts data needs to be merged to the Single Canvas Type Callouts.

## Acceptance criteria

- [ ] Every callout of type Canvas gets a blank canvas as the canvasTemplate instance created and linked

Note: Create a blank canvas encoding to write as value for the blank canvas templates. When editing a Callout, Admins can set a canvas template from Hub templates or Library as the canvasTemplate for that Callout.

## Additional Context
https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Callouts?node-id=568%3A1687

**Comment by techsmyth** [comment]
@alstojanovic for all existing canvas callouts a blank canvas should be added that is the canvas contained by the Canvas Template. So migration can be very simple: just create authorization, create canvas template with empty canvas (just grab json from a graphql call) etc. If the admin later wants to set a particular canvas then they can do that via settings. 

Only question I have is how the setting of the canvas value works with migrations now that the canvas is encoded? Can we encode a raw excallidraw json file in the migration script?

**Comment by alstojanovic** [comment]
@techsmyth yes, all doable. The empthy canvas encoding can be generated and written as the value.
