### ISSUE TITLE
Graceful communication failure  Alkemio Server : Matrix

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#2459]
## Description

As DevOps engineer
I want my services to fail gracefully unless unrecoverable error happens
so that it isn't unnecessary down time.

## Acceptance criteria

- [x] The server should be able to start when Matrix is not up if COMMUNICATIONS_ENABLED is `false`.
- [x] If COMMUNICATIONS_ENABLED is `true`:
   - [x] No entities should be instantiated if Matrix is not accessible
   - [x] If a message to Matrix doesn't return a reply, the server shouldn't hang

## Additional Context

Currently, when the Alkemio Server bootstrap logic fails, it is a catastrophic failure and the server crashes with unrecoverable exception. If Matrix is down when the server starts, the server starts initializing the `communication` table and creates an entity that is out of sync with Matrix. The server hangs. Upon restart, and when Matrix is up, the server crashes because an exception is thrown that we try to create a room that already exists.

**Comment by valentinyanakiev** [comment]
To reproduce:

1. In order to reproduce it, just drop your DB, stop your matrix service, run migrations, run the server. It will get stuck.
2. Stop the server, start matrix, start the server.
3. You will get to the broken state.

The problem happens because when we start `Matrix adapter`, it reads the RabbitMQ queue, processeses and acknowledges the message, creating the entity in the postgres Matrix database, out-of-sync with the server.

**Comment by valentinyanakiev** [comment]
@techsmyth I think this problem is not that trivial at all. To elaborate:

1. I assume your gut feeling was that the message provided by the `Matrix` service was not in the same format as expected to be picked up and handled by the `communications` service. That is correct. I have a branch with a fix for that particular error.
2. Unfortunately, it is not the only step failing in the initialization. `Updates` entity was never initialized because the server never received a response beforehand. This can be handled, potentially, by timeouts, but logic on the server likely needs to be changed as well as there are multiple steps of the initialization workflow.

Most importantly, I believe we are doing this conceptually wrong. Splitting Matrix into its own microservice with its own lifecycle requires a slightly different approach from what we have used so far.

1. `Ensure...` should no longer be needed. It is redundant, literally. RabbitMQ + microservice policies ensure something gets initialized, not our server (anymore). If a message is not acknowledged, ensuring happens when a Consumer is up, consumes the message, and acknowledges it.
2. It might look like this is wrong at first glance, because we may end up in a situation where both services are not up at the same time. Well, that's the case anyway, we just don't handle it. I believe we should approach the initialization of the entities on the server in a `fire-and-forget` manner. We use promises and don't await them. We let RMQ + `Matrix adapter` handle creating the message based on acknowledge patterns. If the `Matrix adapter` (or postgres) is down, we'll get an error anyway, even if things were initialized properly.

**Comment by valentinyanakiev** [comment]
Forget about `fire-and-forget`, it seems we rely heavily on callbacks from the `Matrix adapter` to populate our IDs. We might need to add heartbeat service like [terminus](https://docs.nestjs.com/recipes/terminus) and to check whether `Matrix adapter` is up before we start the bootstrap process.

**Comment by techsmyth** [comment]
@valentinyanakiev could we not for now just trigger a simple call to the communication service as part of the bootstrap process? This could be anything that does not have a side effect. That would then wait until the service responds - we could even put it in a loop to try a couple of times...not super elegant but would work around the issue.
