### ISSUE TITLE
Domain model extended for InnovationSpace

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2531]
## Description

As a dev I want clear data model for Innovation Space

## Acceptance criteria

- [ ] InnovationSpace entity added at the Platform level

data model: tbd 
- selection critera; domain,
- associated org: org
- data selection: ...
- branding: visuals, description etc

## Additional Context
![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/4caf9709-bdfe-4818-9a0b-20864990634b)

**Comment by hero101** [comment]
This does not have enough information.
