### ISSUE TITLE
Search: contribution results with Cards

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2533]
## Description

As a user I want to be able to find cards that match my search terms

## Acceptance criteria

- [ ] New category of search results: Contributions
- [ ] CardSearchResults within this category

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by valentinyanakiev** [comment]
Queries used to test are in the [PR](https://github.com/alkem-io/server/pull/2537)
