### ISSUE TITLE
BUG: ApplicationFormData maxLength doesn't validate user input

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2577]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/graphql
2. Apply for the community: https://dev.alkem.io/sv-hub-bug/apply
3. Type in the first input field  string like '123' 
4. Apply - the request is successful even the maxLength for the field is 1
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b5a319d1-af46-4440-81b4-6f32d1dcfe4a)

**Expected behavior**
Validation is working as defined in applicationForm.

**Comment by techsmyth** [comment]
@Comoque1 this field is intended for the client to pick up, rather than being strictly enforced on the server api.

**Comment by techsmyth** [comment]
To be checked with new funcatinoality

**Comment by Comoque1** [comment]
@techsmyth, the client is not taking in consideration the `maxLength` and `explanation` fields.
I will move the story to new issues, to discuss.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6ffc711d-b0bd-48bf-a296-537fa215d6a3)

**Comment by techsmyth** [comment]
@Comoque1 understood, explanation is also not exposed on the client so can be ignored for now. Max length should be enforced on the client. I will raise a separate bug and close this one.
