### ISSUE TITLE
Spike: Investigate RolesUser performance

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#2603]
## Description

As a user I want a quick response time

## Acceptance criteria

- [ ] Investigate what is causing the large response time + propose / spike improvements to the code for addressing it

Note: any fix to avoid as far as possible lots of direct db queries as that will be hard to maintain. 

Time box to half a day. 

## Additional Context
This is a key query as it is run for all logged in users.

Analysis based on 2,609 records between 27 Jan 2023 - 28 Feb 2023
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/d33bc721-4af9-4ca9-95f5-0c062ed9d65d)
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/639a332f-f3a7-44ba-a463-7165913a8cd7)

**Comment by hero101** [comment]
Two screenshots with the elapsed time analysis attached :)

**Comment by techsmyth** [comment]
@hero101 really super that we are looking at this data. 

This can defiinitely be optimized, but there are two other related items that will also help
- a lot of users have orphaned credentials, which is killing the response time for them. There is a PR for a script to fix it + a bug raised to stop the leakage. This will have quite a big influence as I suspect this query of O(n2) so having users with a lot of extra credentials will have a big effect. I noticed for myself that by removing orphaned credentials my rolesUser query dropped from 3+ seconds to 1.2.
- please see client-3619: there is a new field to get the membership status that will reduce the usage of rolesUser - making this less urgent. 

But we do still need to look at this!

**Comment by techsmyth** [comment]
@hero101 @valentinyanakiev updated this to be a spike, and added description for that. First where is the time going in that particular service: community credentials / orgs etc? Or is it due to it scaling badly? To investigate and understand where the time is going, and potential fixes.

**Comment by hero101** [comment]
An update after the changes were deployed.
Below you can see the response times between the two deployed versions before and after the change. The actual change took place in [v0.46.4](https://github.com/alkem-io/server/releases/tag/v0.46.4).

v0.46.3
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/b7e8dc2e-1885-42e5-905d-14cb2837446a) ![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/2c13e6eb-9321-44d9-9192-9309e9454279)

v0.46.5
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/74e2f827-02c1-4b7f-b55c-e455e64459ad)![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/8379bf80-cb6d-4682-8529-00aadc958dca)

**Comment by techsmyth** [comment]
@hero101 really nice result, and great to see the data showing the actual impact!
