### ISSUE TITLE
BUG: Search is failing 

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#2615]
**Describe the bug**
Search is failing on common terms

_**To Reproduce**

1. Go to search page
2. Search for Digicampus, or "test"
3. No results are shown

**Expected behavior**
Digicampus is an organization on the platform and should be shown

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/c05749b4-f2e5-42d0-9ea7-98d586cf7d37)

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/6b881001-61e5-4df2-9995-71c7210b497f)

**Comment by valentinyanakiev** [comment]
The problem was with multiple orhpaned collaboration entities. The proposed fix works, tested locally with production-like data.
