### ISSUE TITLE
BUG: credentials are not being removed on challenge / opportunity / hub deletion

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2617]
**Describe the bug**
When deleting a hub / challenge / opportunity, the credentials associated with that entity are not being removed from user / organization profiles

**To Reproduce**
1. Go to cli repository and run the script: npm run authorization-detect-orphaned-credentials-from-users

**Expected behavior**
Lead / member credentials associated with a community are removed when the entity is deleted

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/13a073b1-db00-47a8-a4fd-ab120916331a)If applicable, add screenshots to help explain your problem.

**Comment by techsmyth** [comment]
@Comoque1 I tried the main scenarios creating / deleting hub with various roles, creating / deleting challenge with various roles, creating / deleteing opportunities with various roles, creating / deleting organizations with various roles - but I did not find in my testing any residual credentials.

Can you please try yourself to see if there are any credentials being left over?

**Comment by Comoque1** [comment]
Data that remains after deleting major entities:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3173ae25-f598-4b5b-92b2-b063b31cdd82)

**Comment by Comoque1** [comment]
@techsmyth Using the approach from the bug description, the script doesn't return any orphaned credentials on local environment
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7a21dab1-539c-4804-b0a7-99786d500a43)

Using the scripts pushed in the test branch are gathering leftover data after removing journeys and the organization.
The script tests the following:
 - get count of all tables ids (base data)
 - create organization
 - create hub
 - change hub preference
 - send community update
 - create callout on collaboraation
 - create canvas
 - create aspect
 - send comment to aspect
 - send comment to comments callout
 - create application
 - assign user as community member
 - assign user as community lead
 - assign organization as community member
 - assign organization as community lead
 - update hub visibility

 - delete hub
 - delete organization

 - get count of all tables ids (after data after hub / organization deletion)
data difference
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/813e4872-5682-4562-bc1e-b7bc83e86d9c)
The numbers are the new numbers, not the difference from `after - before`
For example `authorization_policy` = 529, but the actual difference is 20.  
Querying the deleted Hub id in `authorization_policy` table returns (59) records.
