### ISSUE TITLE
BUG: Migrations are not running

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2648]
**Describe the bug**
ON trying to run migrations to create the db structure nothing is happening:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/17fd5962-261f-4b58-aa84-553dfcaaf501)

**To Reproduce**
1. Drop schema
2. Create new schema
3. Go to command line and run `npm run migration:run` - nothing happens to the db beyond stating that all migrations have been run

**Expected behavior**
Migrations should run
Documentation if needed is updated.

**Comment by Comoque1** [comment]
The regression tests worked fine locally.
