### ISSUE TITLE
BUG: Error is thrown, when search by term that is contained by user

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2654]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/search?terms=dev&terms=water&terms=qa
2. Error is thrown: `"message":"Property "tagset" was not found in "Profile". Make sure your query is correct."`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5d50fe25-b508-4feb-ba5b-bf0cd6ed3021)

**Expected behavior**
Search returns correct results.

**Comment by alstojanovic** [comment]
@Comoque1 I cannot reproduce this anymore so I guess we fixed it at some point.

**Comment by Comoque1** [comment]
On ACC env, page crash, with specific [filter](https://acc.alkem.io/search?terms=23)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/19d683f3-27ad-43ea-8157-96b6fe1d2900)
