### ISSUE TITLE
BUG: unable to upload images of type webp

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2667]
**Describe the bug**
The image type webp is growing in usage, but it is not a valid type according to our visual definition.

**To Reproduce**
1. Go to any visual on edit location, and try to modify the image. The client does not allow webp to be selected.

**Expected behavior**
The client is able to upload visuals of type webp

A sample one is: https://www.gstatic.com/webp/gallery/1.webp

**Comment by Comoque1** [comment]
The issue is still reproducible on ACC env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/a3f1204d-252f-4d2e-a6f7-7e742d1d8575)
