### ISSUE TITLE
Callout groups

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#2676]
## Description
As a product lead I want to update and extend the callout types to provide more collaboration tools for the users and leads. 

## Acceptance criteria

- [ ] Callout entity extended with a "group" field that has is essentially a string identifier for grouping the Callouts
- [ ] callouts field on collaboration entity to allow requesting Callouts based on a particular group
- [ ] Tests added

**Comment by hero101** [comment]
What does " Updated to work with api as above" mean? I don't believe this is introducing any breaking changes to the client.
It would make more sense for this to be integrated end to end.

**Comment by hero101** [comment]
@valentinyanakiev, @me-andre I believe the group names (e.g. HOME_, COMMUNITY_) are too tightly coupling the frontend to the backend (just for display purposes) - a more generic name (e.g. GROUP_*) would decouple them, then the group can be used in the frontend completely independent

**Comment by me-andre** [comment]
I think the proposed approach somewhat violates Single Responsibility and MVC by mixing pure presentational attributes with the data structure.
Instead, I would propose each Collaboration having an instance of CalloutsLayout that would store the tree of how Callouts are positioned on the pages:
```
{
  "homeLeft": ["uuid-0", "uuid-1"],
  "homeRight": [...],
  ...
}
```
That would achieve the following:
1. Ordering isn't ambiguous anymore (now it's global but it must work on each page separately);
2. When the pages structure is changed, we don't touch Callouts in the migration (Single Responsibility).

**Comment by techsmyth** [comment]
@hero101 @me-andre good comments. One key think I think we should align on is that the data model should not have anything specific to the UI: there should be experimentation in how it is displayed / used. In that sense my original suggestion re having specific names for the groups does not make sense. But I do think groups themselves make sense. Note that I can easily see a situation whereby a callout is shown in more than one location - so we do need to support that- but that may cause issues with routing. 

Looking at the above I think that what we effectively need are tags, and we could see the groups as a sort of tagset. But it feels simpler to for now have groups and if we start having more tagsets in use for different purposes (e.g. alkemio client layout) then we can migrate to that. The client would then need to have some mapping, which could be hard coded in the client, t o state that "group1" tag goes to xxx position. 

Maybe easiest to chat through?
