### ISSUE TITLE
Callout type: collection of links, migration of recommendations

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2677]
## Description
As an Admin I want to highlight a collection of links in the Hub that is easily manageable, for example: recommendations, help documents, reports etc. 

## Acceptance criteria
- [x] Callout types enumeration updated to have additional entry: LINK_COLLECTION
- [x] Callout entity to expose the links via the contained profile entity

Migration
- [ ] Migration of recommendations to be a Callout of type LINK_COLLECTION and in the right group

Create /edit flows:
- [ ] Collection of links added to the create callout dialog
- [ ] Create + edit dialog for the collection of links callout
- [ ] Expand dialog for the collection of links

Admin
- [x] Context entity to no longer have Recommendations field (remove mutations associated etc)
- [ ] remove management of recommendations from Hub admin

Client: 
- [ ] Updated to work with api as above

## Additional Context
https://www.figma.com/file/zw3ymZPkFkVqtMsVLRuLRR/Structure-refresh-Q1?node-id=263%3A1428&t=pRarUMlgFIz1JKnT-1

**Comment by hero101** [comment]
Is the new Callout type called Reference or Link collection?

**Comment by techsmyth** [comment]
@hero101 Link Collection, people understand that more than Reference
