### ISSUE TITLE
Callout type: single whiteboard

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#2678]
## Description
As a lead I want to put up a single board where my community can brainstorm, for example a stakeholder map

## Acceptance criteria
- [x] New callout type WHITEBOARD (tbd what the name will be as the collection of whiteboards is now Canvas)
- [ ] This Callout type has a simple blank whiteboard by default

Create /edit flows:
- [ ] Whiteboard added to the create callout dialog
- [ ] Create + edit dialog for the whiteboard callout
- [ ] Expand dialog for the whiteboard

## Additional Context
https://www.figma.com/file/zw3ymZPkFkVqtMsVLRuLRR/Structure-refresh-Q1?node-id=263%3A1428&t=pRarUMlgFIz1JKnT-1

**Comment by valentinyanakiev** [comment]
@larssondenise the design has `Comments` on this type of `Callout`. `Canvas` doesn't have `Comments` at the moment, is adding `Comments` a requirement? Are `Comments` on the `Callout` or on the `Canvas` (both don't have `Comments` currently)? This needs clarification.

![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/cbbe7b52-01b7-42f8-b623-533e0a12236a)

**Comment by larssondenise** [comment]
@valentinyanakiev This is not something for this sprint! :)
