### ISSUE TITLE
Rename inheritable in authorization policy to cascade

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2688]
## Description

As a developer I want clear naming to make code easier to understand

## Acceptance criteria

- [ ] Inheritable concept in authorization policy renamed to cascade

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
Run some of the api tests and pass:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5b6d1369-0d3c-4766-932d-348ec5c98e6a)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/82d6f774-4659-4e7e-b4ba-81ecf0bad9d8)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c9833042-1ef9-4fd0-8e20-0052e032dcad)
