### ISSUE TITLE
Child activity visible in parent activity log

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#2703]
## Description

As a visitor of the Hub, I want to understand the activity which also means the activity in the underlying level. 

## Acceptance criteria

- [ ] Visualize Challenge activity in the Recent Contributions on the Hub dashboard
- [ ] Visualize Opportunity activity in the Recent Contributions on the Challenge dashboard

### API requirements
- the query `activityLogOnCollaboration` has an optional parameter to include activities from direct children
- the result must indicate that it is from a child entity

### Client-side requirements
- the client application is showing the child results
- the child results are indicated on the client as the title is truncated to X characters and "in \<Challenge icon\> \<Challenge title\>" is appended to the end

**Comment by larssondenise** [comment]
@SimoneZaza let's also look at the design for distinguishing the hub from the challenge activities in the section! Or did we have that in the design?

**Comment by SimoneZaza** [comment]
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/ccd4bf89-fd10-49af-985f-9fc8a57f621c)
The text is the same, but the headline ends with "in <Challenge/Opportunity icon> <Challenge/Opportunity title (truncated)>, and the image is different, but maybe for now that should stay the same.

**Comment by Comoque1** [comment]
Tested on DEV env.:

 - [x] Missing indication if the activity is from hub or challenge, respectively challenge / opportunity
 - [ ] Subscriptions are not triggered, when activity event comes from a child
 - [x] If possible, remove (More Contribution) on HUB level only
