### ISSUE TITLE
BUG: User non member of private space/challenge, doesn't get their results in search

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2711]
**Describe the bug**
Users are not able to search + find private communities

**To Reproduce**
1. Go to https://dev.alkem.io/search?terms=fixes - no results are returned, but hub and challenge must be displayed
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/520bcd93-cc9a-4bea-a99b-08fea729400c)

**Expected behavior**
Non registered user must see private spaces on search results, when he is not member of the community.

Note: challenges in private spaces should absolutely not be shown. 

Note: private challenges in public spaces maybe, but this may be hard to differentiate on (in the logic).

**Comment by techsmyth** [comment]
The space itself should be visible, but challenges absolutely not as that is content of the Space

**Comment by Comoque1** [comment]
The tests are updated, and the search works meaningful at the moment. 

Regarding these 2 point:
- [ ] Registered user, not private hub member
  - [ ] Note: challenges in private spaces should absolutely not be shown - OK
  - [ ] Note: private challenges in public spaces maybe, but this may be hard to differentiate on (in the logic). - not visible with the current implementation

- [ ] Not registered user, not private hub member
  - [ ] Note: challenges in private spaces should absolutely not be shown - OK
  - [ ] Note: private challenges in public spaces maybe, but this may be hard to differentiate on (in the logic). - not visible with the current implementation
 
The rest of the users who are journy, members / admins on different levels, can see private data as on the screenshot below:
(number == the nested entity, i.e.  1 == hub, 2 == hub and challenge, 3 == hub, challenge and opportunity)


Search Public Hub Private Challenge Data 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c30cd0f0-73bd-46f4-bcc7-32bee35db99b)

Search Private Hub Private Challenge Data
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/18f120d7-82b7-4381-8218-4f5173f42210)

@techsmyth, I am approving the PR as is, at the moment. If information above is correct, feel free to merge.
