### ISSUE TITLE
User preferences for notifications for Discussions

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2715]
## Description

As a user I want to be able to control the notifications I receive for discussions

## Acceptance criteria
- [ ] New group for Notifications related to Forum: NotificationForum
User Preferences updated to repurpose the two existing Discussion preferences to be the following Preferences:
- [ ] Receive a notification when a new Discussion is created in the Forum
- name: NotificationForumDiscussionCreated
- default: off. NOTE: this is important.
- group: NotificationForum
- [ ] Receive a notification when a new comment is added to a Discussion I created in the Forum
- name: NotificationForumDiscussionComment
- default: on
- group: NotificationForum
- [ ] Client updated to show the new NotificationGroup
- [ ] Migrate old preference definitions to updated values

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by alstojanovic** [comment]
@Neil on the client is this a separate section? Is there a special place where to put it or can it be added anywhere?
