### ISSUE TITLE
Innovation Spaces CRUD API

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#2729]
## Description

As an Alkemio User
I want to have my own branded space

## Acceptance criteria

- [ ] Innovation Spaces CRUD API
- [ ] API tests added

**Comment by techsmyth** [comment]
@valentinyanakiev please also move the innovation-space folder to be up under platform, it is not part of the core domain model.

**Comment by techsmyth** [comment]
@valentinyanakiev we also need to revisit that chat re logo in Branding entity, in light of the first version of the innovation space where it will not be used + how it relates to storage spaces. To chat through tomorrow.
