### ISSUE TITLE
Innovation Hub domain model + api

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2752]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria

- [x] InnovationHubs are retrieved via Platform entity i.e. platform.innovationHubs
- [x] InnovationHub entity fields:
- subdomain: to be unique across all InnovationHubs, with validation. Regex based.
- hubVisibilityFilter: a type of visibility (valid on visibility hub type)
- hubsListFilter: list of hub IDs. min length of 1
- profile usage: default tagset, banner visual

- [x] authorization: cascade from platform. Implies: Read for all users. Mutations: UPDATE
- [ ] CRUD api on InnovationHub entity
- [x] Allow retrieving of information about an InnovatinoHub via platform.innovationHub(subdomain: string) field

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by hero101** [comment]
@valentinyanakiev I suggest splitting this and the other related story into testable chunks - the model and the two bootstrapped e2e examples, and another for the CRUD.

**Comment by hero101** [comment]
@techsmyth I would suggest the `hubVisibilityFilter` not have a default and be nullable because it's either the `hubVisibilityFilter` or the `hubsListFilter` defined. The default would suggest that it's also an active filter.

**Comment by techsmyth** [comment]
@hero101 agreed - makes sense...
