### ISSUE TITLE
Migration of existing ipfs usage to documents access

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2756]
## Description

As a user I want that all file / image access goes through the Alkemio api

## Acceptance criteria

- [ ] Migrate all images used in visuals that are accessed by direct api access to be Documents + use rest api access
- [ ] Migrate all attachment used in visuals that are accessed by direct api access to be Documents + use rest api access

tbd
- links in markdown?

## Additional Context

Migrate URI from Visual and Reference where the format is https://*.alkem.io/ipfs/{CID}

The regex should be `^https?:\/\/([a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*)\/ipfs\/(Qm[a-zA-Z0-9]{44})$`

The following 2 queries give the only MD fields having ipfs links:

```sql
SELECT * FROM alkemio.profile where description like '%alkem.io/ipfs%';
SELECT * FROM alkemio.activity where description like '%alkem.io/ipfs%';
```

**Comment by valentinyanakiev** [comment]
Raising estimate to `20` as I have not created separate bugs for fixing all the bugs + edge cases reported + fixed
