### ISSUE TITLE
Invitation entity 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2836]
## Description

As an admin I want to be able to invite users to a space
As a user I want to see all my invitations in one place

## Acceptance criteria

- [ ] Invitation entity added to domain model similar to Application entity, with lifecycle etc
- [ ] rolesUser query to also show open invitation as well as open applications

**Comment by alstojanovic** [comment]
@techsmyth do we need to send some message with the invitation or are we just going to have a generic invitation?

**Comment by techsmyth** [comment]
For now just the invitation, no messageSent from my iPhoneOn 30 May 2023, at 12:47, Aleksandar Stojanovic ***@***.***> wrote:﻿
@techsmyth do we need to send some message with the invitation or are we just going to have a generic invitation?
