### ISSUE TITLE
BUG: challenges metric is returning wrong number

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2863]
**Describe the bug**
Look at the offshore-wind-ie space, the challenges metric is returning the value 4 when there is only one challenge:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/a6b85574-e70d-4e48-95f0-53cb927646b8)

**To Reproduce**
1. Go to graphql playground + execute query shown in the image

**Expected behavior**
Challenges metric to return the number of challenges

**Comment by techsmyth** [comment]
@valentinyanakiev this looks like there may be a data issue, as the code itself that is being executed is fine + is working locally:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/d40a4e00-2a46-461a-a6d5-3652eea78337)

Can you try this query against the production data + share what is returned?

**Comment by hero101** [comment]
There are 4 challenges linked to that Space via the `spaceId`.
The only things I see are that `parentSpaceId` is `null` for 3 out of 4 and the nameIDs are linked to the same title meaning that it could be 3 unsuccessful creation attempts. They are all created seconds apart on 30th of May.

**Comment by techsmyth** [comment]
@hero101 ah - so we have some data clean up to do?

**Comment by hero101** [comment]
I don't know what's wrong, so I can't suggest a solution - just stating the obvious for now.
