### ISSUE TITLE
BUG: innovation_hub + invitation entity uses varchar

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2874]
**Describe the bug**
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/6fab0fab-bc5b-49d8-9494-84c59bc700b0)

**Expected behavior**
All UUIDs should be char(36) types, so the id field, authorizationId and profileId all need updating

Same issue with Invitation entity:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/cf7668a3-05aa-4dbe-8077-9d9afb2ba1a2)

**Comment by valentinyanakiev** [comment]
@Comoque1 actually I am going to close this, it's more of a dev issue and I have tested it myself, no need to re-test it.
