### ISSUE TITLE
space settings entity to replace usage of preferences

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2881]
## Description

As a client developer I want the core logic enforced on the server

## Acceptance criteria

- [ ] new SpaceSettings entity to hold the following types of settings: privacy, membership, collaboration
- [ ] Authorization updated to use new approach
- [ ] Migration to move existing preferences to be reflected by the above fields
- [ ] client updated to use simpler logic

**Comment by Comoque1** [comment]
@ccanos challenge and opportunity creation redirects user to 404 page:
1. Create space
2. Create challenge - successfully created, but user is redirected to 404
3. <img width="1366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzQ2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9cba256aaf3a0dc1df20a403b59e305c943ed26/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Update space defaults throws an error:
<img width="1480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2M2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbc7366055e6cd51a58ed3b7b4fb7d271a2f699e/image.png" alt="image.png" />
