### ISSUE TITLE
Spike: hocuspocus via api

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2882]
## Description
As a developer I want to be able to evaluate multi-user collaboration without having to fire up a local hocus pocus

## Acceptance criteria

- [x] Service added to server api
- [ ] Connected to mariadb as backend
- [x] Use Alkemio authorization framework for controlling access

Spike: limit to one day and a half?

## Additional Context
longer term goal is to have this in a separate service

**Comment by hero101** [comment]
[Real-time collaboration setup with Hocuspocus in HackMD](https://hackmd.io/KigrFHfLQS-CVdzerfULfw)
