### ISSUE TITLE
BUG: Invitation, can be triggered, when there is application already

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2893]
**Describe the bug**

**To Reproduce**
1. Go to go to local env
2. Create a hub
3. Create application with user to the hub
4. Using i.e. GA, create invitation to the user, who applied to the hub - application is created successfully
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/3c532e8b-24e3-4c05-a3a3-e64d60a2d958)

**Expected behavior**
Inviting user, that already has an application, should throw an error.

**Comment by techsmyth** [comment]
@SimoneZaza @larssondenise this needs a bit of discussin: should a user be invitable if there is already an application pending?

**Comment by Comoque1** [comment]
The fix works, but there is change in the behavior, when user has invitation and tries to apply - now error is thrown, previously, he was able.

@techsmyth, if you accept the above behavior, will approve / merge the PR
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/bb045be1-d483-44ce-9134-978d900c80d8)

**Comment by techsmyth** [comment]
@Comoque1 yes please merge this one. If we need to have better feedback to the user that is a separate one. Key with this issue is that the underlying logic is robust.
