### ISSUE TITLE
Community roles for spaces expanded to have admin, host + mutations cleaned up

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2896]
## Description

As a space lead, I want to be able to set the visible lead or separate from the org that is formally hosting the space

## Acceptance criteria

- [ ] CommunityPolicy extended to have the following roles: Admin, Host
- [ ] Remove dedicated mutations per role and have all go through the generic assign/remove CommunityRole mutations
- [ ] Test suites updated

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by valentinyanakiev** [comment]
I have tested this manually through the client and seems to be working fine. Also tested creating Challenge, Space etc.
Test-suites need updating big time.
