### ISSUE TITLE
BUG: Forum discussions fail to load

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2907]
**Describe the bug**

**To Reproduce**
1. Go to https://acc.alkem.io/forum - tdiscussions fail to load: "Enum "AuthorizationPrivilege" cannot represent value: "create-comment""
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/bd9d204c-e462-4428-a2bf-5bd708498cdb)

**Expected behavior**
Discussions with its comments, load successfully.

**Comment by valentinyanakiev** [comment]
Requires a migration, `create-comment` is `create-message` now, it seems it wasn't added to the migration

**Comment by techsmyth** [comment]
Auth reset? Privileges should not be in the db I think
