### ISSUE TITLE
Preference to allow a user not to receive email notifications for invitations

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2933]
## Description

As a user I want to be able to disable email notifications for invitations

## Acceptance criteria

- [ ] Additional preference to allow users to not receive emails when invited. Default to true. Existing users receive it as true. 
- [ ] Preference used by notification service to determine if the user receives the email or not.

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by alstojanovic** [comment]
This was added some time ago. @Comoque1 please check NOTIFICATION_COMMUNITY_INVITATION_USER preference.
