### ISSUE TITLE
Refresh default callouts to include emoticons / highlighting

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2939]
## Description

As a user I want an exciting displayed page

## Acceptance criteria

- [ ] Update content of default callouts to include emoticons / highlight text

## Additional Context
Look at https://alkem.io/energy-alliance/dashboard

**Comment by Comoque1** [comment]
When creating new space, collection callout is not created, as stated in second point of AC:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9a76a5e1-cdf1-411e-91e6-0f7dd1c9f8c8)

**Comment by techsmyth** [comment]
@Comoque1 thanks Evgeni - good catch. I have split that out into a separate issue that includes a wider review of the default callouts which will need to discuss with Simone / Denise.
