### ISSUE TITLE
Handling of deleted threads [PLACEHOLDER]

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Server#2955]
This is a placeholder issue to have a conversation about how to handle deleted message threads.

From Teams Development channel:
> There is an outstanding issue with the replies when a thread message (the first message in a thread) is deleted. The replies are still in the room but are not displayed and the counter in the client is showing all the messages in the room - displayed or not. I believe we should handle this by displaying a deleted message placeholder to preserve the context of the reply messages. This may require the product's standpoint, but usually, that is the way most messaging clients are handling that situation.

**Comment by techsmyth** [comment]
replaced by https://github.com/alkem-io/client-web/issues/4556
