### ISSUE TITLE
BUG: auth policy on space storage missing FILE_UPLOAD, has other privileges

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2964]
**Describe the bug**
The set of privileges on storage on space is wrong:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/e3049ee5-d416-43d2-98b0-168e9a4445e4)

**To Reproduce**

**Expected behavior**
No  community priviileges
File upload privilege granted

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by techsmyth** [comment]
@Comoque1 @hero101 this is a nasty one, there was a bug that resulted in using the same authorization policy entity in both community + storage. ![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/54d94aeb-9547-4276-a656-37752d35f2bb)

If an authorization reset has been done in the last couple of days on develop then that db is affected. A migration will not easily fix it, so suggest to restore develop back to state before the following PR was merged into develop: https://github.com/alkem-io/server/pull/2956

**Comment by valentinyanakiev** [comment]
Verified on dev, works fine now
