### ISSUE TITLE
Full Invitation/Application details available through rolesUser

### ISSUE THREAD

**Issue by me-andre** [cherrytwist/Server#2985]
## Description

As a developer, I want to be able to acquire the pending invitations of a user with their metadata easily so that I don't make excessive roundtrips to the server.

## Acceptance criteria

- [ ] extend userRoles query to provide sufficient data for the user invitations so no additional queries to the invitations are required

## Additional Context

To efficiently query the data for Pending Memberships I'm using rolesUser top-level field. However, invitations and applications don't include the full entity (e.g. no welcomeMessage on Invitations) and have journey ids instead of journeys (can't query journey fields directly).
While the latter can be worked around by just querying the needed journeys by ids, the former can't be solved on the client because we can't query an invitation or an application by id (to get the missing fields).
The other option would be to allow a user to query his own invitations and applications on community, but that seems to be a harder one to implement.

**Comment by techsmyth** [comment]
@me-andre agreed - this api does need a refresh to make the full entities available, otherwise it is way too heavy / much work for the client
