### ISSUE TITLE
platform related queries as fields under platform

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2991]
## Description

As a developer I want a clean api

## Acceptance criteria

- [ ] Platform related queries accessed as fields under the platform entity. To cover: authorization, metadata, configuration
- [ ] Remove existing top level platform related queries: authorization, metadata, configuration
- [ ] Client updated to retrieve data from fields
- [ ] client-lib updated
- [ ] populator + notifications updated to use new client-lib

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
The queries `full-config` and `template-config` are failing
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/9a3d2a60-bcdf-4699-be79-e112d223886a)
