### ISSUE TITLE
Extend set of default callouts for new journeys

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3026]
## Description
As a user I want an exciting displayed page

## Acceptance criteria
- [ ] Full refresh of default callouts on new journeys

https://app.excalidraw.com/s/4BCnkZqaP0t/9b9d4DpZEvG

**Below you'll find  a list of default templates, listed per Journey type/tab. In order to get the most fluent copy-paste experience, labels such as title are not included, but the order is as follows:
    - title
    - description
    - template (when applicable)**

## Space
- [ ] Dashboard
    - [x] LEFT Post: 
        - Chat
        - [empty description]
    - [x] LEFT Collection of links:
        - Getting Started
        - ⬇️ Here are some quick links to help you get started
    - [ ] RIGHT Whiteboard *further refine the vision of space > leave this one as there are no whiteboard templates possible*
    - [ ] RIGHT Post *lightweight question to spark conversation, > leave for now*

- [ ] Community
    - [x] LEFT Post *Ideas to grow this community, > is a post instead of whiteboard as we do not have templates*
    - [ ] RIGHT Call for whiteboards *Introduce yourself > leave for now as we do not have templates*
    - [x] RIGHT Whiteboard *Understanding/Visualizing the existing + potential community > template not possible so is an empty whiteboard*
- [] Challenges
    - [x] LEFT Post:
        - 🚩What Challenges do you care about?
        - [empty description]
    - [x] RIGHT Call for posts:
        - Challenge Proposals
        - What are the 🚩Challenges that you think we should be working on? Please add them below and use the template provided.
        -   **Title**

            **Description**

            **Who to involve**

            **Why is this important**

- [ ] Knowledge Base
    - [x] RIGHT Collection of Links
        - Interesting documents
        - [no description]
    - [x] RIGHT Collection of Posts
        - ❓ FAQ
        - Below you'll find various questions and answers on this topic. Please feel invited to join in and share your answers as well!
    - [ ] RIGHT Post *left out as it is too much*
        - Must reads 💛
        - What books, articles, etc., should we definitely read? 
    - [x] RIGHT Collection of Posts *extended with articles, news, etc.*
        - ✨ Inspiring examples ✨
        - What examples are you working on or do you know about? 
        -   **Title**

            **Description**

            **Find out more here:**
## Challenge
- [ ] Dashboard
    - [x] LEFT Post: 
        - Chat
        - [empty description]
    - [x] LEFT Collection of links:
        - Getting Started
        - ⬇️ Here are some quick links to help you get started
    - [ ] RIGHT Whiteboard *further refine the vision of Challenge, > no whiteboard templates so left out for now*
    - [x] RIGHT Collection of posts 
        - 👥 This is us!
        - Here you'll find the profiles of all contributors to this Challenge. Are you joining us? 👋Nice to meet you! Please also provide your details below.
        -   Hi! I am...

            In daily life I...

            And I also like to...

            You can contact me for anything related to...

            My wish for this Challenge is...

            *And of course feel invited to insert a nice picture!*
- [ ] Contribute
    - [x] LEFT Collection of Links
        - Interesting documents
        - [no description]
    - [ ] LEFT Collection of Whiteboards *My ecosystem, template needed > We leave this one out because we can't use templates*
    - [x] LEFT Post
        - Must reads 💛
        - What books, articles, etc., should we definitely read? 
- [ ] Opportunities
    - [x] LEFT Post:
        - 💡 What Opportunities do you suggest?
        - [empty description]
    - [x] RIGHT Call for posts:
        - Opportunity Proposals
        - What are the 💡 Opportunities that you think we should be working on? Please add them below and use the template provided.
        -   💡 **Title**

            💬 **Description**

            🗣️ **Who to involve**

            🌟 **Why this has great potential**

## Opportunity
- [ ] Dashboard
    - [x] LEFT Post: 
        - Chat
        - [empty description]
    - [x] LEFT Collection of links:
        - Getting Started
        - ⬇️ Here are some quick links to help you get started
    - [x] RIGHT Collection of posts 
        - 💪 Jobs to be done...
        - [empty description]
        - Task:

          Related to:

          People involved:
            
          Deadline:

    - [x] RIGHT Post
        - 👋 Hi, this is us!
        - Please introduce yourself to each other, sharing a bit about your background, goal, and (envisioned) role in this project 
- [ ] Contribute
    - [x] LEFT Collection of Links
        - Important links & documents
        - [no description]
    - [x] LEFT Post
        - Must reads 💛
        - What books, articles, etc., should we definitely read? 
    - [x] RIGHT Whiteboard *What is needed for this solution, > empty whiteboard for now*

# Example code (is this complete?)
{
    type: CalloutType.POST,
    profile: {
      displayName: 'Why do you care about this Challenge?',
      description:
        '👋 Please share a few words about yourself to help the community get to know each other. For example, why is this Challenge important to you, or relevant thoughts, experience or expertise.',
      tagsets: [
        {
          name: TagsetReservedName.DISPLAY_LOCATION_CHALLENGE,
          tags: [ChallengeDisplayLocation.HOME_LEFT],
        },
      ],
    },
    nameID: 'challenge-welcome',
    state: CalloutState.OPEN,
    sortOrder: 1,
  },

**Comment by Comoque1** [comment]
## Space
- [ ] Dashboard
    - [x] LEFT Post:  - **OK**
        - Chat
        - [empty description]
    - [ ] LEFT Collection of links: - **missing (there is second post callout (Do you have any questions or feedback))**
        - Getting Started
        - ⬇️ Here are some quick links to help you get started
        ![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1591a3e1-810b-463c-890e-0cda3334862b)
    - [x] RIGHT Whiteboard *further refine the vision of space, still to be worked out*
    - [ ] RIGHT Post *lightweight question to spark conversation, still to be worked out* - **missing**

- [ ] Community
    - [ ] LEFT Whiteboard *Ideas to grow this community, still to be worked out, template needed* - **missing, but there is the "Welcome to community" callout**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/098779f7-77c5-44fd-a5e2-d591c8fccb52)
    - [ ] RIGHT Call for whiteboards *Introduce yourself, still to be worked out, template needed*
    - [ ] RIGHT Whiteboard *Understanding/Visualizing the existing + potential community, still to be worked out, template needed* - **missing**
- [ ] Challenges
    - [x] LEFT Post:
        - 🚩What Challenges do you care about?
        - [empty description]
    - [x] RIGHT Call for posts:
        - Challenge Proposals
        - What are the 🚩Challenges that you think we should be working on? Please add them below and use the template provided.
        -   **Title**

            **Description**

            **Who to involve**

            **Why is this important**

- [ ] Knowledge Base
    - [x] RIGHT Collection of Links
        - Interesting documents
        - [no description]
    - [x] RIGHT Collection of Posts
        - ❓ FAQ
        - Below you'll find various questions and answers on this topic. Please feel invited to join in and share your answers as well!
    - [x] RIGHT Post
        - Must reads 💛
        - What books, articles, etc., should we definitely read? 
    - [ ] RIGHT Collection of Posts - **missing**
        - ✨ Inspiring examples ✨
        - What examples are you working on or do you know about? 
        -   **Title**

            **Description**

            **Find out more here:**
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/d02f70ca-8165-4708-8d0a-c21b6eebc534)

## Challenge
- [ ] Dashboard
    - [x] LEFT Post: 
        - Chat
        - [empty description]
    - [ ] LEFT Collection of links: - **is this the recommended by the host (if so, it is still positioned, where it was still )**
        - Getting Started
        - ⬇️ Here are some quick links to help you get started
        ![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c754b5b4-1bb6-40ac-8f43-f8321d8627b7)
    - [ ] RIGHT Whiteboard *further refine the vision of Challenge, still to be worked out* - **missing**
    - [ ] RIGHT Collection of posts  - **missing**
        - 👥 This is us!
        - Here you'll find the profiles of all contributors to this Challenge. Are you joining us? 👋Nice to meet you! Please also provide your details below.
        -   Hi! I am...

            In daily life I...

            And I also like to...

            You can contact me for anything related to...

            My wish for this Challenge is...

            *And of course feel invited to insert a nice picture!*
- [ ] Contribute
    - [x] LEFT Collection of Links
        - Interesting documents
        - [no description]
    - [ ] LEFT COllection of Whiteboards *My ecosystem, template needed and still to be worked out further* - **there is no collection of whiteboards**
    - [x] LEFT Post
        - Must reads 💛
        - What books, articles, etc., should we definitely read? 
        ![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/49a8003a-2704-48b0-a359-839332446978)
- [ ] Opportunities
    - [x] LEFT Post:
        - 💡 What Opportunities do you suggest?
        - [empty description]
    - [x] RIGHT Call for posts:
        - Opportunity Proposals
        - What are the 💡 Opportunities that you think we should be working on? Please add them below and use the template provided.
        -   💡 **Title**

            💬 **Description**

            🗣️ **Who to involve**

            🌟 **Why this has great potential**

## Opportunity
- [ ] Dashboard
    - [x] LEFT Post: 
        - Chat
        - [empty description]
    - [ ] LEFT Collection of links: - **this is positioned where it was - not on the left**
        - Getting Started
        - ⬇️ Here are some quick links to help you get started
    - [ ] RIGHT Collection of posts  - **there is post callout (is this meant under collection?)**
        - 💪 Jobs to be done...
        - [empty description]
        - Task:

          Related to:

          People involved:
            
          Deadline:

    - [x] RIGHT Post
        - 👋 Hi, this is us!
        - Please introduce yourself to each other, sharing a bit about your background, goal, and (envisioned) role in this project 
        ![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/b0b4e8a4-8a8a-4b74-ac40-65a18bdd0389)
- [x] Contribute
    - [x] LEFT Collection of Links
        - Important links & documents
        - [no description]
    - [x] LEFT Post 
        - Must reads 💛
        - What books, articles, etc., should we definitely read? 
    - [x] LEFT Whiteboard *What is needed for this solution, template needed and still to be worked out further*
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/08263094-a902-4338-bc9c-9f2ee2a8f029)

**Comment by Comoque1** [comment]
The display of new default callouts where reviewed on localhost by me and @larssondenise on local environment. 
The code changes where reviewed by @techsmyth.
