### ISSUE TITLE
BUG: after deleting a message, the replies to it are still returned in the api

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3074]
**Describe the bug**
When a message is deleted that has replies, the replies are still returned as messages in the room

**To Reproduce**
1. create a message in a discussion
2. reply to the message
3. delete the root message
query the set of messages in the room, the reply is still visible

**Expected behavior**
Reply messages should be deleted when the parent message is deleted.

**Comment by alstojanovic** [comment]
@techsmyth I think it's hard to not return these messages. When we request messages from a Room, we return the whole timeline of matrix messages. We can maybe filter the timeline but it could be expensive. I think we should allow a [deleted message] placeholder on the client and then to have the replies underneath.
If we filter out the replies, from a UX standpoint it would be the same as deleting them and it would mean that the parent message owner would be the thread owner and could "remove" all the replies if he doesn't like something. We are an open platform and we shouldn't allow any user to "hide" other user's messages in my opinion.

**Comment by techsmyth** [comment]
replaced by https://github.com/alkem-io/client-web/issues/4556
