### ISSUE TITLE
Design for templating the innovation flows with callouts

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3082]
## Description

As a user I want to be able to access fully populated innovation flow templates

## Acceptance criteria

- [ ] Design for how we will allow for associating callouts with innovation flows
- [ ] Design for how to associate whiteboard template with callout template

## Additional Context
https://app.excalidraw.com/s/4BCnkZqaP0t/9kSIOONYDrL

First design pass:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/51278640-70dd-49dc-8209-26fcb19e917a)

**Comment by techsmyth** [comment]
@valentinyanakiev on further consideration I think we can go with a much simpler design 

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/3a249315-9a5c-43fa-92e7-995a0bbe2d2b)

this has the advantage that it is purely additive, and we can also do it incrementally by first adding in the CalloutTemplate entity + add it to the TemplatesSet. Main downside is that there is no option to share e.g. a whiteboard across multiple templates - but we can manage that by having some user support e.g. "move whiteboard to be a standalone template" kind of functionality.

**Comment by valentinyanakiev** [comment]
@techsmyth that's OK and easy to implement. Should be fairly easily doable.

**Comment by valentinyanakiev** [comment]
Closing this, we have an initial design discussed & agreed.
