### ISSUE TITLE
BUG: rolesUser query doesn't return applications/invitations data

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3097]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/graphql
2. Perform the following query:
```
query rolesUser($input: RolesUserInput!) {
  rolesUser(rolesData: $input) {
    id
    organizations{
      id
    }
    spaces{
      id
    }
    spaces{nameID roles }
    applications{id}
    
    invitations{id}
    }
}
```

```
{
  "input": {
    "userID": "1fd4168b-a98c-457c-b6d3-bbebf7687c30"
  }
}
```
3. The results don't return applications / invitations for the user,but it has (when queried from `me` query)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1f988c96-b940-4419-a742-66e166a09913)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/01fc21bf-814a-4516-9603-7eabfb89c420)

**Expected behavior**
`rolesUser` returns invitations / applications, when queried from global admin.

**Additional context**
Raising this bug with respect to second comment of `Updated me query + applications / invitations via field resolvers on rolesUser #3088` second comment

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/07978d29-1189-49df-97c4-5613576ef05a)

**Comment by valentinyanakiev** [comment]
@techsmyth is the current behaviour 100% correct? Wouldn't a `PLATFORM_ADMIN` be able to other somebody else's applications / invitations? For normal users it's a definite no-go, but for platform level admins?

**Comment by techsmyth** [comment]
@valentinyanakiev indeed a platform admin should (must) be able to see the inviations / applications for troubleshooting + support
