### ISSUE TITLE
BUG: Exception error code not logged

### ISSUE THREAD

**Issue by senna-alkemio** [cherrytwist/Server#3106]
**Describe the bug**
In Alkemio-server the field err.code is not tracked, so you are not able to breakdown the errors by type

**To Reproduce**

1. Go to Discover
2. Click on alkemio-server => err.code

**Expected behavior**
Expected that the err.code is tracked so you can see all different types of errors

**Screenshots**
![image.png](https://images.zenhubusercontent.com/63e0bdb20b31c1867d73d0e4/230b484a-2a11-488d-ab7f-de36b645d14f)

**Additional context**

**Comment by hero101** [comment]
The error code of the exceptions needs to be logged (reported) by `GraphqlExceptionFilter`.

**Comment by hero101** [comment]
The code, ingestion, and data have been verified.
