### ISSUE TITLE
BUG: When there is pending invitation and user is removed, space preference cannot be updated

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3111]
**Describe the bug**

**To Reproduce**
1. Go to ACC
2. Create new space
3. Invite internal user
4. Remove the user
5. Try to change the space preferences - error is thrown: ` "message": "Unable to find user with given ID: 0b480dbe-4aa4-4407-b762-3f9461e2cbd8",`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7248fb6d-bc1a-4909-b67a-b94c29cd6400)

**Expected behavior**
When user is removed, there are no side effects for community from which has received an invitation.

**Comment by alstojanovic** [comment]
When a preference gets updated we trigger a policy reset on Space and thus it gets propagated to sub entities. It triggers a policy reset for the invitation and then want's to trigger policy reset for the deleted User who was invited. There are probably a number of solutions, one is to remove invitation to users when the user is deleted (but we may want to keep that data). Another option is to maybe label invitations that are expired or not valid anymore and then skip the authorization propagation to those users. 
@techsmyth what is your opinion?

**Comment by techsmyth** [comment]
@alstojanovic we can "hide" the error by being smarter in the invitation authorization policy, but I think the right thing would be that if a user is deleted then we also should delete any invitation entries that are associated with that user - agreed? Same would apply for applications. So I suggest we instead extend the deleteUser method in the userService to also remove any invitations / applications that are for the user being deleted. Agreed?

**Comment by alstojanovic** [comment]
Agreed, I also think that is the most correct way but we weren't sure if we would want to keep the invitations data for some reason.

**Comment by techsmyth** [comment]
For now I think we can best leave it that if a user is deleted that any invitations / applications related to them are also deleted - so please go ahead with the deleting of them. Note: only invitations **for** the user should be deleted, and invitations created by a user should remain.
