### ISSUE TITLE
Create snapshot of synapse db from local environmen

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3125]
## Description

As a QA, I want to be able to create / restore synapse db snapshot from local env, so that everyone can use efficiently Alkemio DB backups.

## Acceptance criteria

- [ ] Create snapshot of synapse db
- [ ] Restore snapshot of synapse db

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by hero101** [comment]
Is this tagged with the correct epic and is this an initiative?
