### ISSUE TITLE
Clean up space field resolvers api

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3130]
## Description

As a developer I want clean code

## Acceptance criteria

- [ ]  Remove the ID parameter from the community field resolver
- [ ]  Remove the opportunity field resolver (single opportunity)

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by hero101** [comment]
This issue is blocked by  [Look up opportunities / challenges via UUIDs and via lookups #4537](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/4537), which is not in Sprint 71
