### ISSUE TITLE
BUG: avatar url has hub in it

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3135]
**Describe the bug**
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/c7897593-7b75-4c91-9aa6-6cce3a56db07)

**To Reproduce**
1. Go to https://alkem.io/challengecentric/challenges/enabling/opportunities/journeystructure-6338/collaboration/considerationsfort-5587/posts/scaling-1097/dashboard
2. Look at the contents of the returned query for opportunityPost and in particular the URL for the avatar of users

**Expected behavior**
Avatar URLs should not have hub in them

Note: this is likely a data issue in that we have some old ways of referring to user profiles? 
Note also that in the same thread that Simone's avatar URL is fine

Question is how many users have this URL set wrong?

**Comment by hero101** [comment]
471 visuals on production start with `https://hub.`. I have not found any references like that.
The records can easily be updated with a single statement.

**Comment by hero101** [comment]
Visuals uri update with the following script

```sql
UPDATE alkemio.visual
SET uri = REPLACE(uri, 'https://hub.alkem.io', 'https://alkem.io')
WHERE uri LIKE 'https://hub.alkem.io/%';
```

**Comment by hero101** [comment]
Visuals uri update with the following script

```sql
UPDATE alkemio.visual
SET uri = REPLACE(uri, 'https://hub.alkem.io', 'https://alkem.io')
WHERE uri LIKE 'https://hub.alkem.io/%';
```

**Comment by techsmyth** [comment]
@hero101 great - has this been run on production then?

**Comment by hero101** [comment]
@techsmyth Yes, it has been applied.

**Comment by techsmyth** [comment]
Super, thanks...
