### ISSUE TITLE
Contribution entity

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3161]
## Description

As a developer I want a clean code base / api
As a user I want flexibility in callouts

## Acceptance criteria
- [ ] Add the Contribution entity to the domain, derived from AuthorizableEntity, with the following fields:
- createdBy
- whiteboard
- post
- reference
- [ ] Migration to move existing callout responses to be Contribution entities 
a) CalloutType.CollectionOfPost => Contributions each with a post built from Callout.posts
b) CalloutType.CollectionOfLinks ==> Contributions each with a Link, built from Callout.profile.references. Note: the existing references should be moved, not copied, so that the profile will not have any refrerences afterwards
c) CalloutType.Whiteboard ==> No contributions
d) CalloutType.CollectionOfWhiteboards ==> Contribution each with a Whiteboard, built from Callout.whiteboards
e) CalloutType.Post ==> No contributions

- [ ] Mutations to be updated to reflect the above
- [ ] Client to be updated to query / send data as per above updated entity model

Note:
- leave comments on Callout for now. 
- leave CallloutType as is for now

...

## Additional Context
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMThGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ca53022ada2f8a52aace28b0fd6a3fb5e87488a/image.png)

Note: image above needs updating to reflect latest field names / design choices

**Comment by alstojanovic** [comment]
@techsmyth can this be taken or are you working on it?

**Comment by techsmyth** [comment]
@alstojanovic I had started it but better if you pick it up. Suggest we have a call before the daily tomorrow so I can talk it through with you?

**Comment by alstojanovic** [comment]
Sure let's talk before the daily.

**Comment by techsmyth** [comment]
Moved estimate to 8 as part of the scope was split out

**Comment by alstojanovic** [comment]
Do we still leave createdBy on Post and Whiteboard entities?
