### ISSUE TITLE
Addition of WhiteboardRT

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3170]
## Description

As a user I want to have the ability to work with whiteboards in multi user mode
As a dev lead I do not want existing functionality touched

## Acceptance criteria

- [ ] New whiteboard entity: WhiteboardRT, similar to Whiteboard but without checkout + not encrypted
- [ ] New callout type WhiteboardRT that holds a single whiteboard
- [ ] Callout to be extended to be able to hold a single WhiteboardRT
- [ ] Mutations etc for updating the profile / authorization

Later: 
- authorization to control access to using callouts of this type

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by hero101** [comment]
I don't expect this to be covered by API tests or additional testing efforts.
We are in an exploratory phase for now.
