### ISSUE TITLE
BUG: default callouts on new db are failling

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3172]
**Describe the bug**
When creating a new db, and then starting the server the callouts are created as part of the bootstrap process - meaning there is no user associated with the callouts.

The client is then failing when trying to read these callouts:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1JRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c9bf9710ddf90be9bdc32efbb867582c7f7f8116/image.png)

**To Reproduce**
1. remove the db
2. create a new db, run migrations
3. start the server
4. navigate to the space, errors are thrown as shown above

**Expected behavior**
The callouts should load without error, even when created via bootstrap process with no user

**Comment by Comoque1** [comment]
Tested OK locally.
