### ISSUE TITLE
Visual type for full page banner, as used in custom home page

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3194]
## Description

As a custom home page admin I want to be able to use full page width banners

## Acceptance criteria

- [ ] new Visual type: BANNER_WIDE, which has the following properties:
- aspectRatio: 10
- minHeight: 64,
- maxHeight: 256,
- aspectRatio
- minWidth: 640 (banner has 384, so divided by 6 & multiplied by 10),
- maxWidth: 2560 (banner has 1536 ...)
- [ ] Migration to assign this type to all innovationHub profile visuals
- [ ] New InnovationHub entities to pick up the new banner type
- [ ] Rename bannerNarrow to card

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
When I try to create new InnovationHub, the request fails
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbStyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cbc2d5aa8bac79a198617fb9d266be11443a47b1/image.png)

**Comment by Comoque1** [comment]
Raised a bug and closing this issue: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/4756
