### ISSUE TITLE
BUG: GLOBAL_COMMUNITY_ADMIN, doesn't have rights to send invitation to existing user

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3208]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/admin/spaces/doc-hub/community
2. Authenticate with GLOBAL_COMMUNITY_ADMIN 
3. Send invitation to existing user - authorization error is thrown: ` message: "Authorization: unable to grant 'community-invite' privilege: create invitation community: 6ef722b8-c860-4629-a5e9-b34015fb41ce user: 67cf5f33-1823-4faf-9a22-b199da094a39"`

**Expected behavior**
GLOBAL_COMMUNITY_ADMIN can send invitations to internal users even if he is not a community member

**Comment by techsmyth** [comment]
It should not
