### ISSUE TITLE
spaces paginated query

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3222]
## Description

As a user I want to have a home page that returns quickly 
As an admin I want to have a platform that scales well

## Acceptance criteria

- [ ] Add the ability to query spaces in a paginated way, via a new spacesPaginated
- [ ] Use the paginated spaces query on the home page on the client-web so that not all spaces are loaded. Load spaces with 10 per time. 

## Additional Context
Currently we are loading 80+ spaces with all information every time the user goes to the home page. This does not scale.

**Comment by alstojanovic** [comment]
@techsmyth On the client, do we add a 'show more' button to load the next 10 hubs or do we call the spacesPaginated until we get to the "last page"?

**Comment by techsmyth** [comment]
I would just load more as the user scrolls down, like what is done for users on the contributors page

**Comment by Comoque1** [comment]
UserSpaces request is triggered 4 times and always request all spaces.
Is this expected?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmpvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ac4e9ddbe12f43fcfd0397606557bcebf9f0afe/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnJvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f83a255473206336399a3bb50e200b87e00e3f7e/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnZvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--61ef3687ac1260e6e9e91eff842b81e2a3409806/image.png)

**Comment by Comoque1** [comment]
Raised a [bug](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/4853) regarding the above issue and closing this one.
