### ISSUE TITLE
Architecture + path forward for whiteboardRT in production

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3223]
## Description

As a an architect I want to ensure that production whiteboard RT are fit for purpose

## Acceptance criteria

- [ ] Design review covering the points in the epic
- [ ] Discussion / decisions on key findings
- [ ] ...

Spike: 1 day overall effort

**Comment by hero101** [comment]
Todos: https://github.com/alkem-io/server/issues/3212
