### ISSUE TITLE
Documents authorization policy to derive from usage

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3237]
## Description

As a user I expect to see content held in documents if I have access to an entity

## Acceptance criteria

- [ ] Profile to have a storage bucket, and storage bucket to inherit its authorization policy from that
- [ ] Each profile storage bucket points to a higher level "parent" storage bucket that will be used for management of documents

## Additional Context
An image is uploaded, for example to the background context for a space such as on Velolab: https://alkem.io/velolab/dashboard + then click on more info
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGJsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--258910070dbb8e59f4c2d4cae686588875da32b2/image.png)

The image shown in this page is stored in a document and accessed via:
https://alkem.io/api/private/rest/storage/document/5acc09f8-1fac-4364-965e-4b3eea7e2790

However when opened in a private window without having access to the space:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGZsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a014034ab9f0a18cd088e568cba5fe25e7b934dc/image.png)

The document has an authorization policy that is derived from the Space storage bucket, which derives from the space. So even though the actual field space.context.background has anonymousReadAccess to true - any images uploaded to it will not be visible. 

Ideally the authorization policy of the Document is somehow tied to the entity on which it was used.

Note: this is potentially a big issue also for WhiteboardRT in the future - whereby say we want to allow guest access to a whiteboard (anonymousReadAccess = true) or access for a particular user - they would not in the current setup be able to see the images in the whiteboard once they are converted to Documents + accessed via URLs.

**Comment by Comoque1** [comment]
GA, cannot upload banner on OLDER organizations: authorization issue:
The error is:"message": "Authorization: unable to grant 'file-upload' privilege: visual image upload on storage space: aa1aed33-7b3d-41f9-af41-4c0646e6fa22 user: 406d1f0e-7862-4e5f-8996-af58d6408e57",

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM29KQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d3c1eef9b7fe956696ecd0cdfc68c3a23149c05/image.png)

**Comment by Comoque1** [comment]
New discussion with image in MD cannot be created:  "message": "Cannot read properties of undefined (reading 'id')",

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEVKQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--163d6573e81b0fe94ed0798bd1ec851e03c7da1d/image.png)
