### ISSUE TITLE
BUG: Visuals / Documents from private space Profile / Context cannot are not accessible by anonymous user

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3285]
**Describe the bug**

**To Reproduce**
1. Go to https://acc.alkem.io/api/private/rest/storage/document/3ad9a96f-f996-4656-9224-3b83a7e42a55 - 403 "FORBIDDEN" error is thrown
2. Use unauthenticated or registered user that is not member of: https://acc.alkem.io/pre-release-sp-10-10-2023/dashboard
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1llQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98fc4c9f4e572faa799db14404245a4023c80919/image.png)

**Expected behavior**
Profile and context documents / visuals are accessible by an anonymous user.

**Additional context**
Important to note that if I upload another document / visual it is accessible.
Authorization reset is triggered and does not result in any change.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0FmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--718f55c68e9c0d4d09f0cfbdfc71454cb0190428/image.png)

**Comment by valentinyanakiev** [comment]
Fixed partially. 
@techsmyth I have migrated the storageBuckets that were used for Documents, uploaded via Reference / Visual. Unfortunately, there is a third route, via uploadFileOnStorageBucket. The mutation uses only the storageBucket and it is very hard to infer the type of StorageBucket to map it to. I am leaving this `as is`.
