### ISSUE TITLE
BUG: organization avatars are not visible to anonymous users

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3304]
**Describe the bug**
The avatars for organizations are not visible to non-authenticated users

**To Reproduce**
1. Go to https://alkem.io/organization/rotterdamt3d
2. Look at the page that is served:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkUzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3307673b15cdcec5095f2d3bdafa6440f6705baa/image.png)

The request for the visual is failing:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk0zQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9607088c1f425881d6d3e8fa8581fc65db45a6b/image.png)

**Expected behavior**
The profile information for an organization should be visible for anonymous users.

**Comment by Comoque1** [comment]
The issue is resolved on DEV env.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlU3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10e2c5ce3275475fcb65d83b0d178920cc401095/image.png)
