### ISSUE TITLE
Retrieve journeys I was recently contributing to

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3306]
## Description

As a user I want to have the journeys I recently contributed to visible on my home page

## Acceptance criteria

- [ ] field under the me query
- [ ] allow retrieving a spaces / challenges / journeys via a single field
- [ ] provide a limit on number of returned journeys, mandatory parameter that cannot be more than 20
- [ ] only return journeys where I am a member
- [ ] sorting based on recent contribution (activity log) from me on the journey, with most recent contributions showing first

## Additional Context
To be used for the banner based display of recent journeys

**Comment by valentinyanakiev** [comment]
Will be tested with the client story
