### ISSUE TITLE
Capacity: retrieve activity from spaces I am a member of

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3307]
## Description

As a user I want to see recent activity from my spaces

## Acceptance criteria

- [ ] field under the me query
- [ ] Field named "activityFeed"
- [ ] Retrieve activity entries, with additional fields for a) the space b) my role in that space
- [ ] Results to be paginated
- [ ] Allow retrieving just a single space
- [ ] Allow retrieving just for spaces where I have a given role e.g. lead, admin
- [ ] Activity for a space to include activity entries for challenges + opportunities where the user have read access
- [ ] Restrict results based on having Read access to the activity entry

## Additional Context
For the right hand panel of the new home page design. 
User is able to filter to a particular space
User is able to filter by their role in the space e.g. lead, member

**Comment by hero101** [comment]
Closing in favor of #3386
