### ISSUE TITLE
Capacity: Retrieval of my recent contributions

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3308]
## Description

As a user I want to see my recent contributions

## Acceptance criteria

- [ ] api on me query extended with field "myActivity"
- [ ] Returns a list of my last 4 activity events
- [ ] Only return activity events of the following types: 
CALLOUT_LINK_CREATED
CALLOUT_POST_COMMENT
CALLOUT_POST_CREATED
CALLOUT_PUBLISHED
CALLOUT_WHITEBOARD_CREATED
DISCUSSION_COMMENT

Note: 
- show more + pagination is later!

**Comment by hero101** [comment]
Closing in favor of #3386
