### ISSUE TITLE
BUG: When user has invitation from private space and open the space, errors are thrown

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3309]
**Describe the bug**

**To Reproduce**
1. Go to a private space where the user you use has an invitation - errors are thrown
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUk3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6aad3820828ca414448bc1a56cda26ba52a9bc0/image.png)

**Expected behavior**
TBD

**Comment by techsmyth** [comment]
@me-andre please look at this one, related to #4951 - may be the same regression. But this hits newly invited users to a space so am wary of anything visible to them.
