### ISSUE TITLE
BUG: Unable to delete challenge 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3310]
**Describe the bug**
Challenges cannot be deleted after switch to storage aggregator

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Comoque1** [comment]
With develop branch locally, still cannot be deleted
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFE4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c997707ad06e69161527e2ce738e30287d650b62/image.png)
