### ISSUE TITLE
Load all relations using types

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3314]
## Description

As a developer I want compile time feedback if a relations name has changed

## Acceptance criteria

- [ ] All type orm relations loaded by field name, not strings 

## Additional Context
184 instances

**Comment by techsmyth** [comment]
@valentinyanakiev think we need to go for this near term, would have saved a bunch of bugs today...

**Comment by hero101** [comment]
After a quick search, I have found 184 instances.
