### ISSUE TITLE
BUG: Can't Sort callouts

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#3322]
Describe the bug
Error when trying to sort callouts

To Reproduce

    Go to Contribute tab
    Click on the cogwheel of a callout
    Click on Move down
    See error

Expected behavior
Callouts are moved when clicking on Move Up/Down/Top/Bottom

Screenshots

![Image](https://github.com/alkem-io/server/assets/16032487/a402562c-f7bd-41fe-8626-ea31ea03d040)
{
    "errors": [
        {
            "message": "Authorization: unable to grant 'update' privilege: update callouts sort order on collaboration: 9fdbd76f-57d9-40cb-93d4-50a91b1a6cf6 user: f6df5ebd-3040-4bb4-88f3-195370383615",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "updateCalloutsSortOrder"
            ],
            "extensions": {
                "code": "FORBIDDEN_POLICY",
                "exception": {
                    "message": "Authorization: unable to grant 'update' privilege: update callouts sort order on collaboration: 9fdbd76f-57d9-40cb-93d4-50a91b1a6cf6 user: f6df5ebd-3040-4bb4-88f3-195370383615",
                    "error": "Authorization: unable to grant 'update' privilege: update callouts sort order on collaboration: 9fdbd76f-57d9-40cb-93d4-50a91b1a6cf6 user: f6df5ebd-3040-4bb4-88f3-195370383615",
                    "context": "auth",
                    "code": "FORBIDDEN_POLICY",
                    "exceptionName": "ForbiddenAuthorizationPolicyException",
                    "checkedPrivilege": "update",
                    "authPolicyId": "987bb6fb-051c-4857-a952-2bf318bb52b6",
                    "userId": "f6df5ebd-3040-4bb4-88f3-195370383615",
                    "stacktrace": [
                        "ForbiddenAuthorizationPolicyException: Authorization: unable to grant 'update' privilege: update callouts sort order on collaboration: 9fdbd76f-57d9-40cb-93d4-50a91b1a6cf6 user: f6df5ebd-3040-4bb4-88f3-195370383615",
                        "    at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:7:9)",
                        "    at new ForbiddenAuthorizationPolicyException (/usr/src/app/dist/common/exceptions/forbidden.authorization.policy.exception.js:8:9)",
                        "    at AuthorizationService.grantAccessOrFail (/usr/src/app/dist/core/authorization/authorization.service.js:45:15)",
                        "    at CollaborationResolverMutations.updateCalloutsSortOrder (/usr/src/app/dist/domain/collaboration/collaboration/collaboration.resolver.mutations.js:107:35)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
                    ]
                }
            }
        }
    ],
    "data": null
}

**Comment by Comoque1** [comment]
Fixed, by hiding sorting options for member roles.
