### ISSUE TITLE
api to retrieve random template

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3325]
## Description

As a user I want to see random content on my home page

## Acceptance criteria

- [ ] Allow retrieving an innovation pack from the library at random 
- [ ] Do not cache this data so that every time the page is refreshed it is reloaded
- [ ] Selection to be done server side, client must not be downloading all the data. 

## Additional Context

Only refresh to get a new one when reload the page

**Comment by ccanos** [comment]
Done in this commit: https://github.com/alkem-io/server/commit/4cee21ef183e50858de5b7e62d6cee42f23a4131
```
query {
  platform {
    library{
      innovationPacks(queryData:{
        limit: 1,
        orderBy:RANDOM
      }) {
        id
        nameID
      }
    }
  }
}
```
