### ISSUE TITLE
BUG: callouts failing to load on challenge contribute tab

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3333]
**Describe the bug**
Go to challenges contribute tab + look at graphql results:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGxOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57338e32d48cfbe081c2d56cc6d90d23ac8d6e8d/image.png)

**To Reproduce**

**Expected behavior**
Data can be loaded

**Comment by alstojanovic** [comment]
I can recreate the behaviour when creating a new challenge.
