### ISSUE TITLE
BUG: Error is thrown, when querying storageBuckets, parentEntity

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3339]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/graphql
2. Perform the following query
```
query {
  space(ID: "space2") {
     challenges {
      storageAggregator {
        directStorageBucket {
          maxFileSize
          size
          parentEntity{displayName}
        }
        size
        storageBuckets {
          allowedMimeTypes
          maxFileSize
          parentEntity{displayName}
          documents {
            id
          }
        }
      }
    }
    opportunities {
      storageAggregator {
        directStorageBucket {
          maxFileSize
          size
          parentEntity{displayName}
        }
        size
        storageBuckets {
          allowedMimeTypes
          maxFileSize
          parentEntity{displayName}
          documents {
            id
          }
        }
      }
    }
  }
}

```
3. Error is thrown: `"message": "ER_BAD_FIELD_ERROR: Unknown column 'callout.profileId' in 'where clause'",`
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1pTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0488eb29b212ab248279b1c2bc159e3481813298/image.png)

**Expected behavior**
No error is thrown.Correct data is returned.

**Comment by Comoque1** [comment]
The error from the bug is not hit anymore, but different one is shown: "message": "Cannot read properties of undefined (reading 'calloutId')",

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0pmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4454759d32049a93f45979d756ca3102ba750d2/image.png)

@valentinyanakiev, if you prefer, I can raise another but about it?

**Comment by Comoque1** [comment]
The above comment is still reproducible.
Can be easily hit, when create a single callout with uploaded image and delete it afterward.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWR6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4dac9cb796ce5fb90b92c9b28bcb9d1d7c9a3c0/image.png)

**Comment by techsmyth** [comment]
This sounds like storage bucket not being deleted?!

**Comment by techsmyth** [comment]
Please also check on what storage bucket the image is being uploaded, it might be going to the wrong one...
