### ISSUE TITLE
BUG: documents for visuals on private spaces are failing

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3366]
**Describe the bug**
The visual used on the card for spaces is failing to load for users not logged in. For example: 
https://alkem.io/api/private/rest/storage/document/0eb6723b-778b-4399-9d0c-90db28be419d
This is the card visual for UWV

**To Reproduce**
1. Look at the dashboard page as a not logged in user

**Expected behavior**
Documents that are holding visuals used by Spaces / Challenges / Opportunities should be moved to the StorageBucket under the Profile for that journey.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1Z3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7b9e12899b8b28873e4b2b2496fb4b2b3af21b5/image.png)

**Comment by valentinyanakiev** [comment]
There are 2 bugs here, so raising the estimate accordingly
