### ISSUE TITLE
Activity feed query

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Server#3386]
## Description

As a user, member of a Space
I want to see the activity feed of a Space I am member of and my own activity
So that I am aware of what is happening in my communities and I feel more engaged

## Acceptance criteria

- [ ] An ActivityFeed graphql query exists
- [ ] The results are filtered by 
  - activity types
  - own user activity (whoever is making the request)
  - Spaces
  - roles the user has in the Space
  - the results are paginated

## Additional Context
- all the returned results implement ActivityLogEntry
- multiple activity types can be specified; all if omitted
- multiple Spaces can be specifiied; all the user is member of if omitted;
- multiple roles can be specified; all roles if omitted;
- feed can be specified just for the user or about all the users in which the user is member of; or to specific Spaces if the corresponding filter is applied
- activity for a space to include activity entries for challenges + opportunities where the user have read access
- restrict results based on having Read access to the activity entry

**Comment by hero101** [comment]
Based on #3307 and #3308

**Comment by valentinyanakiev** [comment]
Will be tested with the client story
