### ISSUE TITLE
BUG: Unauthenticated users get "NOT_FOUND" error instead Unauthorized 

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3387]
**Describe the bug**

**To Reproduce**
1. Go to https://alkem.io/api/private/rest/storage/document/85321ced-72ff-43d6-a4ac-9d69d541b3e1 without being logged in
2. The error returned is `"statusCode":404,"code":"NOT_FOUND"`
3. See error
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEdBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0abfe27aaa0ac5dca8b6fe9d01e5880703b265e/image.png)

**Expected behavior**
The rest error returned must be: `"statusCode":403,"code":"UNAUTHORIZED"`
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by valentinyanakiev** [comment]
@Comoque1 should be fixed with the next deployment
