### ISSUE TITLE
Search results not picking up lower case

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#3389]
**Describe the bug**
When I search for digitale leefomgeving, the Space does not show up
When I search for Digitale Leefomgeving, the Space does show up

For users it will be very frustrating when they can't find their space or challenge, even though they type in the exact wording (with the exception being that they used lower case instead of capitals)

**To Reproduce**

**Expected behavior**
provide search results regardless of capital/lower case

**Screenshots**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzF1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1b3f9acf6aaf8d7eaf801493817733c815f283e/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJ1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36918ce75073643672a27f3a6a2f21a26dde1c67/image.png)

**Comment by techsmyth** [comment]
@valentinyanakiev am guessing this is a side effect of the recent search changes...
