### ISSUE TITLE
BUG: Space admin, who creates an organization, cannot update it

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3399]
**Describe the bug**

**To Reproduce**
1. Go to https://acc.alkem.io/admin/organizations/
2. Authenticate with Space admin
3. Navigate to user profile / organizations
4. Create a space - successfully created
5. Update the space and press "Save" button - error is thrown: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTJPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c89d8b5d8ad9324ddf51f12aa516d2c3a997ed3f/image.png)

**Expected behavior**
When space admin creates an Organization, he become Organization admin, hence, he must be able to make modifications / assignments.

**Comment by techsmyth** [comment]
@Comoque1 just tried to reprduce this - but the scenario was working fine for me...

**Comment by Comoque1** [comment]
Cannot reproduce anymore as well on DEV env.
Could be data issue on ACC env.
