### ISSUE TITLE
BUG: Search doesn't show results for tags on posts in call for posts

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3400]
**Describe the bug**
I've created a post in a call for post with:
Title: Dolphin!
Description: cat
Tag: dog

When I search for these different animals I get the post as a result for dolphin and cat, but not dog. Also interesting is that when I search for cat, the opportunity shows up as a result. This seems to come from the description: "Improved communi**cat**ion"

**To Reproduce**

1. Go to https://acc.alkem.io/space-20-09-23-release/dashboard
2. Type in the search "dog", (the search filtered with space) - post card is not returned when searched by tag and  filtered space
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemIyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68276f30001689000c11e1dd1bce8a201b949a64/image.png)

**Expected behavior**
Post card is returned when searched by tag and  filtered space.

**Screenshots**

![Image](https://github.com/alkem-io/client-web/assets/38861315/07ed979c-38c9-4f5f-9d73-f4292bacb56c)

![Image](https://github.com/alkem-io/client-web/assets/38861315/d2bec196-ee50-476d-9117-415326ce1e97)

![Image](https://github.com/alkem-io/client-web/assets/38861315/abedd0a1-8729-4acf-8bca-1c5fab758f00)

**Comment by techsmyth** [comment]
@Comoque1 just tried this out + working fine: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzNhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1546736d95f2db75e3e48d7d9055a71c7306e83/image.png)

**Comment by Comoque1** [comment]
@techsmyth the issue is reproducible, but is hit when search within a space.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekQyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a3e6ba041916746ac6fdfb80b24ec18d7e338dd/image.png)

When searched using the global search - returns the post card
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekwyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3bfd708dbf707acdd10694bebdfda71c0259d12/image.png)


Updated the AC.
