### ISSUE TITLE
Allow whiteboard RT to be viewed read only with updates + presencing

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3409]
## Description

As a <user I want to be able to view a whiteboard RT + see what is happening

## Acceptance criteria

- [ ] Allow connections to a whiteboard RT in read only mode, in addition to update mode - with events filtered accordingly. To be able to connect in read only mode requires the READ privilege. To connect in update mode requires the UPDATE_CONTENT privilege. 
- [ ] Client to use the whiteboard rt read only mode to display whiteboard rt instead of the pure content view

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by ccanos** [comment]
A small client change is needed too, 
client-web/src/domain/collaboration/whiteboard/WhiteboardDialog/WhiteboardRtDialog.tsx
On line 273, we are checking if the user has permission to edit the whiteboard, and showing a single-user-readonly `ExcalidrawWrapper` if they don't. That needs to change and use directly `CollaborativeExcalidrawWrapper` in `viewModeEnabled: true`. I think that can be all, but contact me whoever takes this task if anything is needed.
