### ISSUE TITLE
Connection modes on whiteboard rt

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3412]
## Description

As a user I want to have multiple modes, with each mode having a limit on the number of connections

## Acceptance criteria

- [x] Allow multiple modes for a room

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by hero101** [comment]
Needs a wider discussion about licesing, how the limits will be enforced and the functionality detailed - differing it to next Sprints

**Comment by techsmyth** [comment]
@hero101 split the second half of this one out
