### ISSUE TITLE
Refactor IJourney and IBaseChallenge

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#3418]
## Acceptance criteria
- [ ] All the fields of IBaseChallenge are exposed the same way (fields / field resolvers)

## Additional Context

- If we don't have the same hierarchy we won't hit the same field resolvers and the behavior will be altered
- There is a lot of overlap in the two - find what exactly needs to be used.
a WIP draft PR that can't start the server https://github.com/alkem-io/server/pull/3405

**Comment by techsmyth** [comment]
Done as part of subspaces work
