### ISSUE TITLE
Uploading to a visual or reference to remove previous Document used

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3430]
## Description

As a user I do not want to have a growing set of storage space used if I keep on updating my visuals or references

## Acceptance criteria

- [ ] Uploading an image to a visual should delete the previous Document entity that was used, so that it no longer shows up in the StorageBucket

## Additional Context
Previously, if I keep on changing the banner in e.g. a Space then I see all the Documents that were created, and the space for all the visuals, even the ones I do not use, is reported in my usage which is very confusing. 

Note: the cleaning up of IPFS files to be handled separately, this for now ensures that storage usage is more logical and understandable - and makes the IPFS cleanup later much easier.

**Comment by techsmyth** [comment]
@valentinyanakiev this would seem to be a fairly simple fix to address the bloat of images that are being generated via whiteboard visuals being generated....thoughts?

**Comment by Comoque1** [comment]
The behavior works as defined, but introduced a [bug](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/3459) BUG: When user upload the same file twice to the same entity, requests start to fail #3459
