### ISSUE TITLE
BUG: When cacllout has a reference, template cannot be created

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3432]
**Describe the bug**

**To Reproduce**
1. Go to http://localhost:3000/111/community
2. Create any type a callout
3. Add reference to it
4. Create a template from it: error is thrown: `      "message": "Variable \"$framing\" got invalid value { id: \"410a79e4-1f13-4a17-8220-5036d93c09af\", name: \"New reference\", uri: \"\", description: \"\" } at \"framing.profile.referencesData[0]\"; Field \"id\" is not defined by type \"CreateReferenceInput\".",
`
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXk4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2ee783afc997ac328ffb39e41f7acb6b079338c/image.png)

**Expected behavior**
Template can be created from callout with references.
"Collection of links" callout template is created when the callout has references

**Comment by Comoque1** [comment]
Still reproducible, with different error: `      "message": "Variable \"$calloutData\" got invalid value { id: \"d745018b-b74e-4075-86fc-9b138c86a253\", name: \"New reference (2)\", uri: \"\", description: \"\" } at \"calloutData.framing.profile.referencesData[1]\"; Field \"id\" is not defined by type \"CreateReferenceInput\".",
`
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDIvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--00d07f4551cc7f24cdcc2f66e96c477583ffce1c/image.png)

**Comment by alstojanovic** [comment]
The question about the references is also do we prefill the new callout with them?
