### ISSUE TITLE
Beta testing organizations

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3445]
## Description

As a platform admin I want to be able to assign whole organizations to be beta testers

## Acceptance criteria

- [ ] Allow for organizations to be beta testers: Server authorization logic for assigning privilege for access to beta testing features to allow testing for organizations with the beta tester privilege

## Additional Context
Server only for now, no UI changes on the client - do be done on api when needed

## To test

Use the new mutation grantCredentialToOrganization to assign the BETA_TESTER credential to a chosen organization.

Login as any user (can be global admin) and ensure the user is not part of the beta testing group.

Do authorization reset on Platform, and verify the credential rule is there with the additional criteria for associates of the org:
The query to check the credential rule is:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9hQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b09c4157962f716608b126facc36c26673a7994/image.png)

which the rule ending in "platformAccessGuidance" will have a criteria for each org that has the beta tester credential (after resetting auth):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOURhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--242f5b6f938184c11aa6d1f85d0af73c627bed8d/image.png)

Check the privilege on platform i.e. platform { authorization { myPrivileges} } } - it will not be there.

Add the user as an associate of the chosen org. Check the privilege again - it should now be there.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUxhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b99da0ccd439c6055e1a7630773bb5621188eb25/image.png)

**Comment by techsmyth** [comment]
@Comoque1 instructions for how to test this is working are above. Working for me but was not working for Valentin earlier - so am curious what you find...

**Comment by Comoque1** [comment]
@techsmyth tested on ACC env the following scenarios:
1. Grant Org credentials > Reset Platform > Assign User to Org community (Journey Community Admin and Registered User ) > Have BETA_TESTER privilege - **OK**
  1.2 Remove User from Org community (Journey Community Admin and Registered User ) > DON'T have BETA_TESTER privilege - **OK**
2. Assigned second old Org BETA_TESTER credentials > reset Platform - **OK**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXo2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3e40a917353b5bf39298c268437a170c5685c57/image.png)
2. Assign Registered User as Org Member to the second ORG > Have BETA_TESTER privilege - **OK**
3. Assign the same Registered User as BETA_TESTER > no Errors correct privileges - **OK**
4. Remove Registered User from BETA_TESTER and Revoke Credentials of second ORG BETA_TESTER > reset Platform > user doesn't have BETA_TESTER privilege - **OK**
