### ISSUE TITLE
BUG: contributors in a space with whiteboard RT enabled cannot create whiteboard RT

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3449]
**Describe the bug**
In a space with Whiteboard RT flag enabled, contributors are not able to create whiteboard RT callouts

**To Reproduce**
1. Go to a challenge with a challenge member or challenge admin (i.e. https://acc.alkem.io/release-27-07-2023-hub/challenges/release-27-07-2023-c-3261/dashboard)
2. Set the space preference "Create blocks" to disabled
3. Set The space "Space Features" , "RealTime Whiteboards" to active
4. Set challenge preference: "Allow contributors to create Callouts" to active
5. Navigate with the challenge member to the challenge and open "Add collaboration tool" dialog - "WhiteboardRT" option is not available, but the user has the privilege
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMy9OQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f48536fb950dad73ff86128725593eb04888ae14/image.png)

**Expected behavior**
If whiteboard RT is enabled, then users with contributor privilege should be able to create whiteboard RTs.

## Additional information
When the space preference "Create blocks" to **enabled**, the issue is not reproducible.
The issue is not reproducible on Space level at all.

**Comment by techsmyth** [comment]
@Comoque1 can you please try to reproduce this one? Was reported by Denise that admins of challenges were not able to create whiteboard RTs. @larssondenise anything to add to the description above?

**Comment by Comoque1** [comment]
@techsmyth @larssondenise when the space preference "Create blocks" is disabled, the issue is reproducible on Challenge level. On space level, the user is not supposed to even see ""Add collaboration tool" button.

Repro steps are updated.

**Comment by techsmyth** [comment]
@Comoque1 perfect, thanks!

**Comment by techsmyth** [comment]
@Comoque1 I can indeed reproduce it on acc, but not locally with latest source code. Can you please try this out on dev?

**Comment by Comoque1** [comment]
@techsmyth you are right, on DEV env is not reproducible. 
Closing the issue.
