### ISSUE TITLE
Migrate server db to be MySql

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3454]
## Description

As a sysadmin I want to have less database types in production

## Acceptance criteria

- [ ] Server db migrated to mariadb in server repo
- [ ] Maria db container removed from startup services in server repo

## Additional Context

The MySQL cluster we are about to use uses MySQL v 8.3.0. Migrate the mySQL image to that version and test it.

**Comment by valentinyanakiev** [comment]
This should be fairly straightforward operation as we don't even need a backup. It should be straight-up compatible. One thing to consider is, the driver for mysql and the cluster are different so the package is different - this needs to be checked and adds a bit of uncertainty.

**Comment by Comoque1** [comment]
The following actions were required to run the local env successfully.
- Remove Mysql and MariaDB container
- Remove volumes
- Run the docker-compose
- Run migrations
- Start server

Tested:
 - ran an api test
 <img width="1181" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekl3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82cacb8a0604ce057e2d5031d6934c84215231ef/image.png" alt="image.png" />

 - tested authentication flow from the client
