### ISSUE TITLE
BUG: Kibana logs are tracking many times same errors: Internal error occurred during message handling.

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3464]
**Describe the bug**

**To Reproduce**
1. Go to https://kibana.alkem.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:'2023-11-16T07:23:48.571Z',to:'2023-11-16T12:22:30.649Z'))&_a=(columns:!(message,err.code,code,context,stack),filters:!(),grid:(columns:(tags:(width:310))),index:ee214087-bb19-4337-b7ec-a593912a6afd,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))
2. The error: `Internal error occurred during message handling. Please check your implementation. AuthenticationException: Access token has expired!` is reported constantly

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnJrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83021e5ec885cbf3489708087ab93df7eca4bee2/image.png)

**Expected behavior**
Understand what is happening.

Spike: look for half a day.

Users to not receive errors.

**Comment by larssondenise** [comment]
This seems to be related to the case when users get an error when they submit a post to a call for post. The user gets an error and thinks their work is not saved / uploaded so they are frustrated or type their contribution again. But, when they refresh the page, both contributions are visible..
If so > user high priority

**Comment by Comoque1** [comment]
To be verified on PROD.
