### ISSUE TITLE
BUG: Registered users doesn't have rights to see profilePicture of user registered with linkedin

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3469]
**Describe the bug**

**To Reproduce**
1. Go to https://dev.alkem.io/graphql
2. Authenticate to the DEV env.
3. Perform the following query:
```
query{
  lookup{
    document(ID:"9d7c2afa-5191-46b6-a0e0-1a152f924a57"){
      displayName
    }
  }
}
```
4. Authorization error is thrown: `"message": "Authorization: unable to grant 'read' privilege: lookup Document: 9d7c2afa-5191-46b6-a0e0-1a152f924a57 user: a95a859a-6e23-4df1-b771-f643fe9fb60f",`
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEwwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5281731cf7431474903c9679a3558250f10a297/image.png)

**Expected behavior**
Every authenticated member can see the avatar of registered with linkedin user.

**Comment by techsmyth** [comment]
@Comoque1 @valentinyanakiev  it looks like the visual is being uploaded to the wrong storage bucket, or does not get saved into the storage bucket, as these users do not have any documents in their storage
