### ISSUE TITLE
BUG: Querying "task" fails to return data

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3472]
**Describe the bug**

**To Reproduce**
1. Go to https://acc.alkem.io/graphql
2. Perform the following query:
```
query{
  task(id:"23bf1a3c-aefd-4c45-ade3-d36d984b2780"){
    created
    results
    status
    progress
  }
}
```
3. Error is thrown: "message": "Cannot return null for non-nullable field Query.task.",
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2IyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7cd0bbbc1cedb58aa04de7ef6dbab2b6aac2f72/image.png)

**Expected behavior**
The query returns the results without failing.

**Comment by hero101** [comment]
Please verify that the task has been created within 1000 seconds - That is how long the task is stored.

**Comment by Comoque1** [comment]
The issue wasn't reproduced with pre previous release. Closing it.
