### ISSUE TITLE
Whiteboard RT switch to change into 1-20 simultaneous collaborators

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#3556]
## Description

As a admin, I want to be able to control the amount of people that can collaborate simultaneously on a whiteboard.

## Acceptance criteria

- [ ] Change the current Whiteboard RT switch (used to switch Whiteboard RT on/off per space) to switch between 1 and 20 users that can **collaborate** on a whiteboard simultaneously.
- [ ] New users are moved to read-only if the room capacity is reached
- [ ] A message is shown to the user when the room has reached capacity. The message is about letting the user know that they are read-only and capacity is reached.

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by techsmyth** [comment]
@hero101 please update the acceptance criteria based on the excalidraw board e.g. message to user re why they cannot connect

**Comment by hero101** [comment]
@SimoneZaza if an editor is dropped and room is back to capacity, should the viewers be promoted to editors.
I would guess yes, so my question is can we make a first pass without it, because it introduces more complexity or it doesn't make sense rolling this out without it?

**Comment by techsmyth** [comment]
@hero101 no, the person can reload etc. Or we can later add a button / try to reconnect - lets keep this particular one simple.
