### ISSUE TITLE
Performance of my dashboard not demonstratable

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3567]
## Description

As a user I want my dashboard to show up fast

## Acceptance criteria

- [ ] All queries to return in less than 3 seconds, even for users with a lot of memberships

## Additional Context
Response times for neil_admin@alkem.io dashboard:

<img width="584" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE1WQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8053d6abc169d6ad6c7be05ae1119afab579c8e/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
As @valentinyanakiev asked me, I am following up with some details around the request triggered on `My Dashboard` page on refresh:
<img width="1118" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9rQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f4a8ba6120afde6522566d15dd28eca8c62b8a7/image.png" alt="image.png" />
[myDashboard_requests_stats.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58a3c7ef4b38242e64567ea902e31ed836a391be/myDashboard_requests_stats.xlsx)


The durations that are not flagged with `s` are in `ms`.
Total number of different requests triggered: 18
Total number of requests performed on the page without scrolling: 28
The durations in the table for the duplicated requests is highest reached from the client
Environment: Acceptance
User: admin@alkem.io

<img width="1411" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--620682ebe4acc33e9089417a5ea546e51b827bec/image.png" alt="image.png" />

**Comment by valentinyanakiev** [comment]
Raised:

- https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5488
- https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/3576
- https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5490
- https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/3575

**Comment by valentinyanakiev** [comment]
Closing this after the performance analysis + stories were raised.
