### ISSUE TITLE
[Spike] Migrate to Node LTS

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Server#3569]
## Description
As a developer
I want the most recent or up to date dependencies
So that the project is provided with more fixes, fixed vulnerabilities, better api, etc.

## Acceptance criteria

- [ ] Upgrade to 20.x (currently in LTS)
- [ ] Try to address or document any breaking changes, if too much effort is needed

## Additional Context
https://nodejs.org/en/blog/announcements/nodejs16-eol/
https://nodejs.org/en/about/previous-releases

**Comment by Comoque1** [comment]
File upload is failing using this branch:
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG5nQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--191f8e6d3d15e08020745e9faf5ac43aa39b6483/image.png" alt="image.png" />
