### ISSUE TITLE
Increase limit of post description

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#3574]
## Description

As a user working with choral explanations on the platform, I need a higher limit for the post descriptions. 

## Acceptance criteria

- [ ] Increase the visible limit (from 8000) to 16000
- [ ] Increase the server limit (from 32000) to 64000
- [ ] …

## Additional Context
Requested by TIP

**Comment by alstojanovic** [comment]
@SimoneZaza @techsmyth 
The post description is a field on the profile entity.
Is the goal of this task to increase the limit for description on Profile to be 64000 and on the client to increase the description limit to 16000 only for post creation forms?
This can be done but I just want to remind that we had an agreement that all markdown fields should have the same limit.

**Comment by techsmyth** [comment]
@alstojanovic yes this does bring back an inconsistency - but it also helps a customer so please do that for now.
