### ISSUE TITLE
Updated authorization roles using createdBy on Post, Whiteboard

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3583]
## Description

As a developer I want a clean code base

## Acceptance criteria

- [ ] Authorization rules on Post, Whiteboard to be updated to not duplicate assigning of C,R,U that cascades from Contribution

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by valentinyanakiev** [comment]
This will create implicit dependencies for services, e.g. `PostAuthorizationService` requiring a `Contribution` to be passed, which is not great, doesn't add a lot of value, and leads to additional lookups in the DB. I think it is fine (even better design) to have `createdBy` on both levels, given it's a reference.

**Comment by valentinyanakiev** [comment]
I'd actually advocate for having `createdBy` on every `Authorizable` entity --> this will enable `UserSelfManagement`  on every entity with the same generic implementation.

**Comment by techsmyth** [comment]
@valentinyanakiev actually my concern is less with the field on the entities, but the authorization rules. It does not make sense to have an authorization credential rule on Post when there is one on the containing Contribution entity. And ditto for Whiteboard. I would prefer to see the situation whereby the wrapping entity (i.e. CalloutContribution / Template) determines the credential rules. This also means that the PostAuthorizationService does not need to know the Contribution entity.
