### ISSUE TITLE
BUG: Error Signup: email already used, while it is not

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#3596]
**Describe the bug**
When trying to sign up with my hotmail email address, I get an error (see screenshot). However, this email address is currently not used on the platform. It might be that I've used it before, but I'm not sure about that. 

<img width="1278" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUErQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1481c0943d4ddd35ecd51aebc3b75e32941783b/image.png" alt="image.png" />

**To Reproduce**

**Expected behavior**
To be able to sign up with this email address

**Comment by techsmyth** [comment]
@Comoque1  Please verify the scenario where this happens. @SimoneZaza Consider a better error message in this scenario?

**Comment by SimoneZaza** [comment]
@techsmyth I prefer not to get the error at all? When my account was deleted before, I think should be able to create a new account with the same email address?

**Comment by techsmyth** [comment]
@SimoneZaza the issue is that you still have a Kratos account with that email address. When we delete a profile on Alkemio we do not currently also delete the Kratos account - that is gap that we do need to plug. @valentinyanakiev can you manually for now delete the kratos account with Simone's hotmail address? I will separately raise an issue to also delete Kratos account when deleting a user.

**Comment by Comoque1** [comment]
@techsmyth , there is such [story](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/2137) already

**Comment by valentinyanakiev** [comment]
@techsmyth @SimoneZaza I expect when a story is in progress to have all the necessary artifacts to do it needed. Crucially:
- Steps to reproduce, in this case.

I can't guess what is the email, and it is not evident in the screenshots. Please provide details.

**Comment by SimoneZaza** [comment]
@techsmyth good to know that this is the case. @valentinyanakiev simone_rietmeijer@hotmail.com. Thanks!

**Comment by techsmyth** [comment]
I have moved the other issue to be part of the same epic as this one, we can discuss it a bit later. First other use cases to be addressed, but we do need to delete the account from Kratos as part of user deletion.

**Comment by valentinyanakiev** [comment]
@techsmyth  @SimoneZaza done, the account [simone_rietmeijer@hotmail.com](mailto:simone_rietmeijer@hotmail.com) is deleted.

**Comment by valentinyanakiev** [comment]
@SimoneZaza please review you can sign up and close the issue if the problem is fixed for you :)

**Comment by SimoneZaza** [comment]
Great, works, thanks!
