### ISSUE TITLE
Allow platform level updates on user profile

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3605]
## Description

As a platform admin I want to be able to update information in user profiles that is otherwise static

## Acceptance criteria

- [ ] mutation: updateUserPlatformSettings, which takes the user id to be updated
- [ ]  The following fields are settable in the payload: email address, nameID
- [ ]  Validation: ensure no other user has the provided email address or nameID 

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
Tested the following cases:
 - Brand new user with:
   - updated own profile with visuals and all data
   - contributed to forum
   - created challenge
   - with open application and invitation
   - 
The above scenarios work in the case the user email is changed and after that registers with the new email.
If the user authenticate with the old email, data messes up, and he cannot see own profile visuals, activity logs and some more inconsistencies.

When we do this on production, we must consider, to inform the user to NEVER again try to authenticate with old email.

**Comment by techsmyth** [comment]
@Comoque1 can you please try logging in with the old email after say 4 hours?? I am curious what happens then...

**Comment by Comoque1** [comment]
> @Comoque1 can you please try logging in with the old email after say 4 hours?? I am curious what happens then...

I've tried 14 hours later - the user with old email looks like a brand new, but haven't explicitly check all policies, etc.
Tried again with the new email, seems to be fine as well.

**Comment by techsmyth** [comment]
That points to the issue being a caching one, so the risk / issue only happens for a period of time after the change happens.
