### ISSUE TITLE
Sort Challenges/Opportunities based on displayName, not NameID

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#3607]
## Description
As a user, when I see a list of Challenges in alphabetical order, this makes me assume that I can find a certain challenge in a certain place in the list. However, if the title has changed, this system no longer holds. I can't find my Challenge!

## Acceptance criteria
Sort based on displayName instead of NameID for all lists of Challenges and opportunities inside:
- Space
- [ ] Tree view on Space Dashboard
- [ ] List of Challenges on Challenges Page
- [ ] Block with Challenge cards on Challenges page
- Challenge
- [ ] List of Opportunities on Opportunities page
- [ ] Block with Opportunity cards on Opportunities page

## Additional Context
please add this: 
it's sorting them alphabetically by nameId
space.service.ts
 <img width="754" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE5VQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12b0834452ccae35ebb91b8d88c667e6fb73df2a/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Tested on dev env. and sorting is applied as per AC.
Sorting is still not applied on Search (global / space)
