### ISSUE TITLE
spaces query: separate filtering from sorting

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3615]
## Description

As a developer I want to have the filtering separated from how results are sorted

## Acceptance criteria

- [ ] Separate the logic for sorting spaces results from the filtering to get to the set of spaces

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
Filtering seems to be applied correctly. Tested also from the client dev-alkem.io, demo.dev-alkem.io and uwv.dev-alkem.io
