### ISSUE TITLE
Track activity on whiteboard content update

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3631]
## Description

As a User I want to track activity on whiteboard content update.
## Acceptance criteria

- [x] new activity type: Whiteboard content modified
- [x] Adding/Removing content triggers an update event
- [x] Update event is throttled at source *per user* e.g. once 1x per user connection
- [x] Client uses whiteboard content update activity on the "**my** latest journeys" 
- [x] Client uses whiteboard content update for **my** latest contributions". This block to only show one entry for each entity and by activity type. 
- [x] Client to not show show whiteboard update activity in "latest activities in my spaces". 
- [x] Add a parameter to optionally de-duplicate activity events

UI changes:
- [x] My memberships list that is based on latest activity will now include whiteboard content modified as activity to base the order on
- [x] My latest contributions block shows this activity exactly the same way as when a whiteboard is created
- [x] **Latest contributions in my Spaces + recent activity in this Space (Sp Dash) do not show this activity yet** (filter out?).

## Additional Context

This is the first activity for updates, all other activity types are for creation 

Later:
- Cool down period? Show this in ui?
- What about my latest contributions block?
- Maybe grouping per entity, and then expand to show all logs

**Comment by hero101** [comment]
@SimoneZaza We would need more information about how will this work exactly.

**Comment by alstojanovic** [comment]
Also, the whiteboard content could possibly change every 15 seconds. That would maybe be too much activities per whiteboard. It may be more useful to know when the first change happened so that users can see that there is someone in that whiteboard doing things and that they can join the whiteboard.

**Comment by alstojanovic** [comment]
@SimoneZaza Do we want to show whiteboard updated activities on journey dashboard pages in the contributions block? I assume yes but want to check.

**Comment by SimoneZaza** [comment]
@alstojanovic no, as long as we cannot group them we don't want to show them there (see last AC), since 1 session with a small group of people on a whiteboard would then already fill up the entire block.
