### ISSUE TITLE
Delete Kratos account without deleting the user profile

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3650]
## Description

As a user I want to change the method I use to authenticate (account) without deleting my user profile 

## Acceptance criteria

- [ ] Mutation to allow deletion of Kratos account without deletion of a user profile

**Comment by Comoque1** [comment]
Applied on ACC env the following checks:
Trigger the mutation:
```
mutation deleteAccount {
  adminUserAccountDelete(userID:"1a8672fc-1694-40c5-bcba-c55c6dd58f89") {
    id
    email
  }
}
```
- user removed from kratos db
- user remains on alkemio db
- all direct to the user entities remain on alkemio db
