### ISSUE TITLE
States to innovation flow entity

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3652]
## Description

As a subspace admin I want to be able to manage my flow

## Acceptance criteria

- [ ] InnovationFlow entity extended with a list of States, each of which as a displayName, description + sortOrder
- [ ] Mutations to edit states / sort order

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by Comoque1** [comment]
@ccanos  when challenge / opportunity is created with not default innovation flow template, the callouts are not displayed on "contribute_right" location. After changing the innovation flow back to the default one - they become visible.
<img width="1482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3ab4304b7070a748226ea69886a7c4e30c43971/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
The issue from the above comment is not reproducible anymore.
Tested on ACC env:
 - Innovation pack - innovation flow
   - CRUD - OK
 - Space - templates - innovation flow
   - CRUD from Space - OK
   - Import from innovation pack and CRUD on it - OK
 - Challenge and  Opportunity
   - Create journey with not default template - OK
   - Change innovation flow  - all callouts move to first state - OK
   - Change states - OK
   - Move callouts among different states - OK
   - Move callouts among different states and change innovation - all callouts move to first state - OK
