### ISSUE TITLE
BUG: september offsite challenge performance has degraded

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3656]
**Describe the bug**
Loading the september offsite challenge is taking close to 10seconds:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzJPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee3df951ac8e1a38c345f978aa0d3a99654a0b61/image.png" alt="image.png" />

I have noticed over the past week that the performance of this challenge has degraded substantially. It used to be a lot faster - maybe related to the database schema checks now added?

**To Reproduce**
1. Go to https://alkem.io/building-alkemio-org/challenges/teamoffsiteseptemb-9083/contribute
2. Look at the callouts query and how long that it taking to load. 

**Expected behavior**
Callouts query for this challenge returns in less than 2 seconds

Note: this is a space that I like to use to show off the platform, but I do not use it now that the performance has degraded.

**Comment by valentinyanakiev** [comment]
I don't believe it's the database, but this query is insane - it returns 193Kb of data (we are talking about 193Kb of text). Surely we don't need all that when we open the page...

**Comment by techsmyth** [comment]
@sander-cb fyi - please add other details to those already provided: "The TIP knowledge base has become quite slow to use:
https://alkem.io/tip/knowledge-base

That's good news and bad news. The good news is that we
apparently have a lot of content! The bad news is the wait time
can be daunting for potential participants.

What I can find so far: the GraphQL query that runs on every page load
is triggered, now takes 4+ seconds. It's largely about
static content, which changes at most a few times a week. The
payload is currently 218 KB. So I think most of the time is in the
combined database queries."

**Comment by valentinyanakiev** [comment]
I've just spent 1 hour re-creating and isolating what we had with MariaDB on the 2nd of February in production.
The first query was done with the current setup and dataset (visible with the data sample) and the last few with the one from 2nd of February:

<img width="1598" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDJ5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7805ecec92cef9ba68d8872f06197e63a43d15bb/image.png" alt="image.png" />

Practically speaking, the issue is in the amount of data + algorithms extracting it.

**Comment by Comoque1** [comment]
After a discussion with @ccanos the impact could be on the following areas and should be tested:
 
 - CRUD
 - all callout types
 - on all journeys
 - subscriptions
 - direct links
 - change innovation flow template
 - move operations
   - between tabs
   - between callouts
 - convert callout to template

**Comment by Comoque1** [comment]
The above scope was tested on acc env.
The only issue found was: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/5695

**Comment by sander** [comment]
Thanks, the TIP KB is also more usable now: 1+ second instead of 4+ seconds to load the menu data.
