### ISSUE TITLE
When one WB crash, it has impact on rest of the WBs

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3659]
**Describe the bug**

**To Reproduce**

1. Go to sandbox
2. Create a WB with enormous amount of objects
3. Save the whiteboard
4. Start working on other whiteboards - they are behaving unpredictable (i.e. when adding WB to wb collection callout - the dialog is open and closed by itself and user cannot edit it)

**Expected behavior**
When one WB crash, should not have impact on rest of the WBs

**Screenshots**

**Comment by hero101** [comment]
Could not reproduce. Tested with the following callout - https://sandbox-alkem.io/aht-whiteboards/challenges/allhandstesting--8401/collaboration/testwbcallout-3398

I base it on the heavy traffic we generated over the AHT.

We might need to fix this by limiting the amout of element on a whiteboard. Currently the websocket is killed when it transmits more than a megabit for a single message.
