### ISSUE TITLE
BUG: When owner or admin try to update  "who can edit" WB of collection of WBs, error is thrown

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3662]
**Describe the bug**

**To Reproduce**

1. Go to https://sandbox-alkem.io/aht-whiteboards/collaboration/memberaddsacallou-4552/whiteboards/whiteboard-328
2. Open WB of collection of WBs
3. Click on share icon
4. Change the "This whiteboard can be edited by:" to "The owner and the admins and leads of this Space" - error is thrown: `      "message": "Framing not initialized on whiteboard: '3b505068-65fe-48a6-90dd-33ff734c8359'",`
<img width="1537" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnFYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f121063558fe4022ab6f476171283a2f4286edc3/image.png" alt="image.png" />

**Expected behavior**
Change is successful.

**Comment by me-andre** [comment]
@Comoque1 , this doesn't seem to be a client error

**Comment by Comoque1** [comment]
@me-andre  - transferred to server repository.

**Comment by Comoque1** [comment]
The issue with the error is fixed, but I can see that a member user, has can updated and save the changes
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0tlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--204b6d8004d1077dc25ce9ca3bfda614491621c0/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Now works better :)
