### ISSUE TITLE
Allow access to the creation date of Space

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3666]
## Description

As a operations person I want to be able to see when a Space was created

## Acceptance criteria

- [ ] expose the createdDate on the space entity

**Comment by Comoque1** [comment]
<img width="1953" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0N5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7b3657e1e3f0631c0b36dff0b23af3921c5c312/image.png" alt="image.png" />
