### ISSUE TITLE
Account entity

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3685]
## Description

As a developer I want aspects that are shared withing a Space hierarchy to have a clear concept in both the domain model and the code base. Potentially also exposed to the admin /users. 

## Acceptance criteria

- [ ] Create a new Account entity that holds a) library b) license c) defaults d) host org
- [ ] Replace spaceID with pointing to the Account entity
- [ ] Remove Project + Agreement modules
- [ ] Deletion of Account entity is responsibility of Space entity, as is cascade of authorization
- [ ] Space module cleaned up
- [ ] Client to use new api

## Additional Context
Name may yet change. Options considered a) Provider b) Context c) Infrastructure d) Framework e) Fabric f) Configuration f) Scope g) account

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Creating a whiteboard template on Space admin section fails:
<img width="1313" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFhZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e495c50e3a6b7ba854b6b0b2a64e4eeb8c63462f/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
The above is fixed.

2 new issues are identified:
1. When trying to query challenge through space fails to be returned (using `lookup` works fine)
<img width="1183" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGJkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c1a253fd26b60cf1128b3e8786d2997c8a4d5ac/image.png" alt="image.png" />
<img width="1789" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9802e13fef02b8255a7b7a8be055262e60039163/image.png" alt="image.png" />
2. When a organization has been used as a host and the space is removed, the organization cannot be removed 
<img width="1551" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG5kQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f364a4b67c820218ce7d0e374ed52d71b1ed502/image.png" alt="image.png" />

3. querying opportunities from space, returns []
<img width="1514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGJnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a22730bacea3bb5bf989ae7d79cead5ca2a2ca7/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Above is fixed.
1 more:
can create challenges with same nameID
<img width="1631" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHJnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20c23a2ba7a2279b908aa79cda576024e36e35cc/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Cannot update preferences on space
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmpnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df17d3a8fd9e9acc91f8a77dd3a1164e0e3c8f24/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@Comoque1 the nameID check should now be working. 

I was not able to replicate the updating of preference issue, it was working fine for me on both space + challenge...

**Comment by Comoque1** [comment]
@techsmyth thanks!
At the moment I cannot test the fix, as the space creation fails with the latest changes: `"message": "Unable to find user with given ID: 5ad6fe60-c91c-4b7e-bbdd-8e48f1bedfbb"`

<img width="1823" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK25oQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd6f742938df3f873ab221a2f8e6cce3ae4fc452/image.png" alt="image.png" />

Regarding the preferences updates - I've managed to update on the default space now. The issue that was experienced was on a new space.

**Comment by techsmyth** [comment]
@Comoque1 I just tried creating a new space with latest without issues, and also preferences on that space. Can you please try with a clean db / restored db?

**Comment by techsmyth** [comment]
@Comoque1 just pushed the fix for the preference update, might also be a bit faster to do the auth reset.

**Comment by Comoque1** [comment]
Thanks @techsmyth !
Now when a GA creates opportunity authorization errors are thrown: new db.
<img width="1456" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzdrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9fe1080869b41e26bca159ad775831488f5a0be/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@Comoque1 fix is pushed...hopefully getting close...

**Comment by Comoque1** [comment]
Above is fixed.
When non space member opens: space dashboard or challenge / opportunities or an opportunity of a public space, auth errors are thrown:

<img width="1448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODdrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7c561e6d6e39761b21bd2de6c8b030423762f67/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Search within space is failing
<img width="1555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG5uQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef158c2e28afeee28f0c62e2d34e67261dd62ce2/image.png" alt="image.png" />
```
query search($searchData: SearchInput!) {
  search(searchData: $searchData) {
    journeyResults {
      id
      score
      terms
      type
      ... on SearchResultSpace {
        ...SearchResultSpace
        __typename
      }
      ... on SearchResultChallenge {
        ...SearchResultChallenge
        __typename
      }
      ... on SearchResultOpportunity {
        ...SearchResultOpportunity
        __typename
      }
      __typename
    }
    journeyResultsCount
    calloutResults {
      id
      score
      terms
      type
      ... on SearchResultCallout {
        ...SearchResultCallout
        __typename
      }
      __typename
    }
    contributorResults {
      id
      score
      terms
      type
      ... on SearchResultUser {
        ...SearchResultUser
        __typename
      }
      ... on SearchResultOrganization {
        ...SearchResultOrganization
        __typename
      }
      __typename
    }
    contributorResultsCount
    contributionResults {
      id
      score
      terms
      type
      ... on SearchResultPost {
        ...SearchResultPost
        __typename
      }
      __typename
    }
    contributionResultsCount
    __typename
  }
}

fragment SearchResultSpace on SearchResultSpace {
  space {
    id
    nameID
    profile {
      id
      displayName
      tagset {
        ...TagsetDetails
        __typename
      }
      tagline
      visuals {
        ...VisualUri
        __typename
      }
      __typename
    }
    context {
      id
      vision
      __typename
    }
    authorization {
      id
      anonymousReadAccess
      __typename
    }
    community {
      id
      myMembershipStatus
      __typename
    }
    account {
      id
      license {
        id
        visibility
        __typename
      }
      __typename
    }
    __typename
  }
  __typename
}

fragment TagsetDetails on Tagset {
  id
  name
  tags
  allowedValues
  type
  __typename
}

fragment VisualUri on Visual {
  id
  uri
  name
  __typename
}

fragment SearchResultChallenge on SearchResultChallenge {
  challenge {
    id
    nameID
    profile {
      id
      displayName
      tagset {
        ...TagsetDetails
        __typename
      }
      tagline
      visuals {
        ...VisualUri
        __typename
      }
      __typename
    }
    account {
      spaceID
      __typename
    }
    context {
      id
      vision
      __typename
    }
    authorization {
      id
      anonymousReadAccess
      __typename
    }
    community {
      id
      myMembershipStatus
      __typename
    }
    __typename
  }
  space {
    id
    nameID
    profile {
      id
      displayName
      tagline
      __typename
    }
    authorization {
      id
      anonymousReadAccess
      __typename
    }
    account {
      id
      license {
        id
        visibility
        __typename
      }
      __typename
    }
    __typename
  }
  __typename
}

fragment SearchResultOpportunity on SearchResultOpportunity {
  opportunity {
    id
    nameID
    profile {
      id
      displayName
      tagset {
        ...TagsetDetails
        __typename
      }
      tagline
      visuals {
        ...VisualUri
        __typename
      }
      __typename
    }
    context {
      id
      vision
      __typename
    }
    authorization {
      id
      anonymousReadAccess
      __typename
    }
    community {
      id
      myMembershipStatus
      __typename
    }
    __typename
  }
  challenge {
    id
    nameID
    profile {
      id
      displayName
      __typename
    }
    authorization {
      id
      anonymousReadAccess
      __typename
    }
    __typename
  }
  space {
    id
    nameID
    profile {
      id
      displayName
      __typename
    }
    account {
      id
      license {
        id
        visibility
        __typename
      }
      __typename
    }
    __typename
  }
  __typename
}

fragment SearchResultCallout on SearchResultCallout {
  callout {
    id
    nameID
    type
    framing {
      id
      __typename
    }
    __typename
  }
  __typename
}

fragment SearchResultUser on SearchResultUser {
  user {
    id
    nameID
    profile {
      displayName
      ...SearchResultProfile
      __typename
    }
    __typename
  }
  __typename
}

fragment SearchResultProfile on Profile {
  id
  description
  location {
    id
    country
    city
    __typename
  }
  tagsets {
    ...TagsetDetails
    __typename
  }
  visual(type: AVATAR) {
    ...VisualUri
    __typename
  }
  __typename
}

fragment SearchResultOrganization on SearchResultOrganization {
  organization {
    id
    nameID
    profile {
      displayName
      ...SearchResultProfile
      __typename
    }
    __typename
  }
  __typename
}

fragment SearchResultPost on SearchResultPost {
  post {
    id
    nameID
    profile {
      displayName
      visual(type: CARD) {
        ...VisualUri
        __typename
      }
      ...SearchResultPostProfile
      __typename
    }
    createdBy {
      id
      profile {
        id
        displayName
        __typename
      }
      __typename
    }
    createdDate
    comments {
      id
      messagesCount
      __typename
    }
    __typename
  }
  ...PostParent
  __typename
}

fragment SearchResultPostProfile on Profile {
  id
  description
  tagset {
    ...TagsetDetails
    __typename
  }
  __typename
}

fragment PostParent on SearchResultPost {
  space {
    id
    nameID
    account {
      id
      license {
        id
        visibility
        __typename
      }
      __typename
    }
    profile {
      id
      displayName
      __typename
    }
    authorization {
      id
      anonymousReadAccess
      __typename
    }
    __typename
  }
  challenge {
    id
    nameID
    profile {
      id
      displayName
      __typename
    }
    authorization {
      id
      anonymousReadAccess
      __typename
    }
    __typename
  }
  opportunity {
    id
    nameID
    profile {
      id
      displayName
      __typename
    }
    authorization {
      id
      anonymousReadAccess
      __typename
    }
    __typename
  }
  callout {
    id
    nameID
    framing {
      profile {
        id
        displayName
        __typename
      }
      __typename
    }
    __typename
  }
  __typename
}
```
```
{
  "searchData": {
    "terms": [
      "Relevant news, research or use cases 📰"
    ],
    "tagsetNames": [
      "skills",
      "keywords"
    ],
    "typesFilter": [
      "space",
      "opportunity",
      "challenge",
      "post",
      "user",
      "organization"
    ],
    "searchInSpaceFilter": "111"
  }
}
```

**Comment by Comoque1** [comment]
Global search doesn't return contributions
<img width="1390" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHZuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f41d2b8e59ad7a526de24e0c3ef0b7c4383093f/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@Comoque1 thanks, good find - just pushed the fix

**Comment by Comoque1** [comment]
@techsmyth thanks, the contributions global search is fixed.
The previous comment is not addressed - search within space is still failing.

**Comment by Comoque1** [comment]
@valentinyanakiev when we have the following setup:
 - Public active space
 - Private challenge
 - Opportunity
 - Space member queries from the **global** search by term, that is contained by all above entities - Space and opportunity are returned - should be only space
 <img width="1553" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUxwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2bcf12f26f1512d69d201c73bd96417d71b2c02/image.png" alt="image.png" />
