### ISSUE TITLE
Default innovation flow

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#3688]
## Description

As a user, by default I want to see an innovation flow that I understand and that inspires me.

## Acceptance criteria
- Title
Default Innovation Flow

- Description
**Explore, Define, Brainstorm, Validate, and Evaluate:** A journey of discovery begins with research and observation. Sharpen your focus by defining the challenge precisely. Ignite creativity through diverse perspectives during brainstorming. Test assumptions, adapt, and assess impact for informed choices. ✨

- Steps:

Explore
🔍 **A journey of discovery!** Gather insights through research and observation. 

Define
🎯 **Sharpen your focus.**  Define the challenge with precision and set a clear direction.

Brainstorm
🎨 **Ignite creativity.** Generate a constellation of ideas, using concepts from diverse perspectives to get inspired.

Validate
🛠️ **Test assumptions.** Build prototypes, seek feedback, and validate your concepts. Adapt based on real-world insights.

Evaluate
✅ **Assess impact, feasibility, and alignment** to make informed choices.

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@SimoneZaza I can work with this. This is I think basically covering 3677?

**Comment by SimoneZaza** [comment]
@techsmyth yes I think it is, thanks! I will close this one.
