### ISSUE TITLE
Update default application form content

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#3690]
## Description

As an admin, I want the application form that is there by default at the creation of a new Journey, to be relevant and inviting. As a S&D team member, I want to have to change and explain as little as possible to new admins. 

## Acceptance criteria

- [ ] Introduction + questions below, none are required
Welcome!
Thank you for expressing interest in joining our community. We would like to learn more about you and how you can contribute. Please take a moment to complete the following application form.

1. What brings you here?
2. What do you hope to gain from being part of this community?
3. How can you contribute to this community?
4. How did you discover this community?

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
<img width="1123" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGJkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8c947ae77d02954339a9f0264986e2bc04f9111/image.png" alt="image.png" />

**Comment by bobbykolev** [comment]
PRs
https://github.com/alkem-io/notifications/pull/303
https://github.com/alkem-io/notifications/pull/304
https://github.com/alkem-io/server/pull/3854
