### ISSUE TITLE
Space Library: default Templates

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#3691]
## Description
As an admin, I want the templates that are there by default at the creation of a new Journey, to be relevant and informative. As a S&D team member, I want to have to change and explain as little as possible to new admins. Currently, the set of default templates in a space are very, **very** outdated.

## Acceptance criteria
All templates mentioned below are currently part of the Innovation Library
- Whiteboard templates:
- [x] Customer Journey (the blue one)
- [x] Empathy Map
- [x] Setting up a new Space
- Post templates:
- [x] Meeting Notes
- [x] Related Initiatives
- [x] Community Needs
- Innovation flows:
- [x] the default flow from #3688
- [x] Key Insights - Brainstorm  - Notes - To Do - Other (template still to be made once the simple set of states w/ description is in)

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 

<img width="1340" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN25kQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23df49d55ee652db324ce3e6bcfc4ed14d4ac262/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@SimoneZaza is there more to do on this? It is basically going to be hard to support whiteboards as part of space library templates until we get the defaults data driven...

**Comment by SimoneZaza** [comment]
@techsmyth it is what it is 🙃 I'll create an epic about making these things data driven to have this tracked somewhere and then this should indeed be it for now. Default callouts etc are part of a different issue.

**Comment by techsmyth** [comment]
ok, then I will put this to QA review...
