### ISSUE TITLE
Default settings for Space/Challenge creation to align with current usage

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#3692]
## Description

As an admin I want to have to change as little as possible
As an Alkemio team member I get frustrated with changing the exact same settings everytime I create a new Space/Challenge for a new community.

## Acceptance criteria

- [ ] Space settings: visibility: Public
- [ ] Challenge: all authorization switches turned on, thus also enabling:
- [ ] Allow contributors to the Challenge to create Opportunities. 
- [ ] Allow contributors to create Callouts. 

Later:
- [ ] Space mode/visibility: Demo (was Active, but nearly every community currently starts as Demo Space)

## Additional Context

Requested by S&D

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@SimoneZaza I have split the demo visibility out as that would impact more items...
