### ISSUE TITLE
BUG: Search returns results from opportunity of private challenge to space member

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3721]
**Describe the bug**

**To Reproduce**
1. Go to localhost
2. Create a Public active space
3. Create a Private challenge
4. Create an opportunity
5. **Space member** queries from the global search and space search by term, that is contained by all above entities - Space and opportunity are returned - should be only space. For space search 0 results must be returned
<img width="1547" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2ZyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b893ceaa94989e1e608d09be3a1136d4220b6f51/image.png" alt="image.png" />

**Expected behavior**
When member of space (only) search by term that is containe in private challenge and its opportunity - 0 data should be returned for them.

**Comment by techsmyth** [comment]
@Comoque1 will be addressed as part of subspaces change
