### ISSUE TITLE
Search ingestion to use spaces

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3724]
## Description

As a client I want the api to work with finding relevant spaces

## Acceptance criteria

- [x] Search DB: queries updated to use the new structure
- [x] Search elastic: to have new ingestion schema

**Comment by hero101** [comment]
Closing this story with PR https://github.com/alkem-io/server/pull/3819 - more specifically e8efe5113d2f4a0918638df9b8d0beb01bf07e39
