### ISSUE TITLE
Default Active state of an InnovationFlow template

### ISSUE THREAD

**Issue by ccanos** [cherrytwist/Server#3735]
## Description

As an Alkemio templates creator I want to be able to set the default active state when I'm creating an InnovationFlow template.

## Acceptance criteria

- [ ] InnovationFlowTemplate has a `defaultState` or `defaultActiveState` field.
- [ ] That default state becomes the active state when the InnovationFlow is used in a ch/opp
- [ ] `CreateInnovationFlowTemplateOnTemplatesSetInput` and `UpdateInnovationFlowTemplateInput` are also updated accordingly.
- [ ] Server validates that the default active state is one of the IF states.
- [ ] Client is updated according to the designs (Most of the UI work is done, just update the queries and mutations, see branch `server-3735`)

## Additional Context
InnovationFlows, when they are in use, they have associated a tagset (the profile of the ch/opp they are used by) that stores the  current state. There's no such tagset for `innovation_flow_templates`. I suggest adding a field to InnovationFlowTemplate called `defaultState: String` and a column to the table innovation_flow_template.

Screen shots / UX designs / data that are relevant.
<img width="627" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1AxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad313bea8cd866e04466afaf860608db57739d12/image.png" alt="image.png" />

https://www.figma.com/file/SKe3YDHm3Rs7yzuDohHSPK/Innovation-flow-design?type=design&node-id=214-4084&mode=design&t=YP4nZ9QS5lfEHnxi-0

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by SimoneZaza** [comment]
Designs were there only to support this functionality, but the UX is better without having this, so fine as is right now :)
