### ISSUE TITLE
BUG: User can update innovation flow template display name to existing one

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3737]
**Describe the bug**

**To Reproduce**
1. Go to https://dev-alkem.io/graphql
2. Create innovation flow template 1 with display name: "Test display name"
3. Create innovation flow template 2 with display name: "Test display name2"
4. Update the second innovation flow **template** display name to: "Test display name" - the request succeeds and there is no validation
<img width="1386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFQyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f00002697d7fe2af260da0f3d313336c799d9547/image.png" alt="image.png" />

**Expected behavior**
Validation is applied and different innovation flow templates with the same display name cannot be created.

**Comment by techsmyth** [comment]
Not for now, and it is also not an issue from business logic - just what users see + they can update it again to something else.
