### ISSUE TITLE
BUG: callout template framing profile not returning url

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3756]
**Describe the bug**
The logic for returning a url on a callout framing profile that was part of a callout template was missing
The url that was returned for templates in a space library was just the space URL, not to the space settings

**To Reproduce**
1. Create a callout template using the "save as template" option (note: enable this flag via platform setting on space)
2. Go to gragphql, and try to retrieve the url for the framing in the callout template i.e. platform.innovationLibrary.calloutTemplates.framing.profile.url

**Expected behavior**
The logic should handle callout template framing urls
The url returned for templates in the space library should be to the library admin

**Comment by valentinyanakiev** [comment]
@techsmyth please fill in the necessary fields in the bug so that all team members can understand / review it (we have 2 new team members).

**Comment by Comoque1** [comment]
@techsmyth , the framing profile returns URL now.
The issue is experienced, when try to query the whiteboard URL considering the above conditions:
<img width="1396" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGdZQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc9bc7c27d22abc9ccb4988c0819ee0aa7f72664/image.png" alt="image.png" />

```
query {
  lookup {
    calloutTemplate(ID: "bfc9084f-44d3-42f9-a320-866e91b88bda") {
      framing {
        profile {
          url
        }
        whiteboard {
          profile {
            url
          }
        }
      }
    }
  }
}

```
Do you want me to raise a separate bug about it, or it could be addressed as part of this one?

**Comment by techsmyth** [comment]
I think there is still a bug open for this scenario, I had raised a separate one as need to first fix framing. Sent from my iPhoneOn 27 Mar 2024, at 20:24, Evgeni Dimitrov ***@***.***> wrote:﻿
@techsmyth , the framing profile returns URL now.
The issue is experienced, when try to query the whiteboard URL considering the above conditions:

query {
  lookup {
    calloutTemplate(ID: "bfc9084f-44d3-42f9-a320-866e91b88bda") {
      framing {
        profile {
          url
        }
        whiteboard {
          profile {
            url
          }
        }
      }
    }
  }
}


Do you want me to raise a separate bug about it, or it could be addressed as part of this one?
