### ISSUE TITLE
BUG:  server crash when creating post with existing nameID

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3779]
**Describe the bug**
Create a post on a callout of type "POST_COLLECTION" using the payload below:

```
{
  "data": {
    "calloutID": "b7416aa9-4de8-4fb8-9af0-b4db2c874597",
    "post": {
      "profileData": {
          "displayName": "test post 2",
          "description": "this is a very good post"
      },
      "type": "bla",
      "nameID": "test"
    }
  }
}
```

Replacing calloutID value with your callout ID

Run the same mutation again, the server crashes:
<img width="1215" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmNpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae77bbb022a75347aed274cb619c11300e12eb1f/image.png" alt="image.png" />

**Expected behavior**
The server should not crash.

**Comment by Comoque1** [comment]
Tested OK on ACC env.
