### ISSUE TITLE
BUG: Errors are not being cascaded

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3780]
**Describe the bug**
An exception inside the server is not being handled + fed back to users. For example

<img width="984" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFFpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86736073073192fb0cc200dfec31ab32d94a610c/image.png" alt="image.png" />

results in
<img width="939" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed9551624d1589dea0e549913f64f61edc2caf3d/image.png" alt="image.png" />

**To Reproduce**
1. Log out
2. try to access the default me query

**Expected behavior**
The error should be returned

**Screenshots**
It looks like Graphql is not detecting an error has happened and is trying to proceed + then finding no data.

The only code that I see that has changed since 0.72 is the following:
<img width="1109" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE1pQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f697ec64ba4c52ab08899d29dc61764c28efda5/image.png" alt="image.png" />

<img width="1098" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38498edc24010bec093199361e32cc7344e5379e/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
@techsmyth , previously the error code for sending message to closed callout was `CALLOUT_CLOSED`  and now is `INTERNAL_SERVER_ERROR`.
Is this expected?
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGdvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--978c0503d5bb218900120dbc275f221a2f725de5/image.png" alt="image.png" />

**Comment by hero101** [comment]
@Comoque1 No. There must not be any changes.
I have taken over the task.

**Comment by hero101** [comment]
Please retest.
