### ISSUE TITLE
BUG: unable to do platform reset authorization

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3782]
**Describe the bug**
Mutation to do platform reset auth is failing

**To Reproduce**
1. Go to graphql playground
2. Run the mutation to reset auth on platform, it fails

**Expected behavior**
Mutation should pass

**Screenshots**
Issue is that the privilege being checked is not granted i.e. AUTHORIZATION_RESET

<img width="1767" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGNpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0b7bb54571ac308897dd9923160fb5694fc4817/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Works on DEV env.
<img width="1795" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0FqQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad22bf724816f4c4faa8c38d96829bf6140d6f52/image.png" alt="image.png" />
