### ISSUE TITLE
BUG: ChatGuidance persona not returning an answer

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#3807]
**Describe the bug**

**To Reproduce**
1. Create a VP with ChatGuidance engine on https://alkem.io
2. Create a VC using that persona
3. Add the VC to a community
4. Try to use it
5. You get an error

**Expected behavior**
You get a response from the engine

**Comment by Comoque1** [comment]
Works on ACC env.
<img width="1145" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkZyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ccb7e527d36c9537b375e9d7b60d9cfda0c02dc/image.png" alt="image.png" />
