### ISSUE TITLE
BUG: "Authorization: no definition provided" is thrown when try to query SUBSPACES account defaults

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3826]
**Describe the bug**

**To Reproduce**
1. Go to local or dev env graphql
2. Perform the following query:
```
query{
  space(ID:"public-space"){
    subspaces{
      account{id defaults{id}}
    }
  }
}
```
3. Error is thrown: `"message": "Authorization: no definition provided",`
<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDFkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--869e40a778f5b7821e138b5ecce44fd41d4db4cd/image.png" alt="image.png" />

**Expected behavior**
Query returns results successfully.

**Comment by alstojanovic** [comment]
In authorization.rule.agent.privilege when checking isAccessGranted for defaults, the account authorization isn't loaded.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
<img width="1229" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2lpQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7af54350f4a9be6001a08bd6069bdd30fb641b0/image.png" alt="image.png" />
