### ISSUE TITLE
BUG: Server responding with 502 right after Whiteboard creation

### ISSUE THREAD

**Issue by bobbykolev** [cherrytwist/Server#3827]
**Describe the bug**
When creating Whiteboard on Dev, the server returns 502 when trying to retrieve the whiteboard data. See log below.

**To Reproduce**

1. Go to subspace;
2. Click on add collaboration tool;
3. Try to create a Whiteboard;
4. See the error on the Network;

**Expected behavior**
No server errors. Whiteboard data successfully retrieved.

**Screenshots**

**Additional context**
Query:
`{"operationName":"WhiteboardWithContent","variables":{"whiteboardId":"fd359ee0-e341-45fc-a607-b850e570a7c5"},"query":"query WhiteboardWithContent($whiteboardId: UUID!) {\n  lookup {\n    whiteboard(ID: $whiteboardId) {\n      ...WhiteboardDetails\n      ...WhiteboardContent\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment WhiteboardDetails on Whiteboard {\n  id\n  nameID\n  createdDate\n  profile {\n    ...WhiteboardProfile\n    __typename\n  }\n  authorization {\n    id\n    myPrivileges\n    anonymousReadAccess\n    __typename\n  }\n  contentUpdatePolicy\n  createdBy {\n    id\n    profile {\n      id\n      displayName\n      url\n      location {\n        id\n        country\n        city\n        __typename\n      }\n      avatar: visual(type: AVATAR) {\n        id\n        uri\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment WhiteboardProfile on Profile {\n  id\n  url\n  displayName\n  description\n  visual(type: CARD) {\n    ...VisualFull\n    __typename\n  }\n  preview: visual(type: BANNER) {\n    ...VisualFull\n    __typename\n  }\n  tagset {\n    ...TagsetDetails\n    __typename\n  }\n  storageBucket {\n    id\n    __typename\n  }\n  __typename\n}\n\nfragment VisualFull on Visual {\n  id\n  uri\n  name\n  allowedTypes\n  aspectRatio\n  maxHeight\n  maxWidth\n  minHeight\n  minWidth\n  alternativeText\n  __typename\n}\n\nfragment TagsetDetails on Tagset {\n  id\n  name\n  tags\n  allowedValues\n  type\n  __typename\n}\n\nfragment WhiteboardContent on Whiteboard {\n  id\n  content\n  __typename\n}"}`

Local error stack trace
`C:\Users\Vision\Downloads\work\Alkemio\project\server\src\common\exceptions\base.exception.ts:15 
    super(message, {
    ^
EntityNotFoundException: Unable to find space for whiteboard: f7147eef-d007-4656-bf60-a76a146bba18
    at new BaseException (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\common\exceptions\base.exception.ts:15:5)
    at new EntityNotFoundException (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\common\exceptions\entity.not.found.exception.ts:7:5)
    at CommunityResolverService.getCommunityFromWhiteboardOrFail (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\services\infrastructure\entity-resolver\community.resolver.service.ts:175:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WhiteboardService.isMultiUser (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\domain\common\whiteboard\whiteboard.service.ts:225:7)
    at Socket.<anonymous> (C:\Users\Vision\Downloads\work\Alkemio\project\server\src\services\external\excalidraw-backend\excalidraw.server.ts:230:12)`

**Areas that will be affected as part of the fix**

**Comment by Comoque1** [comment]
The issue is not reproducible on DEV env. anymore.
