### ISSUE TITLE
BUG: Non space member gets privileges [ ] when query private space

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3831]
**Describe the bug**

**To Reproduce**
1. Go to https://dev-alkem.io/graphql
2. Authenticate with user that is not member of a Private space and perform the following query to the space
```
query{
  space(ID:"space3"){
    authorization{
      myPrivileges
    }
  }
}
```
3. Empty array is returned instead of "READ" privileges
<img width="1561" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFZlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36f776331708e2993a6bae50064d1fc6dad0f17c/image.png" alt="image.png" />

**Expected behavior**
"READ" privileges are returned.

**Comment by alstojanovic** [comment]
@techsmyth can you confirm that this is the expected behaviour? From the code we are adding READ privilege only for member users and it seems that [] should be returned for non members and unauthenticated users.

**Comment by techsmyth** [comment]
@alstojanovic non-space members absolutely do NOT have READ privilege on the private space. They do have READ privilege on the profile of the Space, and the Context - that is public. It is not as formalized / enforced as it should be - best would be to add an extra privilege e.g. READ_PROFILE, that is what both non-authenticated + non-members of a private space get.

**Comment by alstojanovic** [comment]
ok, that's what the code says but since a lot of code has been moved around I wanted to confirm this. Indeed, we probably should have READ_PROFILE/CONTEXT rules if we wanted to have it strict like that. Currently we use the anonymousReadAccess flag set to true to enable reading profile and context right?

@Comoque1 I'm confirming it is safe to close this one.

**Comment by techsmyth** [comment]
@alstojanovic raised: https://github.com/alkem-io/server/issues/3839
