### ISSUE TITLE
Account host: also allow Users

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3900]
## Description

As a user of Alkemio I want to be able to have my own Space

## Acceptance criteria

- [ ] Account host to allow being a User as well as an Organization

## Areas that will be affected 
test suites
client to also allow specifying a User

**Comment by techsmyth** [comment]
@SimoneZaza we need to think through the implications of this from the user interaction. Are there certain restrictions that come with Users as hosts? Do we need verification? Can an account be re-assigned from an Org to a User?

**Comment by bobbykolev** [comment]
What do you think of restricting the free spaces to use a default organization?
