### ISSUE TITLE
BUG: Space Admin has admin privilege on Platform level

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3906]
**Describe the bug**

**To Reproduce**
1. Go to https://acc-alkem.io/graphql
2. Make sure you are authenticated with Space admin and not GA or GSA
3. Run the following query
```
query {
  platform {
    authorization {
      myPrivileges
    }
  }
}

```
3. User get "admin" privilege on platform level
<img width="1426" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVBOQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--782226e1fa88d08a8ea0f3895362a9503ba547d5/image.png" alt="image.png" />

**Expected behavior**
Space admin doesn't have "admin" privilege on platform level.

**Additional context**
The server doesn't allow the user to reset policies of other spaces, change space / account platform settings or create innovations packs.

**Comment by techsmyth** [comment]
@Comoque1 good catch - this is I think a legacy assignment that was done to allow the space admin to access the admin section of the site. It can likely go, once the PR related to the path changes are done: https://github.com/alkem-io/client-web/pull/6159

@me-andre how is it working with settings on a user / org? I can imagine there is the same issue re paths there...

**Comment by valentinyanakiev** [comment]
Verified locally, no longer the case. With a user that is SPACE_ADMIN on one space only, and no PLATFORM roles, I have:

```gql
query {
  platform {
    authorization {
      myPrivileges
    }
  }
}
```

```json
{
  "data": {
    "platform": {
      "authorization": {
        "myPrivileges": [
          "READ_USERS",
          "CREATE_ORGANIZATION",
          "ACCESS_INTERACTIVE_GUIDANCE"
        ]
      }
    }
  }
}
```
