### ISSUE TITLE
Notifications are triggered for any change to a global role

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3917]
## Description

As a GA I have to be aware of any change on global roles.

## Acceptance criteria

- [ ] Notifications are triggered for any change to a global role, or for the direct addition of any credentials (which is a global action):
![image](https://github.com/alkem-io/server/assets/30729240/3928fa67-d268-4661-a3b0-577d86a05984)

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@Comoque1 maybe am missing something but just in case: did you have the latest notifications service running?
