### ISSUE TITLE
[Create Space] Notification on space creation

### ISSUE THREAD

**Issue by bobbykolev** [cherrytwist/Server#3932]
## Description

As a License Manager
I want to receive a notification on Space Creation
So that I can track, review, moderate, and monitor the newly created Spaces.

## Acceptance criteria

- [ ] When a **top level** space is created, send a notification to all **License Managers** (= new platform role, #3884) with:
- Date/time (also visible from when the email was sent of course, but adding this in the actual notification would be nice)
- Space nameid / link to space
- host
- space plan (free/plus/premium/enterprise(?))

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by SimoneZaza** [comment]
@techsmyth do you want GA's to also receive this notification?

**Comment by techsmyth** [comment]
@SimoneZaza not needed for GA I think, if I want to get it then I can also assign to LicenseMgr role

**Comment by EmiliaPavlova** [comment]
The space plan is omitted in the notification because getting it creates a circular dependency and needs code refactoring that will take place later in time.

**Comment by hero101** [comment]
@techsmyth should this be in the next release?

**Comment by Comoque1** [comment]
Tested ok on ACC env.
