### ISSUE TITLE
BUG: user cannot be admin of more than one subspace

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3934]
**Describe the bug**
The logic for assigning subspace admins is not checking if a user already has the subspace admin credential

**To Reproduce**
1. Create a space
2. Create a subspace
3. Create another subspace in the root space

**Expected behavior**
The logic to add / remove subspace admin credential to check if one is already assigned + not assign a second; also on removing the role to not remove if still has a role elsewhere

**Comment by Comoque1** [comment]
Tested OK on ACC. env for all subspace levels.
