### ISSUE TITLE
BUG: When user accepts invitation from subspace on space level and after that on subspace, server crash

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#3963]
**Describe the bug**

**To Reproduce**
1. Go to localhost:3000
2. Create a private space
3. Create a private challenge
4. Send invitation to existing user from subspace admin
5. From My Dashboard lock select the open invitation
<img width="1358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3Y3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06cd58ec007af630213df12aaaa042e1665d6454/image.png" alt="image.png" />
 

6.  Click on the space card
<img width="985" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFA3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43ad36ce067955de7aaac5acc0f81ade9e3d7e4d/image.png" alt="image.png" />

7. Click on Join button - user becomes a member
<img width="1112" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFQ3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26290842f60651e5aeb72498fcf166b93a5fd264/image.png" alt="image.png" />

7.  Go to subspaces tab
<img width="863" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdy83QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e79091d0ddeb17b667c2b49c35cac675cf8c100/image.png" alt="image.png" />

8.  Open the subspace and click on Subspace card
<img width="897" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFg3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc0c0d744b2b9e76f75de7baad3c2666d0f2d1b4/image.png" alt="image.png" />

9. User is presented with "Accept invitation" button on subspace level
<img width="1049" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGI3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da708fcc1472a50f6435a20b04aa6b1e31764cd0/image.png" alt="image.png" />

10. Click on Accept invitation button and on join button of the appeared dialog
<img width="1002" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGY3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e54468acd9820d97c7e068f36dd44c003944509/image.png" alt="image.png" />

11. Server crash
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGo3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26920b8d656b3b176d7737dcab1c6a55ea1f644b/image.png" alt="image.png" />

**Expected behavior**
Server doesn't crash.

**Comment by SimoneZaza** [comment]
@techsmyth this is the one I was referring to. It is related to another bug - the invitation shouldn't bring the user to the Space in the first place. But even if that is fixed, when people navigate to the Space first to see what this is all about, the bug would still be there.
