### ISSUE TITLE
VC architecture

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#4010]
## Description
As a Developer
I would like to understand what parameters are optional and which are mandatory
for the VC flow so that I don't need to write hacks.

## Acceptance criteria

- [ ] We have a VC / AI Persona architecture that isolates knowledge of specific AI services from the collaboration server domain model
- [ ] top level virtualContributors query remains as is
- [ ] additional virtualContributors query under platform.library that shows all VCs that have are a) Public b) ListedInStore

## Additional Context
These screens imply implicit selection of the engine:

<img width="1573" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20d9f878e8ec090d666aceead43dca788738727e/image.png" alt="image.png" />

**Comment by valentinyanakiev** [comment]
@valeksiev 2nd and 3rd item in the AC are not met

**Comment by techsmyth** [comment]
@valeksiev @valentinyanakiev AC were out of date, we had discussed + chosen a different option. Updated...

**Comment by Comoque1** [comment]
When querying aiPersona data through a VC from top level query, errors are returned:
```
query {
  virtualContributors {
    account {
      activeSubscription {
        expires
        name
      }
      license {
        id
        visibility
      }
    }
    aiPersona {
      bodyOfKnowledgeType
      dataAccessMode
      description
      interactionModes
    }
    searchVisibility
    listedInStore
    profile {
      displayName
    }
  }
}
```

<img width="1459" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXVNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46cda5ce2e8c04c8ba56d88501aff27d64fdf43f/image.png" alt="image.png" />

The same query when used through platform.library, works fine.

**Comment by Comoque1** [comment]
Raised a separate bug: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/4149
