### ISSUE TITLE
Allow platform admins to update Virtual Contributor BoK

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#4011]
## Description

As an Alkemio User
I would like to be able to update BoK of my VCs
so that I can manage my data / IP efficiently.

## Acceptance criteria

- [ ] Update mutation of VC working on the server for all BoK fields
- [ ] Client updated to be able to update the BoK
- [ ] EXPERT engine re-ingesting on updated BoK

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@valentinyanakiev I invite a BoK as a person, so I would find it very strange if all of a sudden the BoK behind the VC is changed. This needs discussion.
