### ISSUE TITLE
BUG: When user, who create free space is deleted, error is thrown on Admin / Spaces section

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4023]
**Describe the bug**

**To Reproduce**
1. Go to alkemio
2. Add a user as Beta tester
3. Create a space with it
4. Delete the user
5. Navigate to http://localhost:3000/admin/spaces - error is thrown: `"message": "Unable to find Host for account with ID: 48276e0b-b207-44af-98e7-31e1bb30714d",`
<img width="1348" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEF1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e37017901fdfed55d1e5bc8d369c7331605a36b5/image.png" alt="image.png" />

**Expected behavior**
TBD

**Additional context**
The impacted ares could be more.
i.e. Activity logs

**Areas that will be affected as part of the fix**
_Optional, to be added by developer if relevant_

**Comment by techsmyth** [comment]
Please retest this with work on multiple spaces to an account

**Comment by Comoque1** [comment]
The flow cannot be reproduced anymore, as a user whose account has a space cannot be removed.
<img width="1702" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0I4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7edc9203a6540b6299dab42d189f9f03aae91ccf/image.png" alt="image.png" />
