### ISSUE TITLE
Remove knowledge of space type from community

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4070]
## Description

As a developer I want maintainable code

## Acceptance criteria

- [ ] Remove the field spaceType from Community entity

## Additional Context
This will be a deep enough change as this field is used in multiple places

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by hero101** [comment]
Run the `journey` suit. Only one test fails, but most probably is not caused by this change
![image](https://github.com/alkem-io/server/assets/7901834/ec657071-410d-480a-93cf-421775e79d98)
