### ISSUE TITLE
BUG: Internal Server error Unable to find Space with ID on L2 Subspace Settings

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#4073]
**Describe the bug**
When I open the settings of a level 2 subspace (former opportunity) I get the following error:
<img width="1554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelJMQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51da56410fa5f923ce99105cb0f0289b647e47a5/image.png" alt="image.png" />
I've checked and get the same error in all 3 l2subspaces that I checked, which are in Building the A-team and Working Challenge Centric

**To Reproduce**
1. Go to a level 2 subspace
2. Click on settings

**Expected behavior**
No error

**Additional context**

**Areas that will be affected as part of the fix**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Duplicate to this one: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6191.

But let's keep the one reported by you, as it has better description :)

**Comment by Comoque1** [comment]
Tested OK on DEV env.
