### ISSUE TITLE
Global support to have edit privileges for organizations

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#4079]
**Describe the bug**
As Global Support, I want to be able to edit organization profiles. 

**To Reproduce**
1. As global support, go to platform administration
2. Search for an organization profile
3. Try to enter the settings
4. not able

**Expected behavior**
Global Support to have edit privileges

## Screenshots

<img width="1778" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFpOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--736c496da636743718155ce5d027999873384015/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Tested OK on dev env.
