### ISSUE TITLE
BUG: Base license plan can be deleted

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4109]
**Describe the bug**

**To Reproduce**
1. Go to http://localhost:3000/graphql
2. Delete a base license plan
3. Query platform licenses: error is thrown: `"message": "Unable to find base plan: 97f798ed-254a-4a31-a2c4-89a7e344f7ff",`
<img width="1636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0JyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31d41203c11dd58c5d38a08b23690fafdd44962d/image.png" alt="image.png" />

**Expected behavior**
Or should not be able to delete a plan, or the querying the plans should return data after a plan is removed.

**Comment by techsmyth** [comment]
Field is no longer present so can be closed
