### ISSUE TITLE
VC gives OpenAI answers

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#4110]
## Description

As a user, I want to ask my VC questions based on my content. However, it now gives me answers based on OpenAI but says that the source is the Subspace. Even with my empty subspace, the VC gives me answers. This scares me as a user and doesn't allow me to gain the right answers.

I want my VC to give me answers based on its data, or explicitly tell me that it is based on external sources. 

## Acceptance criteria
- [ ] The balance should be more on the context provided
- [ ] Flag from the reply stating if response is largely based on generic knowledge

## Additional Context

This VC is based on one document Marketing Assignment informatie document. However when I ask to give me a summary of the information in that document. This is the answer.

Hmm, I am not sure what specific information you are referring to in the 'Marketing Assignment informatie document'. However, as a Virtual Contributor, I can tell you that it is possible to use information from external documents to inform your marketing strategy. It is important to ensure that the information is relevant, accurate, and up-to-date. When using external information, it is also important to properly cite your sources and avoid plagiarism. 

Another example:
VC who is trained on the data by mazzucato
<img width="1520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUJ4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b41346f01b612554c0b0705a666449e1b55d8c7d/image.png" alt="image.png" />

a vc trained on totally different data 
<img width="1584" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXR4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f115e56fb66940e03a832b4e1d02bccc65a35a6/msedge_Egswe8Ub6m.png" alt="msedge_Egswe8Ub6m.png" />

an empty vc trained on zero data
<img width="1590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWh4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f66b331d4b6fe1d1f004c4404bd7faf62bffd209/msedge_4MrU7lXdhf.png" alt="msedge_4MrU7lXdhf.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by larssondenise** [comment]
@techsmyth

**Comment by valentinyanakiev** [comment]
@larssondenise I believe we need some educational materials about what is really expected from GenAI solution such as OpenAI. It has vast array of knowledge and I would not be surprised if book A, B and C are already ingested there. It has to be really specific, unique knowledge to make the answer reasonably different.  I agree that the references could be way better - we show the most relevant sources, but _most_ relevant does not really equate to _relevant_

**Comment by larssondenise** [comment]
@valentinyanakiev not quite sure what you mean... let's have a chat when you're back!
