### ISSUE TITLE
BUG: Search in Space - Whiteboard not in result

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4114]
**Describe the bug**
Searching in a space on the title of a whiteboard is not returning the whiteboard

**To Reproduce**
1. Go to https://alkem.io/building-alkemio-org
2. Search within the space on "VC Roadmap" 
3. There are no matches under callouts
I would expect the following callout to be returned: https://alkem.io/building-alkemio-org/challenges/devprodoffsitejune202/collaboration/vcroadmap

**Expected behavior**
the following callout to be returned: https://alkem.io/building-alkemio-org/challenges/devprodoffsitejune202/collaboration/vcroadmap

**Additional context**
Whiteboards and Posts won't show when searching within the bound of the root Space, because they are ingested with the Space ID of their immidiate Space, and not the root Space.
The result is displayed when you search globally.

**Areas that will be affected as part of the fix**
alkemio-server -> `SearchIngestService`

**Comment by hero101** [comment]
## Verified
It turns out that Whiteboards and Posts won't show when searching within the bound of the root Space, because they are ingested with the Space ID of their immidiate Space, and not the root Space.

**The result is displayed when you search globally.**

**Comment by bobbykolev** [comment]
verified on acc, whiteboards matching the search criteria are returned. Let us know if specific regression testing is required, please.

<img width="415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3k0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a792a8937b7666bf4454d822e6de91cb800cac47/image.png" alt="image.png" />
