### ISSUE TITLE
Make nameID unique inside a Contributor

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#4126]
## Description

As a User
I would like to have error-free experience in my flows
so that I can trust the application with my work.

## Acceptance criteria

- [ ] Looking up contributor across all contributor types should only work with UUID

## Additional Context
Looking up VC/User/Org by nameID is only when the type is exactly know

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
why is it needed to be unique across all contributor types?
