### ISSUE TITLE
Allow VC provider to trigger a refresh of knowledge

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4150]
## Description

As a VC provider I want to be able to explicitly control when I publish a the knowledge behind a VC

## Acceptance criteria

- [ ] Mutation added that triggers a re-publish on a particular VC. The mutation in the case of Alkemio Expert services will then trigger a re-ingesting of the knowledge space.

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on ACC env.
