### ISSUE TITLE
BUG: session extend messages + lost capability

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4160]
**Describe the bug**
IN local development, there are non-stop session extend messages:
<img width="1272" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFdXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9fd8330102371df2ce8f5c2da6d54cd1d17a96a/image.png" alt="image.png" />

Concern is that session extensions have been lost for a while now. 
Also get this message all the time in error logs:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXVnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--260e418c910af9c5f5f915f438310c8204ab8d10/image.png" alt="image.png" />

Overall makes server development a bit less effective

**To Reproduce**
1. Set up for local development

**Expected behavior**
Sessions are extended?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected as part of the fix**
_Optional, to be added by developer if relevant_

**Comment by hero101** [comment]
Session extend has been disabled on the cloud for a couple of months now, due to that capability not working at all on Orys side.
What I would suggest is to
1. Disable the feature by default.
2. Recheck if it has been fixed
3. Raise a github issue if still not working

**Comment by techsmyth** [comment]
@me-andre on my local dev env I am still getting the session extend storm happening: 

![image](https://github.com/user-attachments/assets/6382a67f-8b8c-42ba-928c-32d11ef7cc7a)

**Comment by techsmyth** [comment]
@valentinyanakiev when this happens locally, I also nearly always see the connection to rabbit mq being dropped. Could this also be what is triggering the dropped rabbitmq connections on production?
