### ISSUE TITLE
BUG: On a VC / settings / settings page when ` Include in public selection lists` flag is on, the VC is considering it, no matter the Visibility state

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4169]
**Describe the bug**

**To Reproduce**

1. Go to http://localhost:3000/vc/music-public-not-in-libra/settings/settings or a vc settings page
2. Make the VC public
3. Set the flag: `Include in public selection lists`: true
4. Make the VC `hidden` or `private`
<img width="1050" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9fc9af3c890bc3c84ec02be0052697e7860e8d8/image.png" alt="image.png" />

5. Run the query: 
```
query{
  platform{
    library{
      virtualContributors{
        searchVisibility
        listedInStore
        profile{
          displayName
        }
      }
    }
  }
}
```
6. The VC is displayed in the Library list:
<img width="1240" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3laQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34fa10905423bcae7b79725ba0a5049a4c68f7d4/image.png" alt="image.png" />

**Expected behavior**
When the Visibility is different from `Public`, `listedInStore` must always be false

**Comment by bobbykolev** [comment]
I'm applying a client-side filtering for the Library VC. The client will expose only Public VCs from the library.

The switch for listing in the library (n VC settings) will remain unchanged for now. We can further refine it's UX.

**Comment by Comoque1** [comment]
Reopening the bug, as this should be handled on server level and transferring it to server repository.
