### ISSUE TITLE
BUG: Creating a VC with a normal user (BETA_TESTER, no global admin privileges) doesn't give him permissions to edit it.

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#4188]
**Describe the bug**
Creating a VC with a normal user (BETA_TESTER, no global admin privileges) doesn't give him permissions to edit it.

**To Reproduce**

1. Go to acc env
2. Register new user
3. Create a premium space
4. Create a VC
5. Go to the VC page
6. You don't have edit rights

**Expected behavior**
You should have edit rights

<img width="1452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5affdddb0d487143bb12df8565b12833bf784f53/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
Moved to server repo as it is an auth issue: resetting auth on account  + then the VC auth rules are properly setup. They are not when newly created.
