### ISSUE TITLE
BUG: Declining an invitation on Space leaves it in Open State

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#4195]
**Describe the bug**
 Declining an invitation on Space leaves it in Open State

**To Reproduce**

1. Go to https://acc-alkem.io/test-vc-space-ingest/settings/community
2. Invite `vc-test-create-flow`
3. You get an error

OR

1. Create a space
2. Create a VC
3. Make the VC listable
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzJpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ba34e76891bed54d4182c01817eed90dbfb7f60/image.png" alt="image.png" />
4. Go to another space as GA (should have the VC feature enabled)
5. Invite the VC
6. Go to the VC membership, decline the invite
7. Re-invite the VC
8. You get an error that there is an open invitation 

**Expected behavior**
When an invitation is declined, a new invitation to the same community should be possible.

**Screenshots**
<img width="870" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK21pQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da18b9a5fe550164053d63befe6d1da5a13ee699/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@valentinyanakiev the description talks about application + invitation: which is it?

**Comment by techsmyth** [comment]
@Comoque1 just tried this invite - decline flow for both user + VC, and it works fine **once** the inviting admin has archived the existing invitation. Please double check...

**Comment by Comoque1** [comment]
@techsmyth , correct, if the previous invitation is not archived, new one to the same VC fails, which is expected behavior.
