### ISSUE TITLE
BUG: When the host of a VC is Organization, its admins can't accept external invites to the VC

### ISSUE THREAD

**Issue by bobbykolev** [cherrytwist/Server#4203]
**Describe the bug**
When the host of a VC is an Organization, its admins can't accept external invites to the VC. Note that they receive a notification and the invites are present on their dashboards. On accept an INTERNAL SERVE ERROR is thrown.

**To Reproduce**

1. Invite an external VC hosted by an organization.
2. As an admin of the organization, go to your dashboard and see the invite.
3. Click on Accept.
4. See the error

**Expected behavior**
The admin of org should be able to accept the invite successfully.

**Screenshots**
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXFvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d2cccace0e749125379e6c06e83d9c5760473dd/Schermafbeelding%202024-07-02%20om%2010.48.06.png" alt="Schermafbeelding 2024-07-02 om 10.48.06.png" />

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Tested OK on DEV env.
