### ISSUE TITLE
BUG: Error assigning VC to member role. 

### ISSUE THREAD

**Issue by ccanos** [cherrytwist/Server#4213]
**Describe the bug**

In acceptance, create a new VirtualContributor, error is thrown when assigning that VC as lead of the BoK subspace.

```
mutation AddVirtualContributorToCommunity(
  $communityId: UUID!
  $virtualContributorId: UUID_NAMEID!
) {
  assignCommunityRoleToVirtual(
    roleData: {
      communityID: $communityId
      role: MEMBER
      virtualContributorID: $virtualContributorId
    }
  ) {
    id
    __typename
  }
}
{
  "communityId": "0eb02155-b938-45a4-85de-341ff7ead93e",
  "virtualContributorId": "2a20f462-f651-4e51-a998-6f3fe6d93a27"
}
```

```
stacktrace":[9 items
0:"EntityNotFoundException: Unable to find space for community: 028d191b-e47e-43ff-93f2-95b386477a00"
1:" at new BaseException (/usr/src/app/dist/common/exceptions/base.exception.js:8:9)"
2:" at new EntityNotFoundException (/usr/src/app/dist/common/exceptions/entity.not.found.exception.js:8:9)"
3:" at CommunityResolverService.getSpaceForCommunityOrFail (/usr/src/app/dist/services/infrastructure/entity-resolver/community.resolver.service.js:212:19)"
4:" at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
5:" at async CommunityEventsService.processCommunityNewMemberEvents (/usr/src/app/dist/domain/community/community/community.service.events.js:41:23)"
6:" at async CommunityService.contributorAddedToRole (/usr/src/app/dist/domain/community/community/community.service.js:367:21)"
7:" at async CommunityService.assignVirtualToRole (/usr/src/app/dist/domain/community/community/community.service.js:382:9)"
8:" at async CommunityResolverMutations.assignCommunityRoleToVirtual (/usr/src/app/dist/domain/community/community/community.resolver.mutations.js:129:9)"
```

The problem is caused by a mistake in these changes:
https://github.com/alkem-io/server/pull/4197/files#diff-0ee7cbe3862b3bdf48fcbd97ee7136fea162b7db7320372b7f32c859413d33b5
File src/domain/community/community/community.service.events.ts:53

`getSpaceForCommunityOrFail(spaceID);` expects a `communityID`

Can be fixed passing `community.id`, or using space repository to get the space directly. 
(I recommend the first option, because I think, spaceID is the root spaceID, regarding the error thrown)

Needs notifications testing to make sure that the current space is referenced in the notification.

**To Reproduce**
1. Go to acceptance / My Dashboard
2. Click on Add virtual contributor (you'll need to have a space your user owns, less than 3 other VCs)
3. Fill the form.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected as part of the fix**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Closing. not reproducible on acc env.
