### ISSUE TITLE
BUG: creating a space with an existing nameID is giving internal server error

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4222]
**Describe the bug**
Create a new space on production with the 

<img width="1022" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2k4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3ce31a90bd42aa117c17617c1ab348fde8ec328/image.png" alt="image.png" />

<img width="1056" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3E4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86cf508f2e06172e56ad1c490b804402bd7c8c94/image.png" alt="image.png" />

**To Reproduce**
1. Go to production, create a new space with name "test"

**Expected behavior**
The user should receive a message that the chosen nameID (url path) is already taken and that is handled on the client.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
