### ISSUE TITLE
Allow a user to retrieve the roles they have on the platform

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4225]
## Description

As a user I want to be able to have an experience that is tailored to my role

## Acceptance criteria

- [ ] platform entity extended with a "myRoles" field that returns the set of PlatformRoles assigned to the currently logged in user
- [ ] Split out platform role management into a separate module

## Additional Context
Similar to what is there on Community, but for the Platform.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
<img width="1309" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTNFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6913f030741232f665e98afe37dbb843bcee97e3/image.png" alt="image.png" />
