### ISSUE TITLE
BUG: PlatformStorageConfig fails on Forum page, for newly registered users

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4227]
**Describe the bug**

**To Reproduce**
1. Go to acc-alkem.io with newly registered user
2. Go to : https://acc-alkem.io/forum - error is thrown: `"message": "User (comoque+185@gmail.com) does not have credentials that grant 'read' access to StorageAggregator.directStorageBucket"`
<img width="1467" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejI5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ca81fff67d982edcb831d12cc6974c2a6bd7a63/image.png" alt="image.png" />

**Expected behavior**
Newly registered users can access Platform forum without getting errors.

**Comment by techsmyth** [comment]
@ccanos the question I have is why the platform storage config is being loaded when displaying the forum? Do we need to add forum into the list on the client in StorageConfigLocation?

**Comment by bobbykolev** [comment]
As far as I know, we're using the platform storage from time to time, when there's no explicit contextual one. 
I guess we can add a 'forum'. It's for the image upload markdown.

**Comment by ccanos** [comment]
@techsmyth @bobbykolev Exactly, forum doesn't have a storageBucket, so everything uploaded to the markdown ends up in the platform storage.
We can add a storage for the forum, but, as Bobby says, we use platform storage in a few other places too, when there's no storage yet... 
An example that I can think of, when creating a new InnovationPack, the images uploaded to the description when the IP is not yet created need to be uploaded somewhere
