### ISSUE TITLE
Allow callouts with the same displayName

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4232]
## Description

As a user I want to call my callouts the same, e.g. per state in a flow

## Acceptance criteria

- [ ] Allow callouts with the same displayName

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@SimoneZaza are you ok with this?

**Comment by SimoneZaza** [comment]
@techsmyth yes absolutely! Great to have this

**Comment by techsmyth** [comment]
Great. Client change is separately raised in #6548
