### ISSUE TITLE
Reserved nameIDs for spaces

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4237]
## Description

As a sys admin I want to reserve some routes for a client

## Acceptance criteria

- [ ] Server to have a list of reserved nameIDs that cannot be used for creating spaces

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
Done as part of https://github.com/alkem-io/server/issues/4342
