### ISSUE TITLE
BUG: error message when vc is not found

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4245]
**Describe the bug**
Going to the following URL on production: https://alkem.io/vc/marketingstrategy
gives an error that is not helpful.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOS9MQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6903f9ba5c26e4f2eaac846eb5c7dbb33f84cec/image.png" alt="image.png" />

**To Reproduce**
Steps
 to reproduce the behavior:
1. Run the above query 

**Expected behavior**
The server should give an error message stating that the requested VC could not be found

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected as part of the fix**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Tested OK on DEV env:
<img width="1457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--820e60312cae227f140ecffe3910c5c472c47b48/image.png" alt="image.png" />
