### ISSUE TITLE
BUG: Cloned subspace is created empty (without callouts)

### ISSUE THREAD

**Issue by ccanos** [cherrytwist/Server#4248]
**Describe the bug**
Passing `collaborationTemplateID` to `CreateSubspace` makes the subspace be created empty

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected as part of the fix**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Tested OK on DEV env with the following mutation:
```
mutation createSubspace($input: CreateSubspaceInput!) {
  createSubspace(subspaceData: $input) {
    id
  }
}


```
```
{
  "input": {
    "spaceID": "qauserspace",
    "context": {
      "vision": "cloned5"
    },
    "collaborationData": {
      "collaborationTemplateID": "4861bce5-61f7-4c7d-b290-1b5ea8116b46"  //Cloned collaboration id      
    },
    "profileData": {
      "displayName": "cloned5",
      "tagline": "Subspace to clone",
      "description": "Subspace to clone\n"
    },
    "tags": [
      "Subspace to clone"
    ]
  }
}
```
