### ISSUE TITLE
BUG: MyAccount doesn't show the space I'm the host of *

### ISSUE THREAD

**Issue by bobbykolev** [cherrytwist/Server#4251]
**Describe the bug**
My Account block is empty even when I have a space that I created and I'm the host of it.

The space on prod:
https://alkem.io/vinsight

**To Reproduce**
Note that my role was changed - GS removed. Not sure whether this could cause the issue.
1. I have a space;
2. The space is not shown in the MyAccount widget;

**Expected behavior**
The My Account block should display a space that I'm the host of.

**Screenshots**
<img width="1382" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3pQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a576e0607d59b00e9022774c93c89698ada84911/image.png" alt="image.png" />

**Additional context**
me request returns an empty array of mySpaces:

Request:
```
query MyAccount {
  me {
    mySpaces(showOnlyMyCreatedSpaces: true) {
....
```
`
Note that reset of the account and authorizationPolicyResetOnUser were done. No change.

**Areas that will be affected as part of the fix**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
The issue is not reproducible on ACC env considering also the information from Additional context.
