### ISSUE TITLE
BUG: Platform StorageBucket is not inheriting permssions from the parent storage aggregator.

### ISSUE THREAD

**Issue by ccanos** [cherrytwist/Server#4255]
**Describe the bug**
Normal users cannot read the `platform` > `storageAggregator` > `directStorageBucket`.
The myPrivileges are empty.

This causes issues like this:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0RRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52960dfd660347c72d2ead85ecc7369cee22d866/image.png" alt="image.png" />
because users cannot read the files 

or like this:
<img width="1164" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0hRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e78af6da4ed030b6cca7cbf502af1b01569dcb97/image.png" alt="image.png" />
because users cannot upload files (note the missing clip on the right of the input.

The result of this query:
```
query PlatformStorageConfig {
  platform {
    storageAggregator {
      authorization {
        myPrivileges
      }
      directStorageBucket {
        authorization {
          myPrivileges
        }
      }
    }
  }
}
```

is this:
<img width="691" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2pRQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--504b99c82619ec5419eec963477fb1d00abe4604/image.png" alt="image.png" />

**Additional Context**
looks like the rule is not inherited by the StorageBucket because we are extending SA rules after pushing them to the children SB.
I mean, what's happening at the moment is:
platform: `platform.service.authorization.ts:168` calls `StorageAggregator.applyAuthorizationPolicy`
SAgg: `storage.aggregator.service.authorization.ts`
    - reset rules, `line:53`
    - inherit rules from platform, `line:57`
    - push rules to children `line: 62`
then return to platform and then calls `extendStorageAuthorizationPolicy line:174`
so the new rules are not pushed to the children.
SA is extended okay, but not affecting the children SB
 
 
we have tried 2 approaches, but we couldn't decide which one was best or if they were even correct:
- We could add the privilege to the platform rules, then it's inherited by the storage aggregator because when the SA resets rules, the parent(`platform`) already has the rule.
But, this also affects the SA of the library. so I think it's discarded
- We tried also to separate the logic that pushes the rules to the children SB in the SA to another function and called that from the platform so it was
   - platform calls StorageAggregator.applyAuthorizationPolicy
     - SA resets rules
     - SA inherits rules
  - platform expands rules of SA
  - platform calls SA to push the rules to its children
  We are also not sure if this is correct because this changes affects to all SAs and we need to refactor them then

**To Reproduce**

1. Login as a normal user
2. Go to `/graphql` and execute this query:
```
query PlatformStorageConfig {
  platform {
    storageAggregator {
      authorization {
        myPrivileges
      }
      directStorageBucket {
        authorization {
          myPrivileges
        }
      }
    }
  }
}
```
3. See that `myPrivileges` inside `directStorageBucket` is empty

**Expected behavior**
- Logged in users should have `READ` and `FILE_UPLOAD` privileges in directStorageBucket.
- *I think* not logged in users should have `READ` privilege, to allow download of forum discussions images.

**Areas that will be affected as part of the fix**
Forum

**Comment by techsmyth** [comment]
@ccanos @hero101 your analysis is spot on, it was indeed passing down the tree before being extended, so that the extended rules were not available further down. Please see the changes in the associated PR - this is the correct logic: clone + extend before passing into the child. I had updated a few other places but missed this one.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
<img width="1404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1RXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa0e8421905d35e8da1268183b593cd564c0172a/image.png" alt="image.png" />
