### ISSUE TITLE
BUG: GraphQL query returns MATRIX_ENTITY_NOT_FOUND_ERROR

### ISSUE THREAD

**Issue by sander** [cherrytwist/Server#4266]
**Describe the bug**
In [choral-explanation](https://github.com/sander/choral-explanation), the [questions query](https://github.com/sander/choral-explanation/blob/c26b03b827a829251cad9208b4e4dc865d2502ad/queries.graphql) that used to work 2024-03-17, stopped returning the expected data and returns many `MATRIX_ENTITY_NOT_FOUND_ERROR` errors.

**To Reproduce**
1. Check out `choral-explanation`
2. Run the first code block in `prototype.ipynb`.
3. Run the second code block in `prototype.ipynb`.

**Expected behavior**
See first result data: `"{'nameID': 'toelichting-2833', 'type': 'POST', 'createdBy': {'profile': {'url': "`.

**Screenshots:** N/A

**Desktop:** N/A

**Smartphone:** N/A

**Additional context**
It seems to be the same error message as in https://github.com/alkem-io/server/issues/2557.

**Areas that will be affected as part of the fix**
N/A

**Comment by techsmyth** [comment]
@sander we had an issue with the communications (matrix) about a week ago, for which we still had a known issue with deleting messages on older rooms - but this looks like something else. We can look more on Monday - hope that is ok?

**Comment by sander** [comment]
Of course, no hurry, thank you @techsmyth.

**Comment by valentinyanakiev** [comment]
I reproduce this with version `0.3.4` of the adapter, both with matrixadmin and matrixadmin3.

**Comment by valentinyanakiev** [comment]
Query works fine with matrixadmin and matrix adapter v `0.4.5` locally

**Comment by valentinyanakiev** [comment]
I have pretty much confirmed this being an account issue, doesn't work with matrixadmin2 (used in production), works with matrixadmin

**Comment by sander** [comment]
@valentinyanakiev is there a workaround or a way I can fix it for the `tip` space?

**Comment by valentinyanakiev** [comment]
Hi @sander - unfortunately not, but I am currently working on a structural fix, top of my priorities. I hope to be able to share some good news soon...

**Comment by valentinyanakiev** [comment]
@sander - the root cause of the issue should be resolved now - can you please check and let me know if it works for you?

**Comment by sander** [comment]
Thanks @valentinyanakiev, the query works again without errors.
