### ISSUE TITLE
Kratos account type exposed as field on user entity

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4268]
## Description

As a sys admin or global support I want to be able to help users having login issues

## Acceptance criteria

- [ ] Add a field to the User entity called "authenticationType" which is an enum with the following values: EMAIL, MICROSOFT, LINKEDIN
- [ ] Field information is retrieved from Kratos

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on DEV env.
