### ISSUE TITLE
BUG: storage page errors

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4280]
**Describe the bug**
There are many errors on the storage page of certain spaces:
https://alkem.io/tip/settings/storage

<img width="1897" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHp6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb6ae16a92540609f6931782e6f6ea1691cb2f6f/image.png" alt="image.png" />

**To Reproduce**
1. Go to https://alkem.io/tip/settings/storage
2. Open graphql explorer

**Expected behavior**
There should not be errors

**Comment by techsmyth** [comment]
Fixed by deleting orphaned data

**Comment by Comoque1** [comment]
Cannot reproduce on DEV env.
The concrete space from repro steps has the storage accessible for GA.
