### ISSUE TITLE
VCs to use storage aggregator of parent account

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4299]
## Description

As an account holder I want to see all the storage I am using in my account

## Acceptance criteria

- [ ] VCs to use the storage aggregator from the parent account, not have their own one

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Expose storageAggregator  to account api and make the client to store the documents to account storageAggregator
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0VuQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9ce18893a2bc2df5326391506c2a8e1e19ce9d7/image.png" alt="image.png" />
