### ISSUE TITLE
Accounts without spaces on PROD

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4300]
**Describe the bug**
After running authorization policy reset on PROD, there were 3 accounts without spaces:
```
Resetting authorization for account with id 9cde7f0a-a4ba-4512-855d-430841c00c0a failed! Max retries reached. Rejecting message.",
"Resetting authorization for account with id bacd987b-64bf-4b45-aba8-92b3172d5c9d failed! Max retries reached. Rejecting message.",
"Resetting authorization for account with id 7a1b9cef-b858-43f6-8331-34850b0306c4 failed! Max retries reached. Rejecting message."
```
Querying the accounts data results in: 2 of them are with host: "neil-smyth-admin" and 1: "stefantest-kunst"
<img width="1496" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW9BQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4626fe52f5e02f67b2011cfea4df9cb60a0f889f/image.png" alt="image.png" />

<img width="1654" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXNBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--117e9a18aba84ddabc396799a5be5c89dca2d408/image.png" alt="image.png" />

**Expected behavior**
There are no accounts without space.

**Additional context**
The problem could have been caused by partially created / deleted space

**Comment by techsmyth** [comment]
Yes these are the result of the outage we had when matrix startup failed. They can be deleted.

**Comment by Comoque1** [comment]
Results look OK on DEV env after executing the Migration:
<img width="1112" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEZHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--454ac83f6acf6bf6e59f4915a0f83011e8b1cd33/image.png" alt="image.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--234315fbb2016e09218c2dd43e73bd3256de99d4/image.png" alt="image.png" />

<img width="1342" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGhHQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c64ff5ba5cfa3c7a43cca90ad00bcae4e81c107/image.png" alt="image.png" />
