### ISSUE TITLE
Spaces to know level zero space ID

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4302]
## Description
As a user I want a simple conceptual model
As a developer I want a maintainable code base

## Acceptance criteria

- [ ] Each space should know what its level zero space is

## Additional Context
This issue is a key step to enable having multiple spaces per account.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
<img width="1328" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW9jQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61a96d111e4a5d17296dae01091a80e573814977/image.png" alt="image.png" />
