### ISSUE TITLE
BUG: There are parentDisplayId with value "account-undefined"

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4338]
**Describe the bug**

**To Reproduce**
1. Perform the following query against dev env DB: `SELECT * FROM alkemio.agent;`
2. There are many parentDisplayId with value "account-undefined"
<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2dxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb6b21c9672faaa426332aca3bc699800b6adbf6/image.png" alt="image.png" />

**Expected behavior**
TBD

**Comment by techsmyth** [comment]
This field is being removed from the Agent entity, so it can be ignored
