### ISSUE TITLE
Account StorageAggregator exposed via API

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#4339]
## Description

As an account holder I want to see all the storage I am using in my account

## Acceptance criteria

- [ ] Account to have field resolver for StorageAggregator

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK locally:
<img width="1437" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--879ffb6d2f80ced64b4fe9923e700072dad8c559/image.png" alt="image.png" />
