### ISSUE TITLE
Auto-generate nameId of a space if it's not provided by the client

### ISSUE THREAD

**Issue by bobbykolev** [cherrytwist/Server#4342]
## Description

With the automated space generation (VC creation flow) the nameId creation make sense to be on the server.
Otherwise, the client need to check against existing nameIds. This approach has two caveats - 1. additional API call; 2. the user might not have the privileges to read all existing Spaces' nameIds.

## Acceptance criteria

- [ ] On space creation, if no nameID is passed by the client, the server should generate one using the  provided 'profile.displayName'. In case of an already existing one, apply logic for creation of other entities (numbers after the name).
- [ ] …

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Updating space nameID from admin section is failing:
<img width="1303" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzgwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cf9bdba17c393f727c65ae529a602c5c4b99c6c/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@Comoque1 I was getting a different error, which was blocking the updating. Please see PR that I just tagged you in...
