### ISSUE TITLE
Spike: GraphQLPlaygroud alternative

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4345]
## Description

As a developer / user of Alkemio I would like to be able to interact directly with the api effectively

## Acceptance criteria

- [ ] Investigate alternatives to grapql playground which has been orphaned

## Additional Context
https://www.apollographql.com/docs/apollo-server/v2/testing/graphql-playground/

## Areas that will be affected 
Server deployment / access to playground

Also affects being able to demonstrate access to the api for strategic sales

https://github.com/graphql/graphql-playground/issues/1429#issuecomment-2274843437

## Options: 

	1.	GraphiQL:
	•	Description: One of the earliest and most popular tools for interacting with GraphQL APIs. It’s a browser-based IDE that allows you to write and test GraphQL queries.
	•	Features: Autocomplete, syntax highlighting, query history, and the ability to explore the schema with an in-built documentation explorer.
	2.	Insomnia:
	•	Description: A powerful REST client that also supports GraphQL. It’s widely used for testing APIs.
	•	Features: Schema introspection, request templating, environment variables, and the ability to work with different kinds of APIs including REST and GraphQL.
	3.	Altair GraphQL Client:
	•	Description: A feature-rich GraphQL client that can be used in the browser, as a desktop app, or as a browser extension.
	•	Features: Support for GraphQL subscriptions, custom headers, variable handling, and multiple environments.
	4.	Postman:
	•	Description: While primarily known as a REST client, Postman has added extensive GraphQL support, making it a versatile tool for working with APIs.
	•	Features: GraphQL schema introspection, query building, variables, and collection management.
	5.	Apollo Studio Explorer:
	•	Description: Part of the Apollo ecosystem, this is a web-based IDE tailored for working with Apollo-managed GraphQL servers, but it can also work with other GraphQL endpoints.
	•	Features: Real-time collaboration, query history, schema documentation, and performance tracing.
	6.	GraphQL Editor:
	•	Description: A graphical tool for creating and testing GraphQL schemas. It allows you to visualize your schema and build queries.
	•	Features: Schema visualization, query execution, and the ability to mock data responses.
	7.	Hasura Console:
	•	Description: If you are using Hasura for your GraphQL backend, the Hasura Console provides a comprehensive interface to manage your database schema and run GraphQL queries.
	•	Features: Automatic schema generation, database management, and a built-in GraphQL IDE.

These tools offer a range of features that might suit different use cases depending on your needs for querying, schema exploration, and API testing.

**Comment by bobbykolev** [comment]
GraphiQL looks good, it's a react app, it has history, and when you refresh, it perists the tabs.

<img width="1558" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekxVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8eab87d235e42edfed16b54282ee4d6fd93851f/image.png" alt="image.png" />
