### ISSUE TITLE
BUG: Accounts agents is failing

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4352]
**Describe the bug**

**To Reproduce**
1. Go to 'https://dev-alkem.io/graphql' with GA
2. Perform the following query
```
query{
  accounts{
    id
    createdDate
    
   id
    agent{
      credentials{
        issuer
      }
    }
  }
}
```
3. Error is thrown: `"message": "User (admin@alkem.io) does not have credentials that grant 'read' access to Account.agent with id '20b03f0f-2eff-4400-9a0b-b1b3ae182369' with authorization: 76ded92a-01df-4522-95e3-0e6fd70d2030",`
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWd3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95fe2f4c6cc628fb452ebbb07ea71f46c5f1b288/image.png" alt="image.png" />

**Expected behavior**
Error is not thrown.

**Comment by techsmyth** [comment]
Needs investigating after the orphaned accounts are removed

**Comment by Comoque1** [comment]
Not reproducible on dev env.
