### ISSUE TITLE
Remove agent parentDisplayName field; add type

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4358]
## Description

As a developer I want a clean code base

## Acceptance criteria

- [ ] Remove field parentDisplayName from Agent
- [ ] Add type field onto Agent to make tracking of issues easier

**Comment by Comoque1** [comment]
Tested OK on DEV env.
<img width="1820" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTVNQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be1eb10f83143838d80093098ad075e181017e0b/image.png" alt="image.png" />
