### ISSUE TITLE
BUG: Unable to create a space

### ISSUE THREAD

**Issue by bobbykolev** [cherrytwist/Server#4376]
**Describe the bug**
As GA (all roles) I'm unable to create a space - getting an error - with the latest changes from the server (develop).

**To Reproduce**

1. Go to /create-space route
2. Fill the space data and click create
3. Observe the error: ERROR  Cannot convert object to primitive value - {"stack":[{"errorId":"4f66d1a2-4e1e-4d85-b645-a4f1cf05b988"}],"error":{}}

**Expected behavior**
Space creation shuld work as expected - creating account, space, etc. successfully.

**Screenshots**
<img width="1632" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fc1cc4faedb95df12b989ded8cd0a07e588e9ec/Screenshot%202024-08-07%20163219.png" alt="Screenshot 2024-08-07 163219.png" />

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by Comoque1** [comment]
Tested OK on ACC env.
