### ISSUE TITLE
LinkedIn avatar links 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4392]
## Description

As a user I want to see avatars for users

## Acceptance criteria

- [ ] Identify LinkedIn avatar links i.e. where we directly access linked images as the user avatar
- [ ] Move those avatars to be stored on Alkemio if accessible. If not accessible then switch to the default avatar with letters.
- [ ] Possible to get the actual avatar next time user logs in / ask the user if they want that?
- [ ] ...

## Additional Context
See Sentry to get a feel for the sheer number of errors this is generating:
<img width="1683" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFLQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7502b11e459bc77cfaa66f504eed709c4a26fcab/image.png" alt="image.png" />

**Comment by bobbykolev** [comment]
Looking into this issue I was thinking...
Can we introduce a 'Generate Default' button? That way, it would be a click of a button for both our GS and the users to fix broken avatars.

<img width="1279" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejlkQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e000751ac9d09dba3f98c26c32bf6b93512ec1a0/image.png" alt="image.png" />

**Comment by bobbykolev** [comment]
The `users-avatar-excel` script is available in the https://github.com/alkem-io/cli project. It extracts information about the users' avatars in an Excel file grouped in sheets based on the avatar status. Currently, we have 98 inaccessible avatars on PROD.

The script can also generate default images for the inaccessible avatars, download them into a local 'avatars' folder, and try to upload them. Only the last step is not working at the moment. (use the following flag for the generation: npm run users-avatar-excel -- --generate-default)

@DonnaDuiker is documenting and driving the manual upload of these avatars.

**Comment by Comoque1** [comment]
Number of inaccessible avatars on prod is 0.

<img width="483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGg4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d21ef11397a30aaeebcd93fcada72f17f3288c0f/image.png" alt="image.png" />
