### ISSUE TITLE
LinkedIn retrieved avatars stored on Alkemio

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4408]
## Description

As a user I would like my profile picture to be stored as part of my newly created profile

## Acceptance criteria

- [ ] The LinkedIn avatar to be retrieved and stored within the users profile creation on the platform

## Additional Context
The code for this is currently commented out in UserService.createUserFromAgentInfo

**Comment by valentinyanakiev** [comment]
No need to change configuration, the picture comes in the claims already.
