### ISSUE TITLE
Whiteboard / profile authorization reset to not load the contents

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4417]
## Description

As a user I want a fast application

## Acceptance criteria

- [ ] Authorization reset should not load content fields from potentially heavy entities such as whiteboard content + profile description

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by valentinyanakiev** [comment]
After auth reset on ACC, GA:

<img width="1721" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK21kQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d478b001d134d12210e693485b85b7794d7d7a0/image.png" alt="image.png" />

<img width="1270" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3FkQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c80d55f0932f075f72d89f7a0b4baec06ec01d4c/image.png" alt="image.png" />

@techsmyth @hero101 that doesn't seem right for a GA to me.

**Comment by valentinyanakiev** [comment]
after switching the share settings of the [whiteboard](https://acc-alkem.io/release-03-08-23-hub-cont/collaboration/testbugcheckout13-4726)  back and forth, the controls appeared, so it is definitely an auth reset issue. The issue can be reproduced on [another whiteboard](https://acc-alkem.io/release-03-08-23-hub-cont/collaboration/testbugcheckout12-9120) in the space

**Comment by techsmyth** [comment]
@valentinyanakiev issue with whiteboard was with contentUpdatePolicy not always being loaded, meaning UPDATE_CONTENT privilege was missing. Worked in some code paths and not others, and missed as we had the auth policy reset being done from within the business logic service. 

Fixed as part of PR related to how whiteboard auth is done as that was also touching the same code area + moving all auth reset to the whiteboard auth service.
