### ISSUE TITLE
BUG: On ACC DB, there are agents with type: "null"

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4421]
**Describe the bug**

**To Reproduce**
1. Connect to acceptance database
2. Run the query `SELECT * FROM alkemio.agent where type is null` - 22 records are returned
<img width="1357" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDlvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de109fa8d1c9e52977708a30135262039fe94e35/image.png" alt="image.png" />

**Expected behavior**
All agents have type value

**Comment by valentinyanakiev** [comment]
no longer the case
