### ISSUE TITLE
BUG: SaveAsTemplate and WHITEBOARD_MULTI_USER privileges are missing

### ISSUE THREAD

**Issue by EmiliaPavlova** [cherrytwist/Server#4448]
**Describe the bug**
collaboration.authorization.myPrivileges is missing the SaveAsTemplate privilege when the flag is enabled.

**To Reproduce**
1. Create a space
2. Make sure the flag for saving a template is enabled
3. Go to the space dashboard and open the settings menu of a callout
or perform the following query:
```
query {
  space(ID: "15f2c364-88f6-4a17-b58a-39234a94d1b5") {
    subscriptions {
      expires
      name
    }
    licensePrivileges
    collaboration {
      authorization {
        myPrivileges
      }
    }
  }
}

```
4. The option Save as Callout is missing
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2FCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebc2ee53aca558947c06fffc4a3b2aea81250fa1/image.png" alt="image.png" />

**Expected behavior**
The SaveAsTemplate and WHITEBOARD_MULTI_USER privileges to be present when enabled.

**Comment by Comoque1** [comment]
Tested OK locally
