### ISSUE TITLE
BUG: Accepting invitation doesn't set correct "nextEvents" states

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4457]
**Describe the bug**

**To Reproduce**

1. Go to Dev env
2. Invite a user to a space
3. Using the invited user accept the invitation
4. See error: User doesn't become a member of the space after accepting the invitation:
<img width="1584" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2g5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb52b1902dc810a330c575f05f92e8e5672fba7a/image.png" alt="image.png" />

<img width="1780" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2w5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45bf34a0848c01cb53390be77a9faf7065bc9953/image.png" alt="image.png" />

**Expected behavior**
Correct nextSteps are applied.
User becomes space member.

**Comment by techsmyth** [comment]
Just tried this with both a user + a VC, and in both cases it worked perfectly. The issue may have been related to the bug with picking up the wrong agent for licensing...

**Comment by Comoque1** [comment]
With latest develop branch of server, the issue is not reproducible.
