### ISSUE TITLE
BUG: When GA create a space on ORg Account, Org admins, don't have rights to create posts and assign VCs

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4464]
**Describe the bug**

**To Reproduce**
1. Go to server-4445 with GA
2. Create an Organization
3. Create a Space
4. Enable VC license (is not available)
5. Assign user as Org admin
6. Assign user as part of VC campaign
6. Using the organization Admin, start VC flow (Written knowledge) from Org admin section
7. Error is thrown for "createPostFromContributorTab": `message": "Authorization: unable to grant 'contribute' privilege: create contribution on callout: 074daa5e-b17f-4371-adc5-4c05a7a66260 user: 489958da-d35a-42d4-ba64-6d56be89913f on authorization of type 'callout'",`
<img width="1403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHlIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c3b735f7083690f66d45644f96b265f4b908ec1/image.png" alt="image.png" />

If the ORG ADMIN is added as member to the space, and trigger the same flow, fails with error for `AddVirtualContributorToCommunity`: ` "message": "Authorization: unable to grant 'access-virtual-contributor' privilege: assign virtual community role VC privilege: 18fa66e8-2693-4ec7-9976-f913d705bada user: 489958da-d35a-42d4-ba64-6d56be89913f on authorization of type 'community'",`
<img width="1423" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUNIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cfc2ad27f83e043d9b045dae130f75098e6e914a/image.png" alt="image.png" />

**Expected behavior**
TBD

**Comment by techsmyth** [comment]
```
query {
   platform {
    licensing {
    	plans {
        licenseCredential
        assignToNewUserAccounts
        assignToNewOrganizationAccounts
      }
  	}
  }
}
```

<img width="961" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVdIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6306f55a8e4bdd81cff2cdb5d29bdaddb4d991dc/image.png" alt="image.png" />

So a small migration to switch one flag would fix it.

**Comment by bobbykolev** [comment]
See the PR for details. Here are some of the fixes included:
1. Add type to account so can see whether for a user or an org;
2. Updated licensing framework to add additional license credentials, privileges and rules to work with the credentials;
3. Added an additional license plan for plus license on Account, temporary license plan;
4. Assigned this plan to all user accounts with beta tester or vc campaign membership;
5. Updated logic for assigning platform roles to assign the license plan to the associated user account.
6. Global roles now have Create VC/Space/Pack/Hub privileges;


Not resolved and needs further planning and fixing:
- need to look at how to assign this license credential to organizations, that is still an issue.
- client to filter out the account licenses from the space licenses;
- Further, implement a mechanism for assigning a license to an account;

**Comment by Comoque1** [comment]
Organization Admin doesn't have rights to create any entity on Organization account.
And second thing - the organization admin has "Transfer resources" privilege, which doesn't seem correct.
<img width="1524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTZZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a33a7b282d05cc7071a41aca4b31bc44658d7ab/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@Comoque1 correct, the org resources will for now need to be done with support roles for now. This needs to be separately raised, can you please raise it? Also good point re transfer, we can consider removing admin from being able to transfer resources + restricting that to owners

**Comment by techsmyth** [comment]
Note: neither blocks this release
