### ISSUE TITLE
Spike: Investigate new excalidraw server side architecture

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4483]
## Description

As a <persona or stakeholder type>
I want <some software feature>
So that <some business value>

## Acceptance criteria
- [ ] Architectural design, both now + desired
- [ ] Evaluate effort to adopt new approach
- [ ] Effort needed to move to excalidraw v.next
- [ ] …

Timebox: 1.5 days

## Additional Context
https://github.com/excalidraw/excalidraw/pull/7348

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by hero101** [comment]
### Progress so far

- The fork is synced with Excalidraw and a version is released
- The changes in `0.17.0-alkemio-4` have not been merged to `main` or `develop`
- I have created the branch `0.17.6-5a11c70` with merged changes from `0.17.0-alkemio-4` and excalidraw master
---
- I have not figured out a way to build and publish the package to npm

**Comment by hero101** [comment]
As a result of this investigation, I have managed to bring the reconciliation of the state on the server to a reasonable state. 
- the state is built on the server (let's called it a snapshot)
- the snapshot is saved to the database and to initialize the scene of newly created clients
- based on the testing done on two separate occasions - with 2 and 6 people the state is correctly built, saved, and initialized for new clients
- changes are done to the collaboration server, whiteboard server, and client

### What I DID NOT do
- upgrade to the latest version of Excalidraw (0.17.6 stable)
- merged the changes from `0.17.0-alkemio-4` to our fork's master branch or `0.17.6`.
