### ISSUE TITLE
Sort Explore Spaces section on most activity

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#4517]
## Description

As a person exploring/evaluating the platform, I do not get a good impression when the first spaces I see are ones without an avatar and without active usage when I click on them

## Acceptance criteria
Sort the cards on the page based on
- [ ] The first 30 Active Spaces (level 0), ordered on Most activity in the last 30 days

**Comment by SimoneZaza** [comment]
@hero101 Please let me know if you need anything else. As mentioned, our main goal is to create a visually appealing page with engaging spaces to click on. Given all the current priorities, we're aiming for a quick solution, which is why I've added some options to consider as proxies in the issue. If you have any other thoughts, happy to discuss!

**Comment by Comoque1** [comment]
Tested OK for unauthenticated users.
