### ISSUE TITLE
Tutorials instead of Default Collaboration tools

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#4519]
## Description

As a user, I want to understand what it is that I (de)select when I click on Add Default Collaboration tools
As an admin setting up a (sub)space for someone else, I want to be able to turn on some extra guidance for them

## Acceptance criteria

- [x] Change "Default Collaboration tools" into "Tutorials"
- [ ] Adding tutorials should be independent of the subspace template/innovation flow, and they should just be added to the first state of the innovation flow
- [ ] Also give the option to "Add tutorials" when creating a Space, so the current "default collaboration tools" can be turned off as well when creating a space

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
@SimoneZaza , let's revise this after the latest changes. We're using both default and tutorials.
