### ISSUE TITLE
Only show verified organizations on Explore Contributors page

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#4523]
## Description

As an organization, I don't want my logo to be shown on the contributors page if I didn't verify that it's indeed our organization

## Acceptance criteria

- [ ] In the organizations block on the Find Contributors page (https://alkem.io/contributors) only show organizations that are verified

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
When there are more than 16 verified organizations, they are also displayed:
<img width="1401" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDRrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f95a2f3620f4397d7a3deefc43105cc7d1290ed2/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
I had misinterpreted the expectations with these number of 16. So it should be all that are verified and is working like that.
