### ISSUE TITLE
BUG: Org Admins don't have privileges in the Org's spaces

### ISSUE THREAD

**Issue by bobbykolev** [cherrytwist/Server#4532]
**Describe the bug**
As an Org Admin, I can't create VCs as:
- I'm unable to create callouts in a space/subspace of that Org;
- I'm unable to add a VC to space/subspace community of the Org;

Note that this is reproducible after the Organization has granted the ACCOUNT_PLAN_PLUS (the admin user has privileges to create spaces, VCs, etc. under this account);

**To Reproduce**

**Expected behavior**
Admin users of an Org should be able to create all entities for any space of this organization without errors.
ACs:
- [x] Creator of Space should become admin of that space automatically
- [ ] Check for privileges when creating an entity under an existing space:
  - Create subspace 
  - Create callouts
  - Add member to community
- [ ] If user doesn't have the privileges needed, show dialog with text:
  - It looks like you don’t have the necessary privileges. If you’re creating this VC within an organization account that includes a space, please ensure you have admin rights for that space. This space will be used to create the Body of Knowledge and interact with the VC.

**Screenshots**
<img width="1543" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNy9PQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02974b4b109d7ae9d10a9afa5a78155b502a31cd/image.png" alt="image.png" />

<img width="1494" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOERPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed23015589ae211f1cd8ec826f058b3cd56811b3/image.png" alt="image.png" />

<img width="1717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMC9kQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac6cbcf7d7952ce23a782c401f30acb2b4bd4d9b/image.png" alt="image.png" />

**Additional context**
Relates to #6844

**Areas that will be affected as part of the fix**
_Optional, to be added by developer if relevant_

**Comment by bobbykolev** [comment]
> Creator of Space should become admin of that space automatically

This were accually in place, but the newly created Space under an Org's Account didn't have the FEATURE_VIRTUAL_CONTRIBUTORS assigned.

**Comment by SimoneZaza** [comment]
@bobbykolev I've added the text. But while doing that, I was wondering: what if there are multiple spaces in an account? Will one space be selected randomly?

**Comment by bobbykolev** [comment]
Hey @SimoneZaza , I've already put a text in the modal which is more general. The checks are related not to the space creation but to: Subspace Creation, Accessing VC and adding a VC to community. 
The copy is in the translations so it could be easily altered. 
```
"title": "Insufficient Privileges",
      "description": "You don't have the necessary privileges to complete the creation. Please contact the owners of this account."
```
<img width="1493" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlBrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae59aaf0b8407163947de3c52d4c2c2bca7e7b67/Screenshot%202024-09-18%20120502.png" alt="Screenshot 2024-09-18 120502.png" />

**Comment by bobbykolev** [comment]
@Comoque1 
QA Notes:

The changes related to this story affect the entire VC creation flow. So the flow was (should) be tested both from the Home Dash and through an Account Tab. 
The Account tab could also be divided into personal and Org's one.

**Comment by Comoque1** [comment]
@bobbykolev @SimoneZaza @techsmyth Tested the fixes on acc env and the results are as follows:
1. Newly registered user added to VC campaign group:
   1. VC flows from my dashboard: **OK**
   2. VC flows from my user account: **OK**
2. Newly registered user added to VC campaign group and normal registered user added as ORG ADMINs
   1. The user1 (org_admin) who creates first a  VC flow - OK
   2. The user2 (org_admin) who tries to creates second  VC flow - fails
   3. If user2 added as space admin to the space from the first flow and create VCs to it: OK
   4. If user2 create manually a space to the org account - VC cannot be created to it.
   
The above behavior, was already discussion with Neil and Bobby.
Neil is accepts the behavior for the moment and it is not a blocker for the release.

**Comment by SimoneZaza** [comment]
@Comoque1 @techsmyth I've created an issue for selecting a space to add VC to: #6930. Please note that this only fixes the need to have the right privilege in the space to add the VC to it, it doesn't fix the need to have the privilege to create a subspace/callouts. For this we would need to go back to the old flow, where we first ask in what space people want to create the bok...
