### ISSUE TITLE
Subspace events shown in Spaces: Server work

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#4540]
## Description
As a user, I want to show my subspace events on the parent space as well
As an admin, I want to have the option to prevent subspace events from being promoted on the space dashboard

## Acceptance criteria

- [ ] A setting per space to allow for subspace events to be displayed on the Space
- Should be on by default
- [ ] A setting on subspace events to show this event on the space as well, this option is only available when it is allowed through the space setting
- Should be off by default

## Design
https://www.figma.com/design/rddyv3LBg0sbm1b7Yny9ze/Calendar-V3?node-id=35-221&t=kBz9ml9y23WojMQ7-1

**Comment by hero101** [comment]
- In which of the 3 blocks would this setting be found? - I believe `Allowed Actions` fits best
- a new field for this setting needs to be added
- a new column is required to indicate the visibility of the event
- how deep do we want to display events - level 1 or further?
- if I assume the subspace event will be visible when the root Space events are queried, a new field should be added to indicate this event is not part of the Space events
- Can a non-member still see the events if the subspace is private and both settings are enabled?

**Comment by SimoneZaza** [comment]
All is now included in #6876
