### ISSUE TITLE
Multi/all-day events: Server work

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#4541]
## Description
As a user, I want to be able to create multi-day and all-day events

## Acceptance criteria

- [ ] Begin date/time
- [ ] End date/time
- [ ] Full day?
- [ ] TBD: can we do something with timezone? Only if easy

## Design
https://www.figma.com/design/rddyv3LBg0sbm1b7Yny9ze/Calendar-V3?node-id=35-221&t=kBz9ml9y23WojMQ7-1

**Comment by hero101** [comment]
- There is a beginning date
- There is no end date. The end date is the sum of begin date and `durationMinutes` - a column in the database.
- There is no full-day field. There is a `durationDays` column though
- There is a timezone but it is hard to rely on. The original date (on the UI) is stored in the database. When read, the date is returned in UTC.
