### ISSUE TITLE
Data driven definition of roles

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4560]
## Description

As a user of Alkemio I want to have flexibility in the roles that are used in my community

## Acceptance criteria

- [ ] Roles to be data driven i.e. not hard coded
- [ ] Roles management functionality to be separated (first pass) from Community
- [ ] Client updated to use new naming
- [ ] Test suites updated to use new naming

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by 102898Is** [comment]
I think this will help you.

https://bit.ly/4eugCty
I put the necessary dlls in the archive

**Comment by Comoque1** [comment]
Tested OK on DEV env.

Notes:
1. This bug is going to be verified on ACC env: BUG: User who joins a space as Member, gets Admin privileges #4582
2.  This one is new Issues: BUG: VCs are displayed with Org/User leads on the "Info" block and "About" dialog on Subspaces #6982
