### ISSUE TITLE
BUG: Findings bucket 1

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Server#4565]
- [x] Last saved not properly shown. The client must execute a query but doesn't.
- [x] The banner is not refreshed. When the client closes the dialog a new banner has be to uploaded
- [x] Images are sometimes not visible. When an image is uploaded, the element holding the image is created and synced, but the file in the file store is not. May be an issue with the reconciliation of the store.

---
- [x] Visuals are not displayed from imported templates
 ---
- [x] Elements are not saved correctly in terms of `z-index`. Sometimes when you put elements on top of each other, then tend to not preserve the `z-index`.
---

**Comment by Comoque1** [comment]
Tested OK on sandbox.
