### ISSUE TITLE
BUG: Migrated Callouts of callout Templates have visibility set to 'template'

### ISSUE THREAD

**Issue by ccanos** [cherrytwist/Server#4568]
**Describe the bug**
The migration that moved the `callout_template` table to `template` + `callout`, was setting `callout.visibility` column to `'template'`.
Newly created templates, are getting `callout.visibility` set to `'draft'`
Server code doesn't support `CalloutVisibility` = `'template'`.

Nothing has failed for now, but we have inconsistent data in the `callout` table:
<img width="1545" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkFFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3fe8e45479d595ff1838776a5dce250bf4a902b7/image.png" alt="image.png" />

- All callouts that are linked to a collaboration, have `collaborationId` set.
- The rest of callouts are linked to a template. They have `collaborationId = NULL`
    - The old callout template migrated have `visibility = 'template'`
    - The newly created by the server have `visibility = 'draft'`

We have two options:
A)  Change the server to allow Callout.visibility = 'template'
    - Change callout.visibility.ts to add Template value to the enum
    - Add `templateData.calloutData.visibility = CalloutVisibility.TEMPLATE;` to `template.service.ts:120 `
    - Create a migration to get all the callouts that are `visibility = 'draft'` and `collaborationId IS NULL` and `SET visibility = 'template'`
 
B) Change the migrated templates visibility to be `'draft'` for consistency
`UPDATE callout SET visibility = 'draft' WHERE visibility = 'template'`
- We lose the ability to tell which callouts are templates by just one look, but in theory all the callouts that have `collaborationId = NULL` are templates

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected as part of the fix**
_Optional, to be added by developer if relevant_

**Comment by ccanos** [comment]
See https://github.com/alkem-io/server/tree/server-4568 for option A

**Comment by Comoque1** [comment]
Tested OK locally with acc db.
Now callouts that have collaborationId null and visibility template are set to draft.
