### ISSUE TITLE
BUG: Unverifying Organization does not change it's status

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Server#4583]
**Describe the bug**
When you want to unverify the status of an Organization, the `status` field in the `organization_verification` table does not change.

**To Reproduce**
1. Go to admin organization list page
2. Click on "unverify" on an organization
3. Look at the database entry for that organization verification. The status has not changed.

**Expected behavior**
The status of the verification to change according the current status in the lifecycle.

**Additional context**
This makes it hard for developers to query raw data since the real state can only be checked through the machine state of the lifecycle.

**Comment by larssondenise** [comment]
Want to remove a few organizations that we are currently not working with from the Contributors page, but this is blocking it!

**Comment by Comoque1** [comment]
Tested OK also on DEV env.
