### ISSUE TITLE
Invitations to extra role in RoleSet

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4585]
## Description

As space admin I want to be able to invite users to an extra role

## Acceptance criteria

- [ ] Allow inviting users to join a space in an elevated role
- [ ] When the invitation is accepted, the contributor gets the extra role assigned

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Migration failed to execute on DEV env:
<img width="1340" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem9pQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--734481ea5989d5090becab196d0fc51e68b3e718/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
The above errors are not reproducible anymore, but accepting invitation, doesn't set correct state:
<img width="1687" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTRvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4bc0647778417a6a07ea88bb12a2800bba9f6e0/image.png" alt="image.png" />
<img width="1821" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95e789b468bda94d475492d392929fec4c567ab7/image.png" alt="image.png" />

**Comment by techsmyth** [comment]
@Comoque1 I tried the accepting with and without the extra role set, and it worked without problem for me:

<img width="1221" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3N0Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb71ea8db722f70d343616fe3835feae52b16739/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
When Inviting an Organization as admin or member and the organization admin accept the invitation, 4 -5 requests are throwing 502 error and the last fails (the organization becomes a member in both cases):
<img width="1505" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL012Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41b7fce18973ce033a122f4356c9402fc31d3a60/image.png" alt="image.png" />


```
mutation InviteContributors(
  $roleSetId: UUID!
  $contributorIds: [UUID!]!
  $message: String
  $roleExtra: CommunityRoleType
) {
  inviteContributorsForRoleSetMembership(
    invitationData: {
      roleSetID: $roleSetId
      invitedContributors: $contributorIds
      welcomeMessage: $message
      extraRole: $roleExtra
    }
  ) {
    id
    lifecycle {
      state
    }
    __typename
  }
}

```
```
{
  "roleSetId": "fe59a970-0945-4001-aec8-2f47a6085347",
  "contributorIds": "c78dd0d9-1336-40e9-be38-e0942903d533",
  "roleExtra": "ADMIN"
}
```

**Comment by Comoque1** [comment]
Moved as separate [bug](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/4602) the above comment and closing this one.
