### ISSUE TITLE
Entitlements support 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4594]
## Description

As a support admin I want to be able to manage licenses + associated entitlements for customers

## Acceptance criteria

- [ ] Support for entitlements at all levels of the domain model

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by valentinyanakiev** [comment]
@techsmyth this is, at the very least, in my opinion, a 40, quite possible not even considering the discussions, testing etc. Only my commits (and most have been squashed) are 40-50 in this space, there were 150 across 3 repos when I started.
