### ISSUE TITLE
Retrieve additional information about the users authentication 

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4616]
## Description

As a product admin I want to have additional information about who is using what authentication method 

## Acceptance criteria

- [ ] Extend the authentication method field on User

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
Tested OK on acc env, but raised another [task](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/server/4630) to investigate why for some users the method is unknown.
