### ISSUE TITLE
BUG: Policy reset fails on Alkemio account

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4634]
**Describe the bug**

**To Reproduce**
1. Go to Alkemio account fails to reset on PROD env.

**Expected behavior**
Alkemio account resets successfully.

**Additional context**

**Areas that will be affected as part of the fix**
_Optional, to be added by developer if relevant_

**Comment by valentinyanakiev** [comment]
circumvented the problem by resetting the policy on the account with probes disabled
