### ISSUE TITLE
Removing Custom Homepages fully

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#4636]
## Description

As a PO I want the custom homepages links to be fully removed after I delete them in the platform administration

## Acceptance criteria
To be removed from routing:
- [ ] uwv 
- [ ] inclusive innovations
- [ ] doughnut economics
- [ ] data autonomy

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by valentinyanakiev** [comment]
Managing domains have wider implications so I am not super keen to have these two (managing alkemio domain and external infrastructure) entangled - it has never been something we support. I will remove these manually @larssondenise

**Comment by larssondenise** [comment]
@valentinyanakiev yes manually is fine!
