### ISSUE TITLE
BUG: When invitation is accepted on extrarole that limit is reached, sets the invitation in status 0

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4653]
**To Reproduce** 
1. Go to community settings and add to leads;
2. Make 2 users lead of a community and invite 3rd user (as lead again);
3. Accept the invite with that user;
4. The user becomes a member. Error is thrown for the extra role as the limit is reached. The invitation cannot be removed.

<details><summary>Screenshot</summary>

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHFGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--531c4f8fd617ea75e8bd8188313dde663ccb9593/image.png" alt="image.png" />
</details>

**Expected behavior**
When the maximum is reached, no other users can be invited as leads (later there will also be a limit for admins)

- Pref. UI: Disable Lead option in dropdown, with hover "The maximum number of leads for this space has been reached."
- Also fine: When Lead is selected, show red error text below "The maximum number of leads for this space has been reached."
- Preferrably not, but also okay if others are too much work: Server error bottom right of screen with that text

Note that the situation may occur that more people are invited as leads when the first two didn't accept yet. If someone has a brilliant idea on how to solve this, please share :). Otherwise, ideally, when someone accepts, they’ll be added as a member instead of a lead, with this message: 
"The lead limit for this space has been reached, so you've been added as a member instead."

**Comment by techsmyth** [comment]
Agreed that the user should not be able to invite if limit is already reached: client check.

However the server should also not throw an error if the extra role cannot be added, or if the user is already a member of the parent space.

**Comment by Comoque1** [comment]
The scenario above doesn't trigger an error on the server anymore.
Still, the client side AC is not implemented and I am moving it back for product discussion.

**Comment by SimoneZaza** [comment]
Client AC are part of #7148
