### ISSUE TITLE
Unable to open callout

### ISSUE THREAD

**Issue by sander** [cherrytwist/Server#4663]
**Describe the bug**
One of our callouts cannot be opened.

**To Reproduce**
1. Go to https://alkem.io/tip/collaboration/welkevormenvandigitalemac-1
2. See error on the bottom right:

> Verkeerde gebruikersinvoer: Variable "$calloutNameId" got invalid value "welkevormenvandigitalemac-1"; ID not a valid UUID or NameID: welkevormenvandigitalemac-1

**Expected behavior**
I expected the callout to open. I have made it as a supplement to another callout, which has a similar title: https://alkem.io/tip/collaboration/welkevormenvandigitalemac.

**Desktop**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 132.0

**Additional context**
Instead of the broken post, I have now created a new post: https://alkem.io/tip/collaboration/watgebruikenniet-eer-land. I’d like the broken post to get removed.

**Comment by SimoneZaza** [comment]
@sander Thanks for flagging this! I've removed the broken post as requested—apologies for the hassle!

@Comoque1 Could you take a look at this? I was able to replicate the issue in our testing environment here: https://alkem.io/building-alkemio-org/challenges/testingexperiment-3692/collaboration/welkevormenvandigitalemac-1 (see 2 callouts on top)
