### ISSUE TITLE
BUG: When invited external user accept invitation as admin to a subspace, auth policy from type agent is is created without policy credentials

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4673]
**Describe the bug**

**To Reproduce**
1. Go to https://acc-alkem.io/release-03-08-23-hub-cont/challenges/release-03-08-23-cha-8670/settings/community
2. Invite external user as admin to a private subspace from a private space
<img width="1647" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1ZQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4dc88b6c904871a87ba63d96841d49c5dca7acea/image.png" alt="image.png" />

3. In alkemio db take a note of the number of auth policies with type agent that don't have credential rules
`SELECT * FROM alkemio.authorization_policy where credentialRules = '' and type = 'agent';`
4. Using the invited user register
5. After the user registers, accept the invitation
6. Check the auth policies:  `SELECT * FROM alkemio.authorization_policy where credentialRules = '' and type = 'agent';` - number is increase by 1
<img width="1089" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVNZQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59a486202d7aae3b399d87cd6a51ac6b814d9ca4/image.png" alt="image.png" />

**Expected behavior**
Credential rules are set to registered external users invited as admin to private subspace from private space.

**Comment by techsmyth** [comment]
@Comoque1 can you please check the same flow when inviting to a public space? I cannot see how the logic is specific to a subspace, unless an error is thrown during the actual assignment.

**Comment by techsmyth** [comment]
@Comoque1 scenario to reproduce is I think simpler: invite an external user, get the user to sign up (without accepting invitation), the user's agent does not have credential rules. So it is something with the registration process...

**Comment by techsmyth** [comment]
@comoque please test again after 4678 has been merged

**Comment by valentinyanakiev** [comment]
still reproducible, but the user has the right privileges, so removing the `high prio` tag. There is some bad data generated thou (can't be considered a critical bug).

**Comment by techsmyth** [comment]
@Comoque1 @valentinyanakiev simpler scenario to reproduce: invite external user to space as just a member, issue shows up...

**Comment by Comoque1** [comment]
Not reproducible on ACC env. anymore:
<img width="1449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2E5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23a579cba5650575449de9e1f658b208fa66eb99/image.png" alt="image.png" />
