### ISSUE TITLE
BUG: authorization policies without types

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4677]
**Describe the bug**
There are authorization policies without types present

**To Reproduce**
Create a clean db
look at the contents of the authorization_policy table

**Expected behavior**
All authorization policies to have types

**Additional context**
Makes the tracking down of issues easier

**Comment by Comoque1** [comment]
The issue is still reproducible with develop branch.
<img width="1709" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm1oQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--caa5474acf088e6d865dfd7f0d10cf442d97eb65/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
After running the bootstrap all policies have credential rules:
<img width="1605" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJoQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b70e728a8df2150ed3d3e7c40a35a178a657c9e/image.png" alt="image.png" />

@techsmyth do you accept this behavior?

**Comment by techsmyth** [comment]
@Comoque1  yes I accept the above behavior. Re your first comment, the screen shot you show has the type column populated for all authorization policies!

![image](https://github.com/user-attachments/assets/9b0e4bc1-9e85-41aa-9d16-bf0d1d6c2c8b)
