### ISSUE TITLE
BUG: When user accept invitation, the returned state is "invited" instead of "accepted"

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4686]
**Describe the bug**

**To Reproduce**
1. Go to dev env
2. Make invitation to a user to a subspace where the user is not a member of the parent space, with a role ADMIN
3. Open the application with the incited user
4. Open the dev tools
5. Accept the invitation - invitation is accepted successfully, but the returned state is "invited"
<img width="1751" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWVpQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--624d1095eeca497422a126f9ef636d52a6a6e7bd/image.png" alt="image.png" />
<img width="1704" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW1pQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b8cb73840118f3e6c7b2ad62cbba4d3a11fc778/image.png" alt="image.png" />

**Expected behavior**
Returned state is "accepted".

**Comment by valentinyanakiev** [comment]
I've tried with

```gql
mutation inviteContributorsForRoleSetMembership($contributorIds: [UUID!]!, $roleSetId: UUID!, $message: String, $extraRole: CommunityRoleType) {
  inviteContributorsForRoleSetMembership(
    invitationData: {invitedContributors: $contributorIds, roleSetID: $roleSetId, welcomeMessage: $message, extraRole: $extraRole}
  ) {
    id
    __typename
  }
}
```

```json
{
  "contributorIds": [
    "b56438c5-11c4-4393-b3d7-3e121648e457"
  ],
  "message": "Hi, I would like to invite you to Coördinatie TIP Werkgroep Kennis. Have a look at the Space or click on the button below to directly accept or decline the invitation.",
  "roleSetId": "a0626778-e060-44ad-a202-6113d8368e56",
  "extraRole": "ADMIN"
}
```

then accepting the role. Removed the user about 10 times and re-tried, it was OK every time

**Comment by Comoque1** [comment]
The issue here comes with the case, when User 1 makes an invitation to User 2.  User 1 tries to accept the invitation - the state doesn't change (which is correct), but error is not thrown. 
I will create another story about it.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDJuQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83546362cbf0cac91c5cf3319852df5df157b7a0/image.png" alt="image.png" />
