### ISSUE TITLE
-Innovation Packs, Innovation Library, Best Practices

### ISSUE THREAD

**Issue by jeroentskui** [cherrytwist/Server#4693]
We should consider coming up with a unified term for these concepts. 

Issue Product board next sprint - when neil is back: Donna Denise Simone Neil

**Comment by larssondenise** [comment]
This is a double one, removing if that's okay? @SimoneZaza https://github.com/orgs/alkem-io/projects/22?pane=issue&itemId=86794800&issue=alkem-io%7Cproduct%7C1342
