### ISSUE TITLE
BUG: Demo Spaces are shown

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Server#4703]
**Describe the bug**
On the dashboard for unauthenticated users, Demo spaces are shown

**To Reproduce**

1. Go to the Dashboard without logging in
2. Click on the spaces and you will find some demo spaces

**Expected behavior**
As a user, I don't expect my Space to be visible on the main dashboard when I am in Demo mode and still testing the platform
 
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by SimoneZaza** [comment]
@hero101 can you look into this (I assume the same holds for the explore spaces page) and fix it if it's small, or flag it if it's a big thing?

**Comment by hero101** [comment]
@larssondenise @SimoneZaza Could not reproduce neither on https://alkem.io/home nor on https://alkem.io/spaces

**Comment by larssondenise** [comment]
@techsmyth @SimoneZaza these are still visible on the dashboard for unauthenticated users + can be found in the search!

<img width="854" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME85Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77b4bc29b794ae61cd5c4f14599696365726c7d1/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
(there are no demo labels on the cards, but eg Gebruiker Centraal is a demo space)

**Comment by Comoque1** [comment]
Tested OK on PROD env.
