### ISSUE TITLE
Create platform privileges for beta testers and VC campaign roles

### ISSUE THREAD

**Issue by bobbykolev** [cherrytwist/Server#4704]
## Description

The client needs to treat the contributors in a specific role (beta tester & VC campaign) differently.
As we don't want to expose/query the agent credentials directly (what the client currently does),
let's introduce two new PlatformPrivileges (feel free to name them differently) PLATFORM_BETA & PLATFORM_VC.

## Acceptance criteria

- [ ] Two new privileges assigned/removed to a user once added/removed to the corresponding authorization group:
PLATFORM_BETA, PLATFORM_VC.
- [ ] …

## Additional Context
Inspired by: https://github.com/alkem-io/client-web/issues/7204
But it will solve the current issue that we have - checking the agent credentials for every user to show the Campaign block on the homepage.

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by techsmyth** [comment]
@bobbykolev @SimoneZaza there is already support for this via platform.myRoles - we should not be creating new privileges for representing roles.

**Comment by bobbykolev** [comment]
Correct! Thank you, @techsmyth.

@SimoneZaza 
In case of a user having multiple roles, I suggest a display priority as follows: 
1. GlobalAdmin, then the 2. VC campaign, and lastly 3. Beta Tester. This could be easily changed.

**Comment by SimoneZaza** [comment]
@bobbykolev Thanks, I agree. Added it to #7208
