### ISSUE TITLE
Remove Innovation flow template from client

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Server#4709]
## Description

As a user, I get confused with too many templates. Now we have the subspace templates, the innovation flow templates are redundant.
As a Product team member, I'm ready for the change :) All innovation flows are transformed into subspaces, that will be added as subspace templates once the innovation flow templates are gone (to avoid duplicates)

## Acceptance criteria
Remove from:
- [ ] Global library
- [ ] Innovation packs (profile + settings)
- [ ] Space library

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
Client - All* innovation flow related code was removed. Libraries, cards, graphql, some of the translations (not all).

**Comment by bobbykolev** [comment]
As part of this task all innovation flow templates code was removed from the client. This was critical for better user experience.
 
Let's extract another technical one for removing the redundant logic on the server.

**Comment by Comoque1** [comment]
Tested OK on dev env.
