### ISSUE TITLE
BUG: Registered user not being beta tester or VC campaign has create space/vc/innovation pack buttons enabled

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4715]
**Describe the bug**

**To Reproduce**
1. Go to dev env
2. Register new user
3. Navigate to its account - user see all button to create space/vc/innovation pack available (and can create i.e. a space)
<img width="1587" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGZIQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33bd37fb69a7a5adb27d9da2ca3713736285d88e/image.png" alt="image.png" />

**Expected behavior**
User without correct licenses cannot create space/vc/innovation pack

**Comment by SimoneZaza** [comment]
@Comoque1 What happens when this user clicks on one of those buttons? Seeing the buttons is expected, what happens next should depend on the user's license: either start the creation flow or inviting users to upgrade their account.

**Comment by Comoque1** [comment]
@SimoneZaza space can be created successfully. Please bear in mind that this is introduced with entitlement and will be addressed (if not yet).

**Comment by SimoneZaza** [comment]
👍

**Comment by Comoque1** [comment]
The client still allows to create space and fails on server validation.
Create space button on client (account / home ) pages should not open dialog for space creation.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
