### ISSUE TITLE
BUG: Triggering auth policy reset all, crashes all server pods 

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4733]
**Describe the bug**

**To Reproduce**
1. Go to acc env or get bigger dataset
2. Trigger auth reset - all serer pods start restarting

**Expected behavior**
Reset passes smoothly.

**Comment by hero101** [comment]
The more serious problem IMO is that the process is quite slow.
When I inspected the queue there were 356 messages, all unack, **not ready**.
For a single message to be ack-ed took a minute or more.

Also the servers were crashing after the  exception `Task {{UUID} not found` was thrown
