### ISSUE TITLE
Set default privacy settings of Spaces to private

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#4791]
## Description

As a PO I want to make sure that VC campaign or beta tester members feel confident that their spaces and data is private by default

## Acceptance criteria

- [ ] Set default privacy settings of Spaces created to private

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by larssondenise** [comment]
@SimoneZaza the issue we talked about!

**Comment by bobbykolev** [comment]
Can you confirm whether the requirement is only for Space (level zero) or all space levels?
@SimoneZaza
